cli/scale.go, controller/client/client.go, test/test_cli.go, test/test_scheduler.go
This also fixes some cases that did not properly handle the channel being closed, which resulted in panics in some error paths.
=> all: Use Stream interface for controller client StreamJobEvents

script/release-flynn
=> script: Re-exec release-flynn from commit being released

website/source/blog/2015-01-05-this-week-in-flynn.md
=> website: twif 1-5-15

host/libvirt_lxc_backend.go
Setting the bridge MTU errors with EINVAL if the MTU is greater than 1500, which it will be if eth0 supports jumbo frames. The bridge should automatically use the lowest MTU of all interfaces associated with it, so this setting is not necessary.
=> host: Don’t try to set the bridge MTU

util/release/upload.go
Per https://botbot.me/freenode/flynn/2015-01-06/?msg=28894812&page=3
Signed-off-by: Nathaniel Eliot <Nathaniel.Eliot@bazaarvoice.com>
=> Adding --force to docker tag command

script/release-flynn
See commit messages for explanation.
=> Fix release script re-exec

website/source/docs/installation.html.md
Signed-off-by: Nathaniel Eliot <Nathaniel.Eliot@bazaarvoice.com>
=> Correcting documentation of discovery init-discovery flag.

discoverd2/server/backend.go, discoverd2/server/etcd_backend.go, discoverd2/server/etcd_backend_test.go, discoverd2/server/state.go, discoverd2/server/state_test.go
Incremental patch for #145.
This implements several prerequisites for implementing the HTTP/DNS APIs properly.
=> discoverd2: API prereqs

website/source/blog/2015-01-12-this-week-in-flynn.md
=> website: twif 1-12-15

discoverd2/server/etcd_backend.go, discoverd2/server/etcd_backend_test.go, discoverd2/server/state.go, discoverd2/server/state_test.go
This is an incremental patch for #145.
=> discoverd2: Implement leader election

controller/app.go, controller/common.go, controller/jobs.go, controller/jobs_test.go, controller/scheduler/main.go, controller/schema.go, controller/types/types.go, test/test_scheduler.go
=> controller,scheduler: Implement job metadata

discoverd2/client/client.go, discoverd2/client/heartbeat.go, discoverd2/client/instance.go, discoverd2/server/etcd_backend.go, discoverd2/server/http.go, discoverd2/server/http_test.go, discoverd2/server/state.go, discoverd2/server/state_test.go
Incremental patch for #145. This implements the HTTP API and client along with tests.
=> discoverd2: Implement HTTP API server and client

controller/controller.go, controller/crud.go
refs #744
Still returns martini handler func for lookup
Moving towards using httphelper pkg for Error and JSON responses
=> controller: Change CRUD helper to use httprouter instead of martini

.travis.yml, Godeps/Godeps.json, test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/install.sh
Changelog: https://github.com/golang/go/issues?q=milestone%3AGo1.4.1
=> Bump to Go 1.4.1

pkg/httphelper/httphelper.go
refs #744, #322
All errors respond with `code`, `message`, and optionally `details`
=> httphelper: Standardize response JSON for errors

Makefile, Vagrantfile, appliance/etcd/.gitignore, appliance/etcd/Dockerfile, appliance/etcd/Tupfile, appliance/etcd/build.sh
=> Fix unit test env in devbox

host/containerinit/init.go, host/libvirt_lxc_backend.go
Instead of passing the configuration via arguments, we write it to a JSON file. We were already using JSON for environment variables, and putting the arguments in a struct, so this patch mostly just renames fields.
=> host: Pass config to containerinit via JSON

website/source/blog/2015-01-19-this-week-in-flynn.md
=> website: twif 1-19-15

discoverd2/client/client.go, discoverd2/client/heartbeat.go, discoverd2/client/toplevel.go, discoverd2/health/monitor_test.go, discoverd2/server/http_test.go
=> discoverd2: Misc. client improvements

discoverd2/daemon.go, discoverd2/server/etcd_backend.go
=> discoverd2: Add daemon binary

appliance/postgresql/runner.go
This appliance will be rewritten very shortly, and we don't currently use follower mode, as it is prone to split-brain.
Disabling follower mode makes landing discoverd2 easier, so this patch changes the server to exit if there is already a leader.
=> appliance/postgresql: Temporarily disable follower mode

discoverd2/client/instance.go, discoverd2/server/state_test.go
=> discoverd2: Add Host/Port convenience methods to Instance

discoverd2/client/client.go, discoverd2/client/heartbeat.go, discoverd2/client/toplevel.go, discoverd2/server/http.go, discoverd2/server/http_test.go
=> discoverd2: Add GET /ping endpoint

router/http.go, router/http_test.go
Started adding tests to cover some untested edge cases in the router. Turns out that 2 of the first 3 tests I wrote found bugs introduced by #781.
/cc @benburkert
=> router: improve test coverage, fix some bugs

controller/scheduler/main.go
=> scheduler: Cancel restarts when removing jobs.

blobstore/blobstore_test.go, controller/controller_test.go, controller/jobs.go, pkg/postgres/postgres.go, pkg/testutils/utils.go
Extracted from the deployer branch.
=> Postgres utils

host/libvirt_lxc_backend.go
This prevents libvirt from enabling some iptables rules and starting dnsmasq which conflicts with discoverd2.
=> host: Create/configure bridge directly instead of via libvirt

router/http_test.go
Found a few more error cases that weren't being tested thoroughly. Fortunately, no bugs found this time :tropical_drink:
=> router: more tests for error cases

controller/client/client.go
=> controller/client: Fix RunJobAttached.

router/http.go
The HTTPListener.Start() function was making changes to s.Addr and
s.TLSAddr at the same time as other goroutines were trying to read from
it. This change reorders some code and changes a couple of references to
prevent the race.
Fixes #796.
/cc @benburkert
=> router: fix race conditions during Start()

discoverd2/server/http_test.go
=> discoverd2: Fix test races

bootstrap/bootstrap.go
It can take a few seconds for discoverd to come up as it first waits for etcd + flannel + network setup.
=> bootstrap: Try multiple times to connect to discoverd

discoverd/server/etcd_backend.go
If we don't do this, when etcd goes down we'll go into a tight loop spamming the logs with errors.
=> discoverd/server: Wait a second before retrying after errors

controller/client/client.go, pkg/httpclient/json.go
=> httpclient: Fix Dial for cases where we use pkg/pinned.

website/source/blog/2015-01-26-this-week-in-flynn.md
=> website: twif 1-26-15

controller/deployment.go, controller/deployment_test.go
=> controller: Return a more descriptive error for duplicate deployment.

controller/deployer/main.go, controller/deployer/strategies/all-at-once.go, controller/deployer/strategies/main.go, controller/deployer/strategies/one-by-one.go
=> controller/deployer: Add logging.

controller/types/types.go, dashboard/app/lib/javascripts/dashboard/views/app-resources.js.jsx
This makes the JSON consistent with other controller resources
=> controller, dashboard: Remove "_id" suffixes from resource json

pkg/shutdown/handler.go
The newly added consistent shutdown sequence defers shouldn't hide panics.  This change recovers them, does the usual shutdown sequences, and then re-raises the original panic (meaning we get all relevant stacks and the usual exit code for a panic).
=> pass panics through shutdown

pkg/cluster/client.go
Fixes a hang if for example connection was refused.
=> Report cluster client connect errors.

controller/deployer/strategies/main.go
When the deployer exits, the gouroutines are cleaned up, and `defer
stream.Close()` is called, which can cause the waitForJobEvents to crash.
Fixes #855.
=> controller/deployer: Fix panic.

router/http_test.go
Make sure that query params are kept intact as the request is proxied to the backend.
=> router: add a test for query params

router/api_test.go, router/http_test.go, router/setup_test.go, router/tcp_test.go
Instead of fork/execing discoverd/etcd for every test case, we can just use a single pair, which brings the test runtime down by an order of magnitude to ~2.5s.
Closes #833
/cc @benburkert @bgentry
=> router: Use a single etcd/discoverd pair for the entire test suite

host/types/types.go
This makes it easier to assemble relevant pieces of configuration in stages.
=> ContainerConfig.Merge function

pkg/httphelper/httphelper.go
=> httphelper: Prevent multiple calls to response.WriteHeader when handling errors

discoverd/server/etcd_backend.go, discoverd/server/etcd_backend_test.go
In the rewrite we dropped the workaround for coreos/etcd#407, which is still not fixed in etcd.
Original fix: f7a99cbe10cf3408c02ee7d9f016a4687e974fdf
This fixes issues adding hosts to an existing cluster, which was presenting intermittently on CI.
=> Fix discoverd leader election

controller/client/client.go, controller/deployment.go, controller/deployment_test.go, controller/schema.go
=> controller/deployer: Initial release creates placeholder deployment

router/http.go
Switch channel based error returning to normal returns.
=> router: refactor listener setup

discoverd/health/monitor.go, discoverd/health/monitor_test.go, discoverd/health/register.go, discoverd/health/register_test.go
Incremental patch towards getting rid of sdutil.
/cc @titanous
=> discoverd: Register

test/runner/runner.go
=> test/runner: Add charset=utf-8 to log Content-Type

router/server.go
Don’t register with service discovery until all of the listeners have successfully started, otherwise bootstrap may race to connect.
Closes #917
=> router: Fix race registering for service discovery

website/source/blog/2015-02-02-this-week-in-flynn.md
=> website: twif 2-2-15

host/types/types.go
=> Rename API field for consistency

host/host.go, host/volume/api/http.go, host/volume/backend.go, host/volume/manager/backends.go, host/volume/manager/manager.go
Several more isolated changes that pave the way for volume persistence.
Additional testing coming along with #924, which makes use of these changes.
=> Volume persistence incremental

test/cluster/client/client.go, test/cluster/cluster.go, test/helper.go, test/runner/runner.go, test/test_scheduler.go
This will be useful for testing installation of Flynn components.
=> test: Support booting vanilla VMs

test/rootfs/setup.sh
This is for future testing of image releases.
=> test: Add go-tuf to the rootfs

website/config.rb, website/source/_blog_pagination.html.erb, website/source/blog-list.html.erb, website/source/stylesheets/application.css.scss
=> website: Add pagination to blog

router/http_test.go, router/proxy/reverseproxy.go
If we don't attempt to hijack the client conn before we write a response
to it, the hijack may fail, but we will have no way of telling the
client or backend about that.
Couldn't think of a way to write a test for this. Any ideas?
Regardless, this should fix the issue we discussed towards the end of #926. /cc @benburkert
=> router: hijack conn before writing response

test/rootfs/setup.sh
See https://github.com/flynn/flynn/issues/949
=> test: Install inotify-tools for tup bug workaround

host/Tupfile, host/cli/download.go, pinkerton/context.go, script/export-components, script/install-flynn.tmpl, script/release-components, test/cluster/cluster.go, test/test_release.go
=> host/cli,script: Compress released config and binaries

router/proxy/reverseproxy.go
Refactor `serveUpgrade` to use a single 101 status code check.
/cc @bgentry
=> router: refactor status code check in ReverseProxy

script/release-vm-images, util/packer/ubuntu-14.04/template.json
ping @lmars 
This should fix the release build.
=> script,util/packer: Bump Ubuntu base images

controller/deployment.go
We were checking that map length was 0, when we could have a key
that is set to zero (and then len(map) != 0). Count all of the
processes instead.
Fixes #942.
=> controller: Fix deployments with zero processes.

cli/app.go, test/test_cli.go
=> Cli --yes flag

test/test_taffy_deploy.go
=> test: Add taffy integration test

script/install-flynn.tmpl, website/source/docs/installation.html.md
@domserio please review the docs change.
=> Update installation script and docs

test/cluster/client/client.go
`TestOmniJobs` uses `testCluster.Size()` to determine how many jobs to wait for, so it should not include hosts which have been removed.
=> test: Fix testCluster.Size()

website/source/blog/2015-02-09-this-week-in-flynn.md
=> website: twif 2-9-15

host/volume/manager/manager.go, host/volume/manager/persistence_test.go
Noticed some issues with consistency around deletion; fixed and added missing tests.
n.b. This should have gone in with #973 -- I'd be happy to squash it into that branch after a quick review if desired.
=> volume persistence deletion tests

host/host.go, host/upstart.conf, script/install-flynn.tmpl, test/cluster/cluster.go, tup.config
=> Installation script fixes

host/libvirt_lxc_backend.go
This allows services like the router to use discoverd DNS. Previously all jobs in the host network namespace used the host resolv.conf, but only jobs started before discoverd is up should use it.
This should fix issues connecting to postgres in #959.
=> host: Use discoverd resolv.conf if available

appliance/postgresql/api/server.go, controller/deployer/main.go
This allows apps that are not aware of service discovery to connect to postgres.
=> Add PGHOST to postgres app config

website/source/docs/installation.html.md
Signed-off-by: Anders Petersson <me@anderspetersson.se>
=> website: Simplify language in installation docs.

bootstrap/manifest_template.json, cli/route.go, controller/controller.go, controller/examples/examples.go, controller/routes.go, controller/routes_test.go, router/api.go, router/api_test.go, router/client/client.go, router/data_store.go, router/example-generator/examples.go, router/http.go, router/http_test.go, router/schema.go, router/server.go, router/setup_test.go, router/tcp.go, router/tcp_test.go, router/types/types.go, website/schema/examples/router/route_update.json, website/schema/router/route.json
Store routing state in a PostgreSQL database. Closes #549.
/cc @bgentry
=> router: Postgres datastore

website/source/_coming_soon_banner.html.erb, website/source/blog/2015-02-16-this-week-in-flynn.md
=> TWIF 2015-02-16

controller/deployer/main.go, controller/deployer/strategies/all-at-once.go, controller/deployer/strategies/main.go, controller/deployer/strategies/one-by-one.go, controller/scheduler/main.go, controller/types/types.go, controller/utils/utils.go, discoverd/client/heartbeat.go, host/containerinit/init.go, test/apps/echoer/main.go, test/helper.go, test/test_deployer.go
=> deployer: Support waiting for service discovery events

Godeps/Godeps.json, test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/install.sh
https://github.com/golang/go/compare/go1.4.1...go1.4.2
=> all: Bump Go to 1.4.2

slugbuilder/builder/buildpacks.txt
https://github.com/heroku/heroku-buildpack-nodejs/compare/197845da...c8cb21e7
https://github.com/heroku/heroku-buildpack-java/compare/cfdb4b99...a85be840
https://github.com/heroku/heroku-buildpack-scala/compare/90124426...3e533b6d
https://github.com/heroku/heroku-buildpack-php/compare/1746ff03...62bddfeb
=> slugbuilder: Bump buildpacks

website/source/docs/development.html.md
=> website: Update "Releasing Flynn" section

controller/testutils/fake_host_client.go, host/host.go, host/http.go, host/volume/api.go, host/volume/api/http.go, host/volume/backend.go, host/volume/manager/manager.go, host/volume/manager/persistence_test.go, host/volume/util.go, host/volume/volume.go, host/volume/zfs/zfs.go, host/volume/zfs/zfs_snapshots_test.go, host/volume/zfs/zfs_test.go, host/volume/zfs/zfs_transmit_test.go, pkg/cluster/host.go, test/test_volume.go
Add volume snapshots and (inter-host!) transmission to the host API.
=> Volume transmit api

controller/testutils/fake_host_client.go, host/cli/destroy-volumes.go, host/volume/api/http.go, host/volume/zfs/integrations.go, host/volume/zfs/zfs.go, pkg/cluster/host.go, test/test_host.go, test/test_volume.go
Add volume destroy to API, add retries to zfs destroy commands to improve stability, handle zfs child filesystems correctly in the host cli destroy-volumes command.
=> Volume destroy

controller/jobs.go, controller/jobs_test.go, controller/schema.go
Since multiple schedulers watch for events, job state updates can get intermingled and erroneously leave the job in an incorrect state, so this change ensures that a job never returns to a previous state.
=> controller: Add job state constraint

README.md
=> README: Remove mention of hosted dashboard

README.md, demo/README.md, docs/content/installation.html.md
I missed these in the previous PR. I’ll also set up a 301 shortly.
=> all: Fix links to using Flynn

docs/content/installation.html.md
=> docs: Add note about installing on Linode

cli/app.go, cli/git.go, test/test_cli.go
=> cli: Fix create command when not in a git repo

dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/stores/app.js
=> dashboard: Use deployer when creating new app releases

dashboard/app/lib/javascripts/dashboard/actions/app-route-delete.js, dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/routers/apps.js, dashboard/app/lib/javascripts/dashboard/stores/app-routes.js, dashboard/app/lib/javascripts/dashboard/views/app-route-delete.js.jsx, dashboard/app/lib/javascripts/dashboard/views/app-routes.js.jsx
refs 4ebafaa3078786fb6561b5ca61a541ca57e0442f
fixes #1079
=> dashboard: Fix create route JSON structure, Fix delete route

discoverd/health/monitor.go, host/containerinit/init.go, test/test_deployer.go
The fix here is in 4d6cdad, but I've added the logging commit 300315f as I think it will be useful in the future.
I am not entirely sure this fixes the issue, but it definitely improves the logic. I ran it countless times without error.
Fixes #1060.
=> Fix DeployerSuite.TestServiceEvents

test/rootfs/setup.sh
This is useful for testing cluster updates.
=> test: Install tuf-client

test/cluster/cluster.go, test/main.go, test/runner/runner.go
This is extracted from #1105 so that the tests will run.
=> test: Support booting multiple clusters

cli/install.go, installer/installer.go
After we install a cluster, it makes sense to configure the CLI to talk to it. Before this we just printed the config command, but this is unnecessary work for the user.
/cc @jvatic
=> cli: Add installed cluster as default

cli/install.go, docs/content/installation.html.md
=> AWS CLI install docs

cli/install.go, installer/installer.go, installer/stack_template.go
=> cli: Allow all but micro instance types in installer

host/manifest_template.json
Fix indentation and duplicate args field.
=> host: Remove extra field in manifest template

Godeps/Godeps.json, Godeps/_workspace/src/github.com/thoj/go-ircevent/LICENSE, Godeps/_workspace/src/github.com/thoj/go-ircevent/README.markdown, Godeps/_workspace/src/github.com/thoj/go-ircevent/irc.go, Godeps/_workspace/src/github.com/thoj/go-ircevent/irc_callback.go, Godeps/_workspace/src/github.com/thoj/go-ircevent/irc_struct.go, Godeps/_workspace/src/github.com/thoj/go-ircevent/irc_test.go, test/runner/runner.go, test/runner/types.go
Half of #305 (the other half is email notifications).
=> test: Send IRC notifications

util/cedarish/Dockerfile
Added the FreeTDS library, which is used for connecting to SQL Server.
=> Added the FreeTDS library to the default cedarish image.

bootstrap/manifest_template.json, logaggregator/Dockerfile, logaggregator/Tupfile, logaggregator/main.go, updater/types/types.go, util/release/version_template.json
Add logaggregator as a layer1 service.
=> logaggregator: bootstrap

docs/content/postgres.html.md
Describes how to provision and connect to databases as well as the high-level design of the appliance.
=> docs: Document postgres appliance

cli/resource.go, test/test_cli.go
With corresponding provider names. Fixes #1136
=> CLI support for listing out current app resources

cli/install.go, installer/installer.go, installer/stack_template.go
=> Support for non-default regions and CIDRs in flynn aws install (#1164)

host/cli/download.go
Calling `tuf.FileLocalStore` creates the local TUF db, so if a method after that fails then just checking for its's existence isn't enough to determine whether it needs initializing.
Instead we should check for `ErrNoRootKeys` from the TUF client to determine whether it needs initializing.
This was causing installations to fail in #1143 after an initial failure due to a network timeout fetching the remote root.json.
=> host: Fix initializing the TUF client

host/containerinit/init.go
This is to help debug jobs which remain in the starting state in CI, even though they are running and have output in their logs.
Relates to #907.
=> host/containerinit: Log state changes

controller/deployer/main.go, controller/deployer/strategies/all-at-once.go, test/test_deployer.go
See commit messages for more information.
Fixes #1185.
=> Deployer fixes

discoverd/Dockerfile, discoverd/start.sh, host/containerinit/init.go, host/state.go, host/upstart.conf, script/install-flynn.tmpl
This fixes two bugs found while doing manual QA on restarts, see the commit messages for details.
Refs #235
=> Fix a couple of resurrection bugs

gitreceived/gitreceived.go, receiver/Dockerfile, receiver/Tupfile, receiver/cache-key/main.go, receiver/start.sh, test/test_git_deploy.go
=> Cache gitreceived based on app ID.

dashboard/api.go
Ping handler is accessable from any localhost address so the installer
may verify the certificate works.
Supporting form encoded request to login allows the installer to submit
a form pointing at the dashboard login endpoint (cookie will not be set
for the dashboard interface if request made via JavaScript).
=> dashboard: Add ping handler, allow form encoded request to login

Godeps/Godeps.json, Godeps/_workspace/src/github.com/cheggaaa/pb/LICENSE, Godeps/_workspace/src/github.com/cheggaaa/pb/README.md, Godeps/_workspace/src/github.com/cheggaaa/pb/example/copy/copy.go, Godeps/_workspace/src/github.com/cheggaaa/pb/example/pb.go, Godeps/_workspace/src/github.com/cheggaaa/pb/format.go, Godeps/_workspace/src/github.com/cheggaaa/pb/format_test.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_nix.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_solaris.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_test.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_win.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_x.go, Godeps/_workspace/src/github.com/cheggaaa/pb/reader.go, cli/pg.go, cli/run.go, controller/jobs.go, controller/types/types.go, docs/content/postgres.html.md, host/libvirt_lxc_backend.go, host/types/types.go, schema/controller/new_job.json, test/test_postgres.go
`flynn pg dump` dumps the app's postgres database to stdout or a file.
`flynn pg restore` restores a database dump to the app's postgres database.
=> Implement CLI pg dump/restore commands

host/host.go
=> Improve printing flynn-host version

blobstore/postgres_filesystem.go, controller/app.go, controller/artifact.go, controller/deployment.go, controller/formation.go, controller/jobs.go, controller/key.go, pkg/postgres/postgres.go
=> controller: Descriptive error on duplicate app.

host/containerinit/init.go
This is a temporary hard-coded measure until we have a good system for tuning options like this.
Also dropped the max number of processes to 256 to match Heroku, as a sanity measure.
Closes #1205
=> host/containerinit: Bump max open files to 10k

test/cluster/cluster.go, test/test_release.go, test/test_scheduler.go
The extra logging in `TestReleaseImages` is for #1123, see commit messages for more comments.
=> Test tweaks

test/cluster/cluster.go
`Cluster.Boot` calls `DumpLogs` if bootstrapping fails, so the booted instances need to be added to `Cluster.defaultInstances` as soon as possible so that they are available for grabbing logs (and so that `DumpLogs` does not panic accessing `Cluster.defaultInstances[0]`)
=> test: Fix tracking VMs

dashboard/app/lib/javascripts/dashboard/stores/app-jobs.js, dashboard/app/lib/javascripts/dashboard/stores/job-output.js, dashboard/app/lib/javascripts/dashboard/stores/jobs-stream.js, dashboard/app/lib/javascripts/dashboard/stores/taffy-jobs.js, dashboard/app/lib/javascripts/dashboard/views/app-deploy-commit.js.jsx, dashboard/app/lib/javascripts/dashboard/views/app-logs.js.jsx, dashboard/app/lib/javascripts/dashboard/views/command-output.js.jsx, dashboard/app/lib/javascripts/dashboard/views/github-deploy.js.jsx, dashboard/app/lib/javascripts/dashboard/views/job-output.js.jsx
=> dashboard: Update to work with new log API

Vagrantfile, test/rootfs/setup.sh
I am making this pull request before adding tests so that `bats` is available in CI.
=> all: Add Bats for script unit testing

host/cli/collect-debug-info.go, host/cli/inspect.go
There are many pieces of sensitive information that we shouldn’t collect that are in the environment. Also added a flag to `flynn-host inspect` to omit the environment.
Closes #954
=> host: Don’t include env vars in debug info by default

host/cli/collect-debug-info.go
=> host/cli: Collect iptables rules as part of debug info

dashboard/app/lib/javascripts/dashboard/views/app-deploy-commit.js.jsx, dashboard/app/lib/javascripts/dashboard/views/command-output.js.jsx, dashboard/app/lib/javascripts/dashboard/views/github-deploy.js.jsx
=> dashboard: Don't show timestamps in deploy output

installer/app/src/main-store.js
=> installer: Fix entering AWS creds via UI

installer/app/src/main-store.js
Fields for instance type and num instances were camelCased instead of snake_cased.
fixes #1297
=> installer: Fix input data

cli/config/config.go, cli/main.go, installer/installer.go
refs 67e39ebebccc5dbb550ae694b4027dc249b779d7
fixes #1303
=> installer: Configure CLI

script/release-vm-images, test/rootfs/build.sh, test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/upgrade.sh
14.04.2 includes the backported Utopic 3.16 kernel.
=> Bump Ubuntu

test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/upgrade.sh
For two completely different reasons we actually need to keep these lines that I removed in #1315.
=> Upgrade kernel (again)

script/release-flynn
=> script: Fail if tagging a release fails

installer/installer.go, pkg/awsutil/awsutil.go
=> Installer key fingerprint

script/install-flynn.tmpl
=> script: Ensure /etc/apt/sources.list.d exists

installer/app/src/client.js, installer/app/src/main-store.js, installer/app/src/router.js, installer/app/src/views/wizard.js.jsx, installer/http.go
=> installer: handle failure

test/cluster/cluster.go, test/runner/runner.go
This removes the need to add entries to `/etc/hosts`.
=> test: Use xip.io domains

logaggregator/api.go
Move response flushing & writing into the same goroutine.
=> logaggregator: fix race in flush loop

installer/app/src/views/aws-region-picker.js.jsx
=> installer: Remove eu-central-1 from region select

installer/app/src/application.css, installer/app/src/views/integer-picker.js.jsx, installer/app/src/views/pretty-select.js.jsx
=> installer: Fix UI glitches (windows)

Godeps/Godeps.json, Godeps/_workspace/src/github.com/badgerodon/ioutil/multi.go
See https://github.com/badgerodon/ioutil/pull/1
=> Godeps: Bump badgerodon/ioutil

.gitignore, demo/Makefile, demo/README.md, demo/Vagrantfile, docs/content/installation.html.md
Signed-off-by: Joe Johnston <joe@simple10.com>
This will hopefully make it a lot easier for people to get quickly up and running with flynn.
It also fixes https://github.com/flynn/flynn/issues/975
=> demo: Add Makefile to simplify steps and self document

slugbuilder/builder/buildpacks.txt
https://github.com/heroku/heroku-buildpack-go/compare/daef77e9...98f37cce
=> slugbuilder: Use Heroku-maintained Go buildpack

cli/cluster.go, test/test_cli.go
=> Select next available cluster when default is removed

host/cli/run.go
This allows for arbitrary diagnostics/maintenance and is useful to extract data from clusters under some circumstances.
=> host/cli: Add support for bind mounting in `flynn-host run`

script/install-flynn.tmpl
=> script: Add --remove flag to install script

dashboard/app/lib/javascripts/dashboard/stores/app.js, dashboard/app/lib/javascripts/dashboard/views/app-env.js.jsx, dashboard/app/lib/javascripts/dashboard/views/github-auth.js.jsx
=> dashboard: Updating env always uses latest release

test/rootfs/setup.sh
See https://github.com/docker/docker/pull/11945.
(Hopefully) closes #1300.
=> test: Patch Docker upstart config

installer/stack_template.go
=> installer: Fix DNS and health check

controller/scheduler/main.go
This prevents jobs which are not running still appearing as up in the controller if the scheduler missed the event (e.g. because flynn-host was restarted).
Closes #1406.
=> controller/scheduler: Sync job states at startup

host/libvirt_lxc_backend.go
This parses and copies any search paths from the host `resolv.conf` into the container `resolv.conf`, allowing local domains to be resolved automatically.
Closes #1414
=> host: Copy search path from host resolv.conf

LICENSE, README.md, cli/LICENSE, docs/content/trademark-guidelines.html.md
=> Trademark updates

cli/git.go
Replaced by `multipleRemotesError`.
=> cli: Remove unused errMultipleFlynnRemotes

appliance/etcd/build.sh, appliance/etcd/start.sh
Minor bugfixes.
https://github.com/coreos/etcd/compare/v2.0.5...v2.0.9
=> appliance/etcd: Bump to etcd v2.0.9

.gitignore, util/_toolchain/.gitignore
=> Fixed .gitignore to ignore the util/_toolchain directory

host/libvirt_lxc_backend.go
Fixes #1451.
I tried to run strace on the libvirt daemon to see why it is restarting, but then I could not reproduce the error, I guess Heisenberg's uncertainty principle applies :trollface:.
Given we will be moving away from libvirt soon, I have opted to just keep retrying the domain creation for upto 10 seconds, which should hide the fact that it is temporarily unavailable for some unknown reason.
=> host: Attempt libvirt commands multiple times

controller/app.go, controller/controller_test.go
Follow up to #1467
Unit tests now require the uuid package. Not sure if I need to update godeps for that.
ping @lmars
=> controller: Fixed removal of apps with uuids as names

cli/scale.go, controller/client/client.go, controller/deployer/strategies/main.go, controller/deployment.go, pkg/httpclient/json.go, pkg/httpclient/stream.go, test/test_cli.go, test/test_deployer.go, test/test_healthcheck.go, test/test_postgres.go, test/test_scheduler.go
=> controller: Auto resume job and deployment event streams

appliance/etcd/build.sh
https://github.com/coreos/etcd/releases/tag/v2.0.10
=> appliance/etcd: Update etcd to v2.0.10

test/cluster/cluster.go, test/cluster/instance.go
Building Flynn blocked a CI job. The VM was pegging the CPU and I couldn't get an SSH shell so unsure of the cause.
=> test: Timeout building Flynn after 30 minutes

discoverd/client/heartbeat.go
=> discoverd: Decrease heartbeat interval on error

dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/config.js, dashboard/app/lib/javascripts/dashboard/main.js
**WORK IN PROGRESS**
Closes #1411
ping @jvatic
=> dashboard: Should detect SSL problems with CORS

dashboard/app/lib/javascripts/dashboard/views/edit-env.js.jsx
=> dashboard: Allow empty env vars

host/host.go
This is to avoid the zpool consuming more space than is available on the root device, leading to `ENOSPC` errors and thus breaking many things.
Tested on Ubuntu 14.04 in VirtualBox, EC2 and DO. For example on EC2:
```
$ df -h
Filesystem                                      Size  Used Avail Use% Mounted on
/dev/xvda1                                       50G   12G   36G  26% /
...
flynn-default/bd884404eec54c5e98b0aa21092a70ca   34G  640K   34G   1% /var/lib/flynn/volumes/zfs/mnt/bd884404eec54c5e98b0aa21092a70ca
flynn-default/38099f2b423d4b8796a96b4958a5251c   34G   60M   34G   1% /var/lib/flynn/volumes/zfs/mnt/38099f2b423d4b8796a96b4958a5251c
flynn-default/7d2b3431467046f2bbc9e57f0b4c0523   34G     0   34G   0% /var/lib/flynn/volumes/zfs/mnt/7d2b3431467046f2bbc9e57f0b4c0523
$ sudo zpool …
```
=> host: Set the zpool backing file size to 70% of root device

installer/app/src/views/main.js.jsx, installer/app/src/views/modal/credentials.js.jsx, installer/app/src/views/wizard.js.jsx, installer/http.go, installer/installer.go
=> Installer credentials UX

installer/app/src/views/external-link.js.jsx, installer/app/src/views/modal/credentials.js.jsx
=> installer: Add links for creating credentials

cli/scale.go, controller/client/client.go, receiver/flynn-receive.go, test/test_cli.go, test/test_controller.go, test/test_deployer.go, test/test_git_deploy.go, test/test_healthcheck.go, test/test_scheduler.go
=> Receiver now waits for default formation scale before returning

appliance/etcd/build.sh, discoverd/testutil/etcdrunner/etcd.go
https://github.com/coreos/etcd/compare/v2.0.10...v2.0.11
=> appliance/etcd: Update etcd to v2.0.11

cli/README.md, docs/content/installation.html.md
=> cli: Error if curl download of binary fails

docs/content/installation.html.md
=> docs: Clarify that a firewall is required for security

dashboard/app/lib/javascripts/dashboard/client.js
Use new app events stream introduced in bf1142eff550ff9efbf81260d700bc2e28d1a6ff
#1577, #1579
=> dashboard: Fix waiting for deployment

dashboard/app/lib/javascripts/dashboard/stores/jobs-stream.js
Use new app events stream introduced in bf1142eff550ff9efbf81260d700bc2e28d1a6ff
#1578
=> dashboard: Fix job events stream

demo/Makefile
Include login token in url for automatic login
=> demo: Update make file command for opening dashboard

util/cedarish/Dockerfile
This is to match upstream: https://github.com/heroku/stack-images/commit/f8717d59474da621c670c0156a9ea7cd59e1f2c7
=> util/cedarish: Add stunnel

test/test_postgres.go
The postgres appliance [drains the service discovery channel before applying config](https://github.com/flynn/flynn/blob/master/appliance/postgresql/state/state.go#L255) to ensure it is always acting on current data, which means that some expected states may not happen (e.g. if a new async is started and another goes down, the state is not guaranteed to transition via a state with both asyncs present).
The tests have been updated to check that received states are expected and in-order, but some expected states can be skipped.
=> test: Handle postgres states being skipped

discoverd/client/client.go, host/discoverd.go, host/http.go
=> Host refactor fixes

controller/scheduler/main.go, slugbuilder/builder/build.sh, test/test_cli.go, test/test_postgres.go
See commit messages / code comments for a description of the changes.
=> Intermittent test fixes

discoverd/client/client.go, discoverd/client/watch.go, discoverd/client/watch_test.go
=> discoverd: Reconnect event watches on error

docs/content/installation.html.md
Discovery token handling has changed a bit.
Closes #1610
=> docs: Update for host refactor

installer/installer.go
=> installer: Fix saving azure credentials

gitreceived/gitreceived.go
This is the same fix I made for sshfront.
=> Use ssh.Unmarshal to read request payload.

test/runner/runner.go
I've added versions to builds to determine whether they are compatible with the scrolling log viewer.
I plan to manually migrate the CI database so that all builds before `20150626200913-1e351d94` are v1, and all after are v2.
=> test: Redirect old build logs to S3

host/host.go, host/libvirt_lxc_backend.go
It has been fully replaced by the new volume system.
Closes #1168
=> host: Remove legacy volume support

installer/app/src/router.js
=> installer: Fix building Azure authorize URL

bootstrap/discovery/discovery.go, cli/export.go, host/cli/collect-debug-info.go, host/discoverd.go, host/host.go, pkg/httphelper/request_logger.go, pkg/shutdown/handler.go, router/server.go, script/kill-flynn, script/run-integration-tests
A collection of small fixes I have made whilst working on flynn-host zero-downtime updates.
=> Various fixes

host/libvirt_lxc_backend.go
Including the host ID in the container hostname can result in the name being longer than 64 characters, which is the maximum length that `sethostname(2)` will take.
Refs #1669
=> host: Remove host ID from container hostnames

appliance/postgresql/simulator/simulator.go, controller/events.go, discoverd/server/state.go, pkg/pinned/pinned_test.go, router/discoverd_cache.go
Fix races and other concurrency bugs found while updating to Go 1.5.
=> Concurrency fixes

controller/scheduler-v2/formation.go, controller/scheduler-v2/job.go, controller/scheduler-v2/scheduler.go, controller/scheduler-v2/scheduler_test.go, controller/testutils/fake_controller_client.go, controller/testutils/fake_host_client.go, controller/utils/utils.go
TODO: still need to refactor tests to handle new formations.
=> scheduler-v2: Formation Sync updates

discoverd/daemon.go, host/backend.go, host/host.go, host/http.go, host/libvirt_lxc_backend.go, host/state_test.go, host/types/types.go, router/data_store.go
See commit messages.
Closes #1679.
=> Shutdown fixes

test/test_cli.go
=> test: Fix leaked goroutines

test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/install.sh
https://blog.docker.com/2015/07/new-apt-and-yum-repos/
=> all: Use new Docker apt repo

bootstrap/manifest_template.json
=> bootstrap: Separate login token from dashboard URL

controller/controller.go
If we don’t do this, a bootstrap may be slower than the timeout for the subsequent stream request, causing the controller to crash and the bootstrap to fail.
Reported by @temujin9 in IRC.
=> controller: Wait indefinitely for router to come up before streaming events

demo/Vagrantfile
Small quality of life improvement for VMware Fusion users.
=> demo: Also set memory and vcpus for vmware_fusion provider

host/libvirt_lxc_backend.go
Previously, attaching to a job which had exited and had `DisableLog` set would immediately close the request rather than sending an Attach protocol message.
This change means `AttachSuccess` is sent, followed by `io.EOF` to indicate there is no output.
=> host: Fix attaching to exited jobs with no logs

Godeps/Godeps.json, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/matrix.go
See https://github.com/jvatic/asset-matrix-go/pull/4
\cc @titanous
=> Godep: Update asset-matrix-go

Godeps/Godeps.json, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/matrix.go
Fixes output dependency ordering and npm dependency checking bugs introduced in previous PR (#1745)
\\cc @titanous
=> Godeps: Update asset-matrix-go

test/rootfs/setup.sh
This is the version we install in the appliance.
=> test: Use PostgreSQL 9.4

dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/stores/jobs-stream.js
#1771
Refs c979944e40224b5bec4c0f451ed0caceb4daece7
=> dashboard: Fix: /events replaces /apps/:id/events

controller/provider.go
=> controller: Fix typo controler -> controller

util/cedarish/Dockerfile
For upstream parity: https://github.com/heroku/stack-images/commit/ac4f62dd1b3417f1c035e1e634cc7f97ed65dcbe
=> util/cedarish: Add postgres client libraries

cli/resource.go, controller/client/client.go, controller/events_test.go, controller/examples/examples.go, controller/resource.go, controller/worker/app_deletion/app_deletion.go, test/test_cli.go
Allow removal of resources via CLI
Closes #1413
=> cli: Implement resource removal

cli/provider.go, test/test_cli.go
This is a stepping stone to full custom provider management.
=> cli: Add providers via CLI

Godeps/Godeps.json, Godeps/_workspace/src/github.com/flynn/que-go/que.go, controller/worker/deployment/postgres.go
=> Postgres deployment fixes

controller/scheduler/main.go, pkg/cluster/client.go, pkg/cluster/host.go, test/cluster/client/client.go, test/helper.go
=> Various scheduler fixes

Godeps/Godeps.json, Godeps/_workspace/src/github.com/BurntSushi/toml/README.md, Godeps/_workspace/src/github.com/BurntSushi/toml/encode.go, Godeps/_workspace/src/github.com/BurntSushi/toml/encode_test.go, Godeps/_workspace/src/github.com/BurntSushi/toml/type_fields.go, cli/cluster.go, cli/config/config.go, cli/git.go, cli/key.go, cli/main.go, test/test_cli.go
This allows specifying a custom controller and git URLs, and simplifies things.
Ping @temujin9
=> cli: Custom git and controller urls

test/test_deployer.go
=> test: Wait 5s to ensure services are up

host/cli/collect-debug-info.go, host/cli/log.go
This implements tailing job logs to a set number of lines.
It is available for both collect-debug-info and log commands with the --lines argument.
Logs are collected into a fixed size ring buffer as they are streamed from remote hosts, this avoids memory usage issues encountered previously by buffering the entire log. 
Closes #1716
Closes #1063
=> cli: Implement tailing of job logs to number of lines

discoverd/server/state.go
This will make it easier to debug issues around potentially not receiving service events in the client.
Example:
```
2015/09/01 14:27:20 discoverd listening for HTTP on :1111
t=2015-09-01T14:27:20+0000 lvl=info msg="broadcasting up event" component=discoverd fn=broadcast service=discoverd instance.id=bac41f57798d1ce9219b9b1d2f67a7d8 instance.addr=172.31.8.74:1111
t=2015-09-01T14:27:20+0000 lvl=info msg="broadcasting leader event" component=discoverd fn=broadcast service=discoverd instance.id=bac41f57798d1ce9219b9b1d2f67a7d8 instance.addr=172.31.8.74:1111
t=2015-09-01T14:27:20+0000 lvl=info msg="broadcasting service_meta event" component=discoverd fn=broadcast service=flannel service_meta.index=6
t=2015-09-01T14:27:20+0000 lvl=info msg="broadcasting service_meta event" component=discoverd …
```
=> discoverd: Log broadcast events

controller/app.go, controller/artifact.go, controller/controller.go, controller/deployment.go, controller/events.go, controller/formation.go, controller/jobs.go, controller/jobs_test.go, controller/provider.go, controller/release.go, controller/resource.go, controller/routes_test.go, pkg/postgres/postgres.go, pkg/random/random.go, router/http_test.go, test/test_cli.go
=> Standardise on hyphenated UUIDS

cli/app.go, cli/common.go, cli/main.go, cli/remote.go, test/test_cli.go
CLI for managing git remotes for flynn applications
Closes #1762
=> cli: flynn remote add

cli/deployment.go, cli/main.go, cli/release.go, controller/client/client.go, controller/controller.go, controller/deployment.go, controller/deployment_test.go, controller/schema.go, controller/types/types.go, schema/controller/deployment.json, test/test_cli.go, test/test_deployer.go
List deployments along with their status, start and finish times.
Closes #1176
=> cli: List deployments

gitreceive/server.go, pkg/archiver/archiver.go, test/test_git_deploy.go
Directories were not being saved in the repo cache tar file correctly, which caused git to not see a valid repository. Also, did a bit of refactoring to surface errors from the tar upload correctly.
Closes #1799
=> Fix gitreceive tar

controller/jobs.go, controller/jobs_test.go, controller/scheduler-v2/formation.go, controller/scheduler-v2/formation_test.go, controller/scheduler-v2/job.go, controller/scheduler-v2/scheduler.go, controller/scheduler-v2/scheduler_test.go, controller/testutils/fake_cluster.go, controller/testutils/fake_controller_client.go, controller/testutils/fake_host_client.go, controller/types/types.go, controller/utils/utils.go, host/state.go, host/types/types.go
Also implemented goroutine for handling PutJob queue.
=> Scheduler v2: Implemented host, job event, and formation streaming.

Godeps/Godeps.json, Godeps/_workspace/src/github.com/jackc/pgx/CHANGELOG.md, Godeps/_workspace/src/github.com/jackc/pgx/README.md, Godeps/_workspace/src/github.com/jackc/pgx/conn.go, Godeps/_workspace/src/github.com/jackc/pgx/conn_pool.go, Godeps/_workspace/src/github.com/jackc/pgx/conn_pool_test.go, Godeps/_workspace/src/github.com/jackc/pgx/conn_test.go, Godeps/_workspace/src/github.com/jackc/pgx/doc.go, Godeps/_workspace/src/github.com/jackc/pgx/example_json_test.go, Godeps/_workspace/src/github.com/jackc/pgx/fastpath.go, Godeps/_workspace/src/github.com/jackc/pgx/helper_test.go, Godeps/_workspace/src/github.com/jackc/pgx/messages.go, Godeps/_workspace/src/github.com/jackc/pgx/query.go, Godeps/_workspace/src/github.com/jackc/pgx/query_test.go, Godeps/_workspace/src/github.com/jackc/pgx/stdlib/sql.go, Godeps/_workspace/src/github.com/jackc/pgx/values.go, Godeps/_workspace/src/github.com/jackc/pgx/values_test.go
Upgrade pgx to bring in native JSON/JSONB support.
=> all: Update pgx

util/packer/ubuntu-14.04/scripts/install.sh
=> Added vagrant user to libvirtd group so it has permissions to kill discoverd

test/cluster/client/client.go, test/cluster/cluster.go, test/helper.go
This makes the error more visible, and means the same discoverd client is being used to for both adding and removing hosts.
=> test: Move host removal wait into test/helper.go

cli/cluster.go, cli/config/git.go, cli/git.go, installer/cluster.go
=> installer: Configure local git

test/test_scheduler.go
=> test: Skip SchedulerSuite.TestOmniJobs

test/runner/assets/builds.js, test/runner/assets/index.html, test/runner/runner.go
This turns the "failure" label in CI into a button which once clicked shows a list of the failures from the build.
=> test: Expose list of failures in CI

test/runner/runner.go
=> test: Added failure count to IRC failure notice

test/runner/runner.go
=> test: Added failure count to GitHub CI hook failure notice

controller/scheduler-v2/scheduler.go
=> scheduler: Implemented PR fixes

dashboard/app/lib/javascripts/dashboard/main.js
This fixes cases where a blank page is rendered instead of the login view.
#1696
=> dashboard: Fix issue causing blank page instead of login view

discoverd/server/handler.go, test/test_scheduler.go
=> test: Fix SchedulerSuite.TestOmniJobs

dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/main.js
Fixes issue where event stream would try to connected before app is authenticated and didn't retry after authenticating.
#1881
=> dashboard: Ensure event stream is connected

dashboard/app/lib/javascripts/dashboard/main.js
=> dashboard: Fix install cert flow with security exception

dashboard/app/lib/javascripts/dashboard/actions/deploy.js
=> dashboard: Copy env from previous release when deploying commit

script/run-integration-tests, test/test_scheduler.go
=> script: Fix setting BACKOFF_PERIOD in run-integration-tests

controller/app.go, controller/client/client.go, controller/events.go, controller/events_test.go, controller/formation.go, controller/types/types.go, dashboard/app/compiler.go, dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/stores/app-deploy.js, dashboard/app/lib/javascripts/dashboard/stores/app-history.js, dashboard/app/lib/javascripts/dashboard/stores/app.js, dashboard/app/lib/javascripts/dashboard/views/app-history.js.jsx, dashboard/app/lib/javascripts/dashboard/views/app-source-history.js.jsx, dashboard/app/lib/javascripts/dashboard/views/app.js.jsx, dashboard/app/lib/javascripts/dashboard/waitgroup.js, dashboard/app/lib/stylesheets/dashboard/app-history.scss, dashboard/app/lib/stylesheets/dashboard/application.scss, dashboard/app/vendor/javascripts/ScrollPagination.js
The next step is adding a revert button to each item.
=> dashboard: List app history (release and scale)

schema/controller/app.json
=> schema: Fix app JSON

dashboard/app/lib/javascripts/dashboard/stores/app.js
=> dashboard: Fix scale app

controller/scheduler/formation.go, controller/scheduler/scheduler.go
=> PR feedback for final master review

controller/scheduler/scheduler.go
=> scheduler: Added issue numbers to TODO comments

cli/config/config.go, test/test_cli.go
Instead return an error, as handling this situation is complicated.
Closes #1924
=> cli: Fix panic when force-adding cluster that conflicts with multiple clusters

host/containerinit/init.go, host/libvirt_lxc_backend.go
This is to help debug https://github.com/flynn/flynn/issues/907
=> host: Update containerinit stream logging

script/install-flynn.tmpl
=> install-script: Load ZFS module after installing it

dashboard/app/compiler.go, installer/app/compiler.go
ESLint appears to be using too much memory
=> installer,dashboard: Disable ESLint in build

script/lib/release.sh, script/release-flynn, script/test/release.bats
=> script: Use tags to determine release and tag before releasing

cli/scale.go, test/test_cli.go
=> cli,test: Add --all option to scale command

bootstrap/bootstrap.go, host/cli/bootstrap.go
=> host/cli: Add timeout option for bootstrap

dashboard/app/lib/javascripts/dashboard/stores/app.js
=> dashboard: Show all app processes

test/cluster/cluster.go
=> test/cluster: Add dashboard domain to local DNS

host/cli/list.go, host/host.go
=> host: Add cli command for listing hosts

bootstrap/run_app_action.go
=> bootstrap: Allow 30 seconds for jobs to come up

discoverd/server/store.go, discoverd/server/store_test.go
This commit adds the ability for the discoverd store to periodically check for instance expiration and then execute a consistent expiry command through the raft consensus.
Fixes #1984
=> discoverd: add instance expiration

docs/lib/flynn-docs.rb
=> docs: Add FlynnDocs.images_dir

discoverd/server/store.go
=> discoverd: remove error when no instances need expiration

bootstrap/add_route_action.go, bootstrap/gen_tls_cert_action.go, cli/route.go, controller/client/client.go, controller/controller.go, controller/routes.go, controller/routes_test.go, pkg/tlscert/tlscert.go, router/api.go, router/api_test.go, router/tcp.go, test/test_cli.go
=> controller,cli: Update route

controller/controller.go, controller/deployment_test.go, controller/resource.go, controller/schema/queries.go, controller/worker/app_deletion/app_deletion.go, controller/worker/deployment/context.go, controller/worker/main.go
Just a bit of renaming, formatting and preparing some left over queries.
=> controller: Misc prepared query cleanups

pkg/httphelper/httphelper.go
This change is intended to increase robustness where requests
rely on other services that may be temporarily unavailable.
Closes #1977
=> pkg/httphelper: Retry on net.OpError or syscall.Errno

bootstrap/manifest_template.json, discoverd/main.go, discoverd/server/store.go
This PR is pulling out some of the work @lmars has done to support updating discoverd so that PR can be more focused on the actual deployment/update process when it's opened.
=> Discoverd improvements

cli/update.go, host/backend.go, host/cli/destroy-volumes.go, host/cli/download.go, host/cli/update.go, host/containerinit/init.go, host/discoverd.go, host/downloader/downloader.go, host/host.go, host/http.go, host/libvirt_lxc_backend.go, host/state.go, host/state_test.go, host/types/types.go, host/update.go, host/volume/manager/manager.go, host/volume/manager/persistence_test.go, pkg/cluster/host.go, pkg/exec/exec.go, pkg/tufutil/tufutil.go, script/export-components, script/install-flynn.tmpl, script/run-integration-tests, test/apps/Dockerfile, test/apps/Tupfile, test/apps/partial-logger/main.go, test/arg/arg.go, test/runner/runner.go, test/test_host.go, test/test_host_update.go
Opening for early feedback on the approach.
All but the last 3 commits are in #1671 so will disappear once that is merged.
=> host: Support zero-downtime updates

router/api.go, router/server.go
=> router: Replace martini with httprouter

bootstrap/deploy_app_action.go, bootstrap/manifest_template.json, discoverd/server/handler.go, discoverd/server/store.go
=> discoverd debug logging

dashboard/api.go, dashboard/api_test.go
=> dashboard: Add back support for form-urlencoded login request

discoverd/server/store.go
=> discoverd/server: Don't log during expiry when not leader

host/update.go
Also don't return error from closing our side of the socket pair, as it is non-critical to the operation of the update.
Closes #2014
=> host: Add better logging to child exec

cli/main.go
=> cli: Attempt to get cluster details from git before using default

controller/scheduler/scheduler.go
=> scheduler: Retry SyncJobs with a small delay if it fails

cli/export.go
Allows optional importing of routes.
Closes #1956
=> cli: Route export/import

test/runner/assets/index.html, test/runner/runner.go, test/runner/types.go
Makes it slightly easier to identify which builds are for a particular PR.
=> test: Add branch to CI index

controller/scheduler/host.go, controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go, controller/testutils/fake_host_client.go, controller/utils/utils.go
Closes #1921.
Fixes part of #2004.
=> scheduler: Implement host sync and checking

cli/cluster.go, cli/main.go, controller/client/client.go, controller/controller.go, controller/domain.go, controller/schema.go, controller/schema/queries.go, controller/types/types.go, controller/worker/domain_migration/domain_migration.go, controller/worker/main.go, pkg/tlscert/tlscert.go, test/test_domain_migration.go
=> Migrate cluster domain

installer/azure_cluster.go
=> installer: Save SSH key used in Azure install

test/test_domain_migration.go
This was previously panicking if the events channel closed.
I've also added some debug messages and refactored a little bit.
/cc @jvatic
=> test: Handle closed event stream in TestDomainMigration

host/logmux/logmux.go
=> host/logmux: Fix error handling in log reader

script/release-flynn
=> script: Check commit has passed CI before tagging

appliance/postgresql/main.go, appliance/postgresql/postgres.go, appliance/postgresql/simulator/simulator.go, appliance/postgresql/state/state.go, appliance/postgresql/state/state_test.go, host/cli/fix.go, host/host.go, host/libvirt_lxc_backend.go, script/bootstrap-flynn
Adds `flynn-host fix` which repairs a variety of common cluster ailments.
Closes #2046
Closes #1789
Closes #1988
Closes #1893
=> Cluster repair tool

bootstrap/bootstrap.go, host/cli/bootstrap.go
This ensures that a backup from a multi-node cluster restores correctly into a single node cluster.
=> Fix backup restore singleton flag

controller/utils/utils.go
Signed-off-by: Jorge Ferreira <imjorge@gmail.com>
=> controller: Inject Flynn app name to the apps ENV vars

cli/cluster.go
=> cli: support `flynn cluster add` when git is not present

cli/log.go, dashboard/app/lib/javascripts/dashboard/routers/apps.js, dashboard/app/lib/javascripts/dashboard/stores/job-output.js, dashboard/app/lib/javascripts/dashboard/views/app-logs.js.jsx, dashboard/app/lib/javascripts/dashboard/views/github-deploy.js.jsx, dashboard/app/lib/javascripts/dashboard/views/job-output.js.jsx
=> dashboard: Include backlog when viewing app logs

script/release-timestamp
=> script: Upload latest snapshot in release-timestamp

bootstrap/manifest_template.json, status/status.go
=> status: Require key for status endpoint from public IP

dashboard/api.go, dashboard/app/compiler.go, dashboard/app/lib/javascripts/dashboard/actions/deploy.js, dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/routers/github.js, dashboard/app/lib/javascripts/dashboard/stores/app-deploy.js, dashboard/app/lib/javascripts/dashboard/views/github-deploy.js.jsx, dashboard/config.go
=> dashboard: Deploy bug fixes

controller/events.go, controller/scheduler/scheduler.go, controller/worker/deployment/context.go, controller/worker/deployment/one_by_one.go, test/test_scheduler.go
=> deployer: Wait for job events before deleting formation during rollback

host/cli/collect-debug-info.go, test/cluster/cluster.go
The paths were changed in cb5a37e.
=> host,test: Fix log collection fallback

Godeps/Godeps.json, Godeps/_workspace/src/github.com/pkg/browser/README.md, Godeps/_workspace/src/github.com/pkg/browser/browser.go, Godeps/_workspace/src/github.com/pkg/browser/browser_linux.go
See https://github.com/pkg/browser/pull/3
Closes #2125
=> Godeps: Bump github.com/pkg/browser

discoverd/client/client.go, discoverd/client/client_test.go
=> discoverd: client keep headers on redirect

logaggregator/api.go, logaggregator/api_test.go
=> logaggregator: do not send backlog when requested lines are zero

cli/app.go, cli/main.go
=> cli: add app info command

installer/cluster.go
=> installer: Increase number of ssh connection attempts for bootstrap

controller/worker/domain_migration/domain_migration.go, test/test_domain_migration.go
=> controller: Fix dashboard URL env when migrating domain

test/runner/runner.go
=> test: include custom port on ci links

script/export-components
I always expect -h to return usage.
=> script: Update usage in export-components

controller/worker/deployment/job.go
Currently if you deploy a release that only contains processes that will use service events the job event stream will not be connected.
This breaks deployments of these releases because the deployer still expects to use job events to track the processes shutting down.
=> controller: Always connect job event stream during deployment

host/cli/bootstrap.go, host/cli/cli.go, host/host.go
=> host: remove bootstrap double prints

test/test_host_update.go
This avoids a race where the log is sent to the aggregator before we have started streaming it.
Fixes #2106.
=> test: Stream logs before signalling partial logger

router/setup_test.go
=> router: fix test build failure

bootstrap/manifest_template.json
=> bootstrap: Correct discoverd port in manifest template

controller/log_test.go
It results in a data race (see https://ci.flynn.io/builds/20151128100145-5210d2b0)
=> contorller: Don't call c.Assert in goroutine

controller/formation.go, controller/formation_test.go
=> controller: avoid panic when streaming formation updates

docs/content/installation.html.md
...CLI includes *a* local browser-based installer...
Signed-off-by: Steve Phillips <steve@tryingtobeawesome.com>
=> Fixed typo

controller/formation.go
The tests were hanging during `TestStreamDeployment`, and I noticed that pgx was blocking trying to acquire a connection. Looking at the code, we were creating transactions before reading from the database, and so I moved the transactions and it no longer hangs.
I don't know the specific reason this was an issue (I assume reading inside a transaction is an ok thing to do?).
=> controller: Fix hang in controller tests

Godeps/Godeps.json, Godeps/_workspace/src/github.com/flynn/go-tuf/LICENSE, Godeps/_workspace/src/github.com/flynn/go-tuf/client/local_store.go, Godeps/_workspace/src/github.com/flynn/go-tuf/signed/verifiers.go, Godeps/_workspace/src/github.com/flynn/go-tuf/signed/verify.go, Godeps/_workspace/src/github.com/flynn/go-tuf/util/util.go, host/cli/download.go
Fixes segfault due to misuse of boltdb values (#2211).
=> Fix TUF segfault

controller/utils/utils.go
=> controller: Copy app metadata to host jobs

installer/app/src/base-cluster.js, installer/app/src/main-store.js, installer/app/src/views/clusters.js.jsx, installer/app/src/views/main.js.jsx, installer/app/src/views/prompt.js.jsx, installer/app/src/views/wizard.js.jsx
This makes it possible to do other things (e.g. launch another cluster) before responding to the prompt.
=> installer: Move prompts out of modal

host/cli/bootstrap.go
=> bootstrap: fix panic comparing errors

dashboard/api.go
=> dashboard: Fix memory leak

installer/http.go
=> installer: Add redirect for /clusters -> /

installer/app/src/views/modal/credentials.js.jsx
=> installer: Close modal after adding credential

host/libvirt_lxc_backend.go
Verified this works by booting a cluster, seeing the `EINVAL` in sysdig, but observing that the job still started, see the host log:
```
now=2015-12-10T00:54:35+0000 at=read_config fn=run job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 backend=libvirt-lxc
now=2015-12-10T00:54:35+0000 backend=libvirt-lxc fn=run job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 at=checkout
time="2015-12-10T00:54:35Z" level="error" msg="Couldn't run auplink before unmount: exit status 22" 
now=2015-12-10T00:54:35+0000 backend=libvirt-lxc fn=run job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 at=mount
now=2015-12-10T00:54:35+0000 at=write_config fn=run job.id=host2-be56142e-491b-4030-bcfa-fc96accd6483 backend=libvirt-lxc
now=2015-12-10T00:54:35+0000 backend=libvirt-lxc fn=run …
```
=> host: Retry creating AUFS mounts

installer/app/src/base-cluster.js, installer/app/src/client.js, installer/app/src/main-store.js, installer/app/src/router.js, installer/app/src/views/cluster.js.jsx, installer/app/src/views/credentials-picker.js.jsx, installer/app/src/views/install-steps.js.jsx, installer/app/src/views/main.js.jsx, installer/app/src/views/modal/credentials.js.jsx, installer/app/src/views/prompt.js.jsx, installer/app/src/views/wizard.js.jsx, installer/app/vendor/font-awesome.scss, installer/aws_cluster.go, installer/azure_cluster.go, installer/cluster.go, installer/digital_ocean_cluster.go, installer/events.go, installer/http.go, installer/installer.go
=> installer: Prompt for credentials on auth failure

cli/route.go, controller/jobs.go, pkg/postgres/postgres.go, router/api.go, router/data_store.go, router/http.go, router/http_test.go, router/schema.go, router/setup_test.go, router/tree.go, router/tree_test.go, router/types/types.go, schema/router/route.json, test/test_cli.go
This change set adds path based routing to the router.
Closes #2069 
Closes #2102
=> Path based routing

controller/app.go, controller/controller.go, controller/controller_test.go, controller/types/types.go, schema/controller/app.json
=> controller: Update app endpoint now handles setting empty meta

controller/scheduler/formation.go, controller/scheduler/host.go, controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go, controller/testutils/fake_host_client.go
=> scheduler: Rectify omni job counts when a host goes down

installer/aws_cluster.go, installer/cluster.go
=> Fix installer bugs

dashboard/api.go, pkg/cors/cors.go, pkg/cors/cors_test.go
=> dashboard,pkg/cors: Fix CORS for dashboard ping endpoint

installer/app/src/views/dashboard.js.jsx, installer/http.go
=> installer: Fix cert filename when downloading in Safari

dashboard/app/lib/javascripts/dashboard/actions/app-env.js, dashboard/app/lib/javascripts/dashboard/stores/app.js, dashboard/app/lib/javascripts/dashboard/views/app-env.js.jsx
=> dashboard: Allow editing app env when no release

dashboard/app/lib/javascripts/dashboard/views/apps.js.jsx, dashboard/app/lib/stylesheets/dashboard/main.scss
=> dashboard: Fix app view UI from exceeding container bounds

dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/stores/app-route-new.js, dashboard/app/lib/javascripts/dashboard/stores/app.js, dashboard/app/lib/javascripts/dashboard/views/app-delete.js.jsx
=> Dashboard error handling improvements

router/http.go
This closes a small safety issue that can happen if a path based route is added, the sync connection is lost, that path route is then deleted and re-added (not updated) with a different backend service.
By checking the path backend matches we ensure when processing removals that we don't accidentally delete this new valid route from the routing table.
=> router: Only remove from routing tree if route matches

cli/config/git.go
=> cli: Fix git config on Windows

bootstrap/run_app_action.go, host/libvirt_lxc_backend.go
I keep looking at CI build failures and finding #907 to be the cause, so this is an attempt at a workaround.
=> host: Perform explicit check for running containers

controller/controller.go
=> controller: Stop the formation listener on shutdown

dashboard/app/lib/javascripts/dashboard/stores/app-deploy.js
=> dashboard: Fix deploy completion state transition

slugbuilder/builder/build.sh
This changes the behavior of the `.slugignore` file in `slugbuilder` to remove files from the build root before processing buildpacks rather than simply excluding them when archiving the slug.
It also attempts to implement line handling the same as Heroku, ignoring blank lines and allowing comments in the `.slugignore` file itself.
Closes #2359
=> slugbuilder: Make .slugignore Heroku compatible

controller/events.go
During shutdown, `c.eventListener.CloseWithError(ErrShutdown)` is called this causes the pg listener channel to be closed which will race to be handled and could result in another call to `CloseWithError` which causes another close of `e.doneCh`.
To avoid this we check if the listener is closed in `CloseWithError` and skip the close logic if it has already been closed.
=> controller: Avoid double close panic during shutdown

test/test_redis.go
The redis appliance is not always ready when the `resource add` command returns. Added a check that waits for the discoverd registration before continuing.
/cc @benbjohnson
=> test: Fix race in redis test

cli/release.go, test/test_cli.go
Signed-off-by: Nathaniel Eliot <nathaniel.eliot@bazaarvoice.com>
Fixes #1535
=> cli/release: adding 'release update' to allow tweaking existing releases

appliance/postgresql/api/server.go
By first disallowing new connections and then terminating existing connections we can delete databases were `DROP` would otherwise fail.
Closes #2376
=> appliance/postgres: Forcefully close connections when deleting database

cli/app.go
By scaling down the processes before proceeding with deleting resources etc we can ensure they are no longer being used by the application.
This won't fix the case of trying to remove an in-use resource without deleting the app while the application still has processes running. This will need to be addressed on a per-provider/resource basis.
Refs #2376
=> cli: Scale processes to 0 before deleting app

installer/cluster.go
=> installer: Increase bootstrap timeout to 4m from 2m

docs/docs-nav.json, docs/lib/flynn-docs.rb
=> docs: Move docs-nav.json from website repo

controller/scheduler/host.go, controller/scheduler/scheduler.go, host/discoverd.go, host/types/types.go, test/test_scheduler.go, test/test_z_domain_migration.go
These changes (hopefully) fix a bunch of errors I saw from looking at the past 20 or so CI failures.
Fixes #2182.
=> Test fixes

host/volume/zfs/zfs.go
This changeset implements volume mounting when restoring the volume state db.
Previously it was assumed that some external process will ensure volumes would be mounted before they would be used by `flynn-host`. This behaviour turns out to be somewhat fragile and also non-portable as only Ubuntu ships with the modified version mountall designed to automount ZFS volumes.
=> host: Mount volumes when restoring from statedb

bootstrap/bootstrap.go, host/cli/bootstrap.go
Fix a few bugs in bootstrap from backup.
=> Fix cluster restore

router/http.go, router/tcp.go
This fixes issues caused by sharing transport level options across routes.
Closes: #1425
Refs: #2395
=> router: Use proxy instance per route rather than per service

dashboard/api.go, dashboard/app/lib/javascripts/dashboard/github-client.js, dashboard/app/lib/javascripts/dashboard/main.js, dashboard/app/lib/javascripts/dashboard/views/github-auth.js.jsx, dashboard/config.go
#2447
No UI for now until it can be confirmed working.
=> dashboard: Support configuring GitHub Enterprise domain

host/containerinit/init.go
This will help debug an issue we’re seeing where containerinit processes stop health checking and responding to RPCs.
=> host/containerinit: Print goroutine trace to log fd on SIGUSR2

pkg/cluster/host.go
Some nodes in a cluster may be booted quicker than others, so we may as well wait longer (exiting leaves the cluster inoperable).
=> discoverd,flannel: Wait 20 minutes for appropriate host status

appliance/postgresql/Dockerfile, appliance/redis/Dockerfile, host/libvirt_lxc_backend.go
Not sure how I missed these...
=> appliance/redis,postgresql: Update base images

test/README.md, test/arg/arg.go, test/rootfs/setup.sh, test/runner/runner.go, test/scripts/cleanup.sh, test/scripts/install, test/scripts/upstart.conf
The new CI would have been pretty easy to setup if it wasn't for [this bug](https://github.com/docker/docker/issues/5704) :unamused:.
=> Test script updates

installer/ssh_cluster.go
=> installer: Don't attempt to use nil ssh agent

host/state.go
When iterating over the jobs bucket in `Restore` we don't need to take the mutex lock if we do so before calling `backend.UnmarshalState`. Move population of the resurrection list and drop the mutex lock to avoid deadlocking with potential locks held by `UnmarshalState`.
Fixes #2520 
Fixes #2481
=> host: Don't take lock when populating resurrection list

host/host.go
Fixes docopt to recognize `--max-jobs-concurrency` properly.
=> host: Fix max-jobs-concurrency docopt

cli/cluster.go
=> cli: Update local cluster config after successful domain migration

controller/worker/deployment/context.go, controller/worker/deployment/job.go, controller/worker/deployment/postgres.go
=> worker: Watch job events per release when deploying

controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go
=> scheduler: Ensure omni jobs do not become unbalanced

pkg/httpclient/json.go
=> pkg/httpclient: Don't use a timeout in ResumingStream

status/status.go
Optional services no longer mark the cluster as unhealthy.
This is a stepping stone to some sort of optional Flynn feature system or plugin mechanism to monitor appliances etc in a module way.
=> status: Optional services no longer mark cluster unhealthy

dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/stores/app.js
=> dashboard: Fix scaling app processes when no formation

util/release/version_template.json
Without this, the image will not be uploaded.
=> util/release: Add MariaDB to release manifest

controller/formation_test.go
=> Fix formation stream leak

host/cli/log.go
=> host/cli: Send stderr from log stream to stdout by default

installer/bare_cluster.go, installer/cluster.go, installer/schema.go
=> installer: Use --clean when using install script

cli/cluster.go, cli/export.go, controller/backup.go, pkg/backup/backup.go, pkg/backup/tar_writer.go
Ensure we update the progress bar while writing database dumps to tempfiles.
Closes #2336
Closes #2507
=> cli: Fix backup/export progress info

host/libvirt/types.go, host/libvirt_lxc_backend.go, test/test_host.go
=> host: Add 64MB /dev/shm to each container

test/test_release.go, updater/updater.go
=> updater: Fix updating slug environment variables

discoverd/server/store.go
b727a82 introduced a regression that sent all heartbeats through raft, instead of just new instances. Fix that regression while maintaining the correct mutex usage.
=> discoverd/server: Fix regression sending heartbeats through raft

updater/types/types.go, updater/updater.go
=> updater: Support MariaDB and Sirenia upgrade properly

test/rootfs/setup.sh
=> test/rootfs: Use upstart stop directly

controller/controller.go, controller/controller_test.go
Accidentally closed #2634 via #2490, reopening here with comment addressed.
\\cc @titanous
=> controller: Don't require auth for GET /ca-cert

installer/installer.go
=> installer: Print more readable startup errors

router/http.go, router/proxy/reverseproxy.go, router/proxy/transport.go, router/tcp.go
=> router: Improve proxied request error logging

dashboard/api.go, dashboard/app/lib/javascripts/dashboard/stores/github-repo-json.js, dashboard/config.go
=> dashboard: Always include auth token in clone url when using GitHub Enterprise

appliance/redis/cmd/flynn-redis-api/main.go, appliance/redis/cmd/flynn-redis/main.go, appliance/redis/cmd/flynn-redis/main_test.go
We can change to manual later when the redis appliance is HA.
=> appliance/redis: Use automatic leader election for now

appliance/mariadb/process.go, appliance/postgresql/postgres.go, host/fixer/fixer.go
=> Don't dereference nil database status

installer/persistence.go
Refs #2666 (this should fix the issue, or at least return a meaningful error).
=> installer: Add missing error check

dashboard/app/lib/javascripts/dashboard/routers/main.js, dashboard/app/lib/javascripts/dashboard/views/cluster-backup.js.jsx, dashboard/app/lib/javascripts/dashboard/views/nav.js.jsx
=> dashboard: Add button to download cluster backup

docs/content/how-to-deploy-java.html.md
on deploying Java applications
Closes #2700
Signed-off-by: Philip Lehmann-Boehm <philip@philiplb.de>
=> Added documentation about MAVEN_CUSTOM_OPTS

controller/backup.go, controller/backup_test.go, controller/client/client.go, controller/controller.go, controller/schema.go, controller/schema/queries.go, controller/types/types.go, pkg/httpclient/json.go, schema/controller/cluster_backup.json
=> controller: Backup refactor

cli/remote.go
=> cli: Respect -y flag in `remote add`

docs/content/operating.html.md
=> docs: Add details about status endpoint key

controller/scheduler/scheduler.go
Previously, StartJob would attempt to start a job 30 times with a delay of 500ms, and if the job didn't start then it would give up, but then the job would just stay pending indefinitely without any further attempt to start it.
The scheduler will now continue to start the job, with a slightly increased delay each time (capped at 30s).
Fixes #2745.
=> scheduler: Don't stop trying to start jobs

cli/export.go, cli/release.go, controller/client/client.go, controller/controller.go, controller/formation_test.go, controller/migrate_test.go, controller/release.go, controller/schema.go, controller/schema/queries.go, controller/types/types.go, controller/worker/main.go, controller/worker/release_cleanup/handler.go, test/test_cli.go
Closes #1569.
/cc @titanous @josephglanville
=> Support deleting releases and associated file artifacts

host/libvirt_lxc_backend.go
This may help track down #2737 if it reoccurs.
=> host: Log container IP assignment

cli/main.go
=> cli: Add redis/mysql to top-level help

discoverd/main.go
This fixes 2 things.
One is to close the heartbeater before shutting down, this makes shutdowns an order of magnitude faster and thus considerably less disruptive.
The other is to introduce a wait between shutting down the target and starting up on deployment equal to 2x the election timeout. This is to work around an issue with the Raft library. I am working on a more permanent solution to this in my reconfigure and smarter client branch but this is a stop gap to get everything working again as the chances of the issue manifesting with this sleep in place are very low.
=> discoverd: Deployment stability fixes

controller/migrate_test.go, controller/schema.go
Although in general we shouldn't change migrations that have already been released, this migration only made it into a release a few hours ago, and does not affect clusters which successfully migrated (i.e. those that did not have multiple releases with the same `SLUG_URL` set).
Fixes #2758.
=> controller: Avoid creating duplicate artifacts in migration

host/monitor.go
=> host: Log an error and return if postgres fails to be fixed

cli/run.go, controller/jobs.go, host/http.go, test/test_cli.go
=> controller,host: Check jobs have an image artifact

discoverd/main.go
=> discoverd: Guard against DNS server not being configured

appliance/mariadb/cmd/flynn-mariadb-api/main.go
This avoids a hard dependency on the controller being up. The controller is not up during cluster restores, so before this patch restores that included a MySQL dataset could not proceed.
=> appliance/mariadb: Skip controller checks if database is Read-Write

controller/worker/deployment/context.go
=> worker: Don't retry deploys when ErrSkipRollback is returned

dashboard/app/lib/javascripts/dashboard/actions/providers.js
Refs https://github.com/flynn/flynn/issues/2813#issuecomment-218824947
=> dashboard: Fix adding DB to app without release

cli/export.go, test/helper.go, test/test_cli.go
=> cli: Fix exporting new apps

docs/content/how-to-deploy-java.html.md
Signed-off-by: Philip Lehmann-Böhm <philip@philiplb.de>
=> docs: Add how to tweak java options

controller/events_test.go
This test intermittently fails in CI as it gets events generated by other tests, so I have updated it to ignore those other events.
=> controller: Fix TestStreamAppLifeCycleEvents

appliance/mariadb/process.go, host/fixer/fixer.go, host/monitor.go
This changset introduces attempted recovery of MariaDB via both the CLI fix tool and the cluster monitor.
=> MariaDB recovery

test/runner/runner.go
Fixes small typo in the runner script. /cc @lmars
=> test: Fix typo in runner script

appliance/redis/cmd/flynn-redis-api/main.go
=> appliance/redis: Set Redis environment variables on release

test/cluster/cluster.go, test/runner/runner.go
=> test: Fix configuring docker client (again)

dashboard/app/lib/javascripts/dashboard/views/app-route-new.js.jsx, dashboard/app/lib/javascripts/dashboard/views/app-routes.js.jsx
=> dashboard: Fix adding and displaying routes with path

bootstrap/status_check_action.go
=> bootstrap: Always close status check response body to prevent fd leak

dashboard/app/lib/javascripts/dashboard/routers/apps.js, dashboard/app/lib/javascripts/dashboard/stores/jobs-stream.js, dashboard/app/lib/javascripts/dashboard/views/app-logs.js.jsx, dashboard/app/lib/stylesheets/dashboard/app-logs.scss
=> dashboard: Improve log view

bootstrap/add_route_action.go, cli/app.go, cli/route.go, controller/routes_test.go, controller/worker/domain_migration/domain_migration.go, router/api.go, router/client/client.go, router/data_store.go, router/examples/client/client.go, router/http.go, router/http_test.go, router/migrate_test.go, router/schema.go, router/types/types.go, schema/router/certificate.json, schema/router/error.json, schema/router/route.json, test/test_cli.go
=> router: Manage TLS certificates independent of routes

Godeps/Godeps.json, Godeps/_workspace/src/github.com/hashicorp/raft/README.md, Godeps/_workspace/src/github.com/hashicorp/raft/raft.go
Minor update to bring in additional log message on transition to follower state.
Can make it easier to follow discoverd logs to find previous leader when something bad happens.
=> Godeps: Update hashicorp/raft

discoverd/server/handler.go, pkg/httphelper/request_logger.go
When logging all successful heartbeats etc the discoverd log can become overly verbose.
This change set removes logging of successful HTTP requests and redirects in favour of only logging failures.
We may need to add explicit logging for certain events to compensate for this if we find it necessary.
=> discoverd: Only log failed HTTP requests

cli/deployment.go, controller/app.go, controller/controller_test.go, controller/schema/queries.go, pkg/httphelper/httphelper.go, test/test_cli.go
```text
$ flynn deployment timeout
120
$ flynn deployment timeout 150
$ flynn deployment timeout
150
```
Closes #2662
=> Add `flynn deployment timeout`

test/test_z_discoverd.go
Hardens the Promote/Demote test against `discoverd` taking a while to start up HTTP API .
=> test: Ping new discoverd node until it responds

script/export-components, test/Tupfile, test/rootfs/setup.sh, test/runner/runner.go, test/test_release.go, test/util/file-server/README.md, test/util/file-server/main.go
I've also switched `TestReleaseImages` to use a simple file server rather than the blobstore.
=> test: Set BLOBSTORE_S3_CONFIG in CI

test/cluster/cluster.go
RAM is cheap, and CI has lots of it...
=> test: Increase VM memory

test/rootfs/build.sh
`ubuntu-core` has become `ubuntu-base`...
=> test: Update rootfs ubuntu URL

discoverd/deployment/deployment.go
It's possible for our event stream to not yet reflect the creation of
the deployment metadata because we are connected to a follower that
hasn't yet replicated the service meta command.
=> discoverd: Guard against decoding nil metadata

bootstrap/manifest_template.json, dashboard/api.go, dashboard/app/compiler.go, dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/routers/main.js, dashboard/app/lib/javascripts/dashboard/stores/cluster-status.js, dashboard/app/lib/javascripts/dashboard/views/cluster-status.js.jsx, dashboard/app/lib/javascripts/dashboard/views/nav.js.jsx, dashboard/app/lib/stylesheets/dashboard/application.scss, dashboard/app/lib/stylesheets/dashboard/cluster-status.scss, dashboard/config.go
=> dashboard: Cluster status page

cli/export.go, docker-receive/main.go, test/test_cli.go
=> cli: Fix Docker image import tag

gitreceive/receiver/flynn-receive.go, test/apps/crash/Procfile, test/apps/crash/app.sh, test/apps/crash/bin/compile, test/apps/crash/bin/detect, test/apps/crash/bin/release, test/test_git_deploy.go
=> gitreceive: Wait for service event on initial push

appliance/redis/Dockerfile
=> appliance/redis: Use redis PPA to update to 3.0.x

installer/stack_template.go
Signed-off-by: Kenaniah <kenaniah@gmail.com>
=> Adds encryption to EBS volumes

controller/scheduler/formation.go, controller/scheduler/host.go, controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go, controller/utils/utils.go, host/cli/collect-debug-info.go
This will help debug issues like #2895.
=> scheduler: Add HTTP endpoint to dump internal state

cli/app.go, controller/types/types.go, controller/worker/app_deletion/app_deletion.go, test/test_controller.go
=> controller: Delete releases when deleting apps

cli/export.go, test/test_blobstore.go
=> cli: Follow redirects when downloading slugs

controller/worker/domain_migration/domain_migration.go, router/api_test.go, test/test_z_domain_migration.go
=> controller: Fix domain migration

pkg/postgres/listener.go
@josephglanville this fixes the CI data races you saw.
=> pkg/postgres: Avoid race when closing listener

dashboard/app/lib/javascripts/dashboard/views/apps-list.js.jsx, dashboard/app/lib/javascripts/dashboard/views/apps.js.jsx, dashboard/app/lib/stylesheets/dashboard/apps.scss, dashboard/app/lib/stylesheets/dashboard/items-list.scss
fixes #2109
Signed-off-by: Philip Lehmann-Boehm <philip@philiplb.de>
=> dashboard: Added a link below the apps list to toggle the system apps

appliance/mongodb/cmd/flynn-mongodb-api/main.go
=> appliance/mongodb: Fix DATABASE_URL protocol

dashboard/app/lib/javascripts/dashboard/stores/app-routes.js, dashboard/app/lib/javascripts/dashboard/views/app-routes.js.jsx
=> dashboard: Fix linking to app routes with path and use HTTPS

router/migrate_test.go, router/schema.go
=> router: Fix TLS migration

dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/views/cluster-status.js.jsx
=> dashboard: Fix status page when cluster unhealthy

Vagrantfile, appliance/postgresql/Dockerfile, appliance/postgresql/main.go, appliance/postgresql/postgres.go, controller/formation.go, controller/jobs.go, controller/schema/queries.go, docs/content/postgres.html.md, host/cli/update.go, test/rootfs/setup.sh
Upgrade to 9.5, making use of the new UPSERT functionality to clean up some controller queries.
Closes #2534
=> PostgreSQL 9.5

script/release-flynn
=> script: Fix re-executing release-flynn script

Vagrantfile
Install database test dependencies in development Vagrant virtual machine.
=> Vagrantfile: Install database appliance test dependencies

gitreceive/server.go, test/test_git_deploy.go
=> gitreceive: Show error when pushing to non-master branch

test/test_scheduler.go
=> test: Synchronize with scheduler when changing host tags

Vagrantfile
* Fix installing MongoDB
* Only run apt-get update once
* Make additions to apt sources idempotent so provision can be re-run
* Don't error on failing to create postgres user
* Don't error on failing to start docker
* Configure VM locale to en_US.UTF-8 regardless of host locale
=> Vagrantfile: Improve initial setup

appliance/mariadb/process_test.go
A more detailed explaination is why this change is necessary is
in the linked issue.
Closes #3065
=> appliance/mariadb: Fix waitReadWrite in integration tests

test/rootfs/setup.sh
=> test: Add squashfs-tools to rootfs

appliance/mariadb/process_test.go
Still tracking down sporadic failures, issues only occur in CI so this should help track them down.
=> appliance/mariadb: Improve logging in integration test

discoverd/client/heartbeat.go
=> discoverd/client: Retry registering services and creating heartbeater

host/cli/list.go
If discoverd is available show the Raft status for each host, ie:
```
$ flynn-host list
ID     ADDR              RAFT STATUS
host1  192.0.2.201:1113  peer
host2  192.0.2.202:1113  peer
host0  192.0.2.200:1113  peer (leader)
host3  192.0.2.203:1113  proxy
```
=> host/cli: Show host Raft status in list

Godeps/Godeps.json, vendor/github.com/jackc/pgx/CHANGELOG.md, vendor/github.com/jackc/pgx/conn.go, vendor/github.com/jackc/pgx/conn_pool.go, vendor/github.com/jackc/pgx/query.go, vendor/github.com/jackc/pgx/values.go
Update pgx to bring in the non-blocking `ConnPool.Acquire()`
=> vendor: Update pgx

appliance/mariadb/process_test.go
The semi-sync plugin doesn't increment `master_clients` until the
connected slave has acked a message. Because of this `SLAVE_HOSTS`
can show a connected slave before `master_clients`.
Instead just use `SLAVE_HOSTS` for verifying the correct downstream
is present and use `master_clients` for determining read/write.
=> appliance/mariadb: Wait for master_clients > 0

controller/events_test.go
We don't guarantee that events will be delivered in a specific order.
=> controller: Fix event ordering assumption in TestStreamReleaseEvents

gitreceive/server.go
When a push fails, there is no reason to upload the repo to the blobstore, as it should be unchanged.
Refs #3161
=> gitreceive: Don't persist git repo if push failed

cli/docker.go, test/test_cli.go
=> cli: Only use ENV from docker images as defaults

bootstrap/manifest_template.json
=> docker-receive: Use status endpoint for health checks

docs/content/mongodb.html.md, docs/docs-nav.json
Document usage for the MongoDB appliance.
=> docs: Add MongoDB page

docs/content/operating.html.md
Documents use of promote/demote to replace Raft consensus members.
=> docs: Document host replacement

router/data_store.go, router/http_test.go, router/schema/queries.go, router/server.go, router/setup_test.go
Updates the router datastore to use prepared queries.
Closes #3179
=> router: Use prepared queries

cli/docker.go
=> cli: Fix docker TLS error detection

installer/aws_cluster.go
=> installer: Bump CloudFormation stack creation timeout to 30 mins

installer/aws_cluster.go, installer/azure_cluster.go, installer/cluster.go, installer/digital_ocean_cluster.go, installer/events.go, installer/schema.go, installer/ssh_cluster.go
=> installer: Fix race condition accessing cluster state

installer/events.go, installer/schema.go
=> installer: Fix SSH install with multiple nodes

test/test_host.go
We don't guarantee the order that events are delivered in.
=> test: Fix flaky HostSuite.TestAddFailingJob

controller/jobs.go, host/libcontainer_backend.go, pkg/cluster/attach.go
This fixes several bugs related to the cleanup of attached processes as well as a fd leak. See the individual commit messages for details.
Closes #3158
=> Fix attach zombies

controller/jobs_test.go
This test was racing with the one-sided close detection in the controller handler.
=> controller: Fix race in TestRunJobAttached

appliance/redis/cmd/flynn-redis-api/main.go, bootstrap/create_artifact_action.go, bootstrap/manifest_template.json, cli/export.go, controller/examples/examples.go, gitreceive/receiver/flynn-receive.go, host/cli/bootstrap.go, test/test_release.go, updater/updater.go
=> gitreceive,taffy,redis: Use artifact IDs rather than URIs

controller/worker/deployment/all_at_once.go, controller/worker/deployment/one_by_one.go, test/apps/http/Godeps/Godeps.json, test/test_git_deploy.go
=> controller: Fix removing release process types

script/install-flynn.tmpl, test/test_release.go
=> script: Require --clean when re-running the install script

host/volume/api/http.go, host/volume/manager/manager.go, host/volume/zfs/zfs.go
Some minor refactors extracted from #3100.
=> Host volume updates

README.md
This makes it super clear where to start contributing to the code.
=> Readme: Add link into Development Guide

host/cli/update.go
Updating from versions prior to v20160711.0 is currently broken as they try and download the nsumount binary which no longer exists.
We actually decided not to support in-place updates from libvirt-lxc to libcontainer so we just need to tell users to do a backup/restore instead, so I have bumped the minVersion and also fixed it so that it's compared against the version of hosts running in the cluster (rather than checking its own version, which will never fail).
=> host: Fix checking minimum update version

dashboard/app/lib/javascripts/dashboard/stores/providers.js
=> dashboard: Handle missing providers

bootstrap/manifest_template.json, dashboard/api.go, dashboard/app/lib/javascripts/dashboard/actions/nav.js, dashboard/app/lib/javascripts/dashboard/client.js, dashboard/app/lib/javascripts/dashboard/config.js, dashboard/app/lib/javascripts/dashboard/main.js, dashboard/app/lib/javascripts/dashboard/routers/apps.js, dashboard/app/lib/javascripts/dashboard/routers/main.js, dashboard/app/lib/javascripts/dashboard/views/route-link.js.jsx, dashboard/config.go
=> dashboard: Minor improvements to install cert

dashboard/app/lib/javascripts/dashboard/stores/app-routes.js
=> dashboard: Ignore TCP routes for now to avoid breaking UI

discoverd/main.go
=> discoverd: Wait indefinitely for leadership on startup

docs/content/docker.md
The Node.js app conforms to the expectations of a Flynn app (i.e. it listens on the PORT environment variable) so provides a better example than ElasticSearch.
I have also clarified the routing setup.
Closes #3222.
=> docs: Use the Node.js example app as Docker push example

controller/worker/deployment/one_by_one.go
The `oldScale` map will most likely contain types with a zero count (i.e. ones that have just been scaled down) and there is no need to add them to the diff.
=> worker: Fix final scale down in one-by-one deploy

appliance/mongodb/process.go, bootstrap/manifest_template.json
=> appliance/mongodb: Fix UserExists check

host/containerinit/init.go, test/test_host.go
Some containerised apps expect to be able to use `/dev/stdout` and `/dev/stderr` to write data to stdout / stderr (e.g. [the official Docker nginx app](https://github.com/nginxinc/docker-nginx/blob/1.11.1/mainline/jessie/Dockerfile#L21-L23)), but that doesn't work if those paths point to sockets (in which case `open(2)` fails with `ENXIO`, see http://marc.info/?l=ast-users&m=120978595414993).
My solution here is to provide jobs with a standard pipe, continue to provide flynn-host with a socket and copy data between the two. This isn't ideal as the data is now being copied through containerinit's memory. If we think this is problematic we could provide a flag to enable this just for jobs which require the use of `/dev/stdout` and `/dev/stderr`.
/cc @titanous @josephglanville
=> host: Allow non-TTY jobs to use open(2) on /dev/stdout & /dev/stderr

host/host.go, host/http.go, host/volume/api/http.go, pkg/postgres/postgres.go, test/test_backup.go, test/test_controller.go, test/test_postgres.go, test/test_release.go, test/test_zz_backup.go
It is proving disruptive to other tests.
=> test: Don't run BackupSuite concurrently

host/containerinit/init.go
Instead of waiting until the process exits after a signal to pull the registration from discoverd, remove it immediately after receiving a SIGINT/SIGTERM. This ensures that that process can shut down cleanly without getting additional traffic from the router.
Closes #3388
=> host/containerinit: Unregister from discoverd on signal

installer/app/src/views/digital-ocean-launcher.js.jsx
=> installer: Fix Digital Ocean launcher

dashboard/api.go, dashboard/config.go
=> dashboard: Add content security headers

blobstore/Dockerfile, blobstore/Tupfile, blobstore/blobstore.go, blobstore/cleanup.go, blobstore/migrate.go, docs/content/production.html.md, test/test_blobstore.go
Closes #3353 
Any documentation needing update?
/cc @titanous @lmars
=> blobstore: merge blobstore commands into single binary

cli/export.go, cli/run.go, controller/jobs.go, controller/types/types.go, schema/controller/new_job.json, test/test_cli.go
=> cli: Just use the slugrunner image when exporting slugs

dashboard/app/lib/javascripts/dashboard/stores/app-routes.js, dashboard/app/lib/javascripts/dashboard/views/provider-route-create.js.jsx, dashboard/app/lib/javascripts/dashboard/views/resource.js.jsx
Closes #3433.
Bug introduced in #3315.
=> dashboard: Fix external route logic

gitreceive/receiver/flynn-receive.go, test/main.go, test/test_gitreceive.go
=> gitreceive,test: Include current env in env dir

host/host.go
=> host: include promote and demote on flynn-host ps -h

discoverd/client/client.go
* Don't shadow the errors module
* Retry until RequestDeadline is reached.
* Retry all servers again after RetryInterval.
=> discoverd/client: Improve client retry behavior

test/test_scheduler.go
Getting a deployment complete event no longer guarantees that all the old jobs have been scaled down (see #3395), so we need to wait for them explicitly.
=> test: Wait for job down events in TestDeployController

demo/Makefile
=> demo: depend on install-cli target on Makefile where required

discoverd/server/store.go, discoverd/server/store_test.go
=> discoverd: Prevent deadlock when restoring from snapshot

dashboard/app/lib/javascripts/dashboard/views/app-env.js.jsx, dashboard/app/lib/javascripts/dashboard/views/edit-env.js.jsx
=> dashboard: Sort env keys / add save keyboard shortcut

cli/ps.go, controller/jobs.go, controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/schema.go, controller/schema/queries.go, docs/content/apps.md, docs/content/basics.md
closes #3332
```
$ flynn ps
ID                                          TYPE   COMMAND                   STATE  CREATED        RELEASE
host0-1b79af28-ae73-4b1f-b971-9a2c568cdfd0  web    /runner/init start web    up     5 minutes ago  905b99b3-edf0-496f-b9be-73442821f178
host0-ca18e56f-5fee-4f54-b943-2005168b3884  web    /runner/init start web    up     5 minutes ago  905b99b3-edf0-496f-b9be-73442821f178
host0-67952632-50db-4dba-878d-046990bda445  web    /runner/init start web    up     5 minutes ago  905b99b3-edf0-496f-b9be-73442821f178
host0-ecf97b0c-e29b-4675-bc1e-3661f3771954  clock  /runner/init start clock  up     5 minutes ago  905b99b3-edf0-496f-b9be-73442821f178
$ flynn ps -a
ID                                          TYPE         COMMAND …
```
=> cli: show command on flynn ps

cli/ps.go
This field won't work on older clusters and is usually redundant.
Use `-c` or `--command` to show the command field.
=> cli: Make ps command display optional

router/http_test.go, router/proxy/reverseproxy.go
=> router: Fix handling of paths beginning with //

controller/app.go, controller/controller_test.go, controller/migrate_test.go, controller/schema.go
=> controller: Default gc.max_inactive_slug_releases to 10

docs/content/installation/cloud.md
=> docs: Update SSH user for each cloud provider

docs/content/apps.md
Signed-off-by: Ben Rometsch <ben@solidstategroup.com>
=> Added info on deploying specific branches

slugrunner/runner/init, test/test_git_deploy.go
=> slugrunner: Allow user to write to /dev/std{out,err}

cli/kill.go, cli/main.go, cli/ps.go
- Resolves #3532 
- Add --quiet flag to `flynn ps`
- Add --type flag to `flynn ps`
- Let `flynn kill` receive multiple job IDs
=> 3532 cli enhancements

discoverd/server/store.go, discoverd/server/store_test.go
=> discoverd: Remove service meta when removing service

slugrunner/runner/init
fixes #3545
https://devcenter.heroku.com/articles/dynos#the-profile-file
=> Add support for .profile

test/rootfs/setup.sh, test/scripts/install, util/_toolchain/build.sh
https://golang.org/doc/devel/release.html#go1.7.minor
=> all: Update to Go 1.7.3

appliance/mongodb/process.go, host/fixer/fixer.go, host/fixer/sirenia.go, host/monitor.go
Misc fixes to the the cluster fixer/resurrection code for MongoDB.
Fixes #3572
Fixes #3552
=> Mongodb recovery fixes

Vagrantfile, appliance/mariadb/Dockerfile, appliance/mongodb/Dockerfile, appliance/postgresql/Dockerfile, test/rootfs/setup.sh
=> test: Update mariadb apt key

host/cli/collect-debug-info.go
Can be helpful in determining state of Sirenia clusters quickly without having to trawl through lots of logs.
=> host/cli: Collect Sirenia metadata in debug info

host/containerinit/init.go, test/test_host.go
=> host: Use FIFO for job stdout / stderr

controller/client/client.go, controller/client/v1/client.go, controller/types/types.go
See bc1ef1041d16243c737a121da7a111d465a5eb6a
=> controller: Remove unused SSH key methods and type

cli/export.go, test/test_cli.go
=> cli: Fix exporting Docker images to stdout

host/cli/download.go
This means we can continue to use the nightly version of `flynn-host` to bootstrap the stable version, even if the image format is different (as it is right now).
=> host: Re-exec the requested version of flynn-host on download

vendor/github.com/awslabs/aws-sdk-go/aws/ec2.go
=> Fix creating EC2 keypair

controller/client/v1/client.go, host/cli/update.go, test/test_release.go
I've also thrown in a fix for the scale timeout.
=> host/cli: Bump minimum update version

cli/main.go, cli/pg.go, script/start-flynn-host
=> cli: Fallback to --jobs=1 when importing to old clusters 

script/install-flynn.tmpl
=> install-script: Ignore 'systemctl stop' failure

host/libcontainer_backend.go, pkg/dialer/retry.go
Previously we were getting an IP for discoverd URLs and retrying requests to that IP, whereas we want to do the lookup on each retry to handle services being deployed.
Fixes #3666.
=> host: Use discoverd aware HTTP retry client

cli/export.go, cli/run.go, controller/types/types.go, schema/controller/new_job.json
=> cli: Fix exporting slugs from old clusters

host/Dockerfile, host/cleanup.sh, host/start.sh, pkg/exec/exec.go, test/cluster/cluster.go, test/cluster2/cluster.go, test/helper.go, test/rootfs/build.sh
I've also moved the host zpool cleanup into a separate job to make sure it always runs.
=> test: Increase disk / memory / cores for default CI VM

test/helper.go
When running concurrently, some backup tests were failing with:
```
Get https://controller.0df394315d49921d12be96cfe935e677.1.localflynn.com/apps/nodejs/release: remote error: tls: internal error
```
The domain was being resolved incorrectly because the Go resolver had just read `/etc/hosts` after booting a previous cluster, and did not re-read it because it has a cache age of 5s (see [here](https://golang.org/src/net/hosts.go)).
The backup tests take around a minute, so waiting 5s isn't a big deal.
=> test: Wait for the Go resolver's /etc/hosts cache to expire

controller/jobs.go, controller/utils/utils.go
=> controller: Retry provisioning volumes and running jobs

host/cli/collect-debug-info.go, host/cli/gist.go
=> host/cli: Add --filename option to collect-debug-info

pkg/imagebuilder/builder.go
=> pkg/imagebuilder: Only convert non-empty layers

host/libcontainer_backend.go
Fixes logic for determining if we should enable IP forwarding.
=> host: Fix enabling of IP forwarding

host/cli/bootstrap.go
When restoring from backup we need to run the docker-migrator with
CAP_SYS_ADMIN as it execs docker-artifact as a child process rather
than in a seperate job.
=> host/cli: Run docker-migrator with CAP_SYS_ADMIN

script/release-channel, script/release-flynn
=> script: Fix changelog generation

schema/controller/sink.json, schema/examples/controller/sink_create.json, schema/examples/controller/sink_delete.json, schema/examples/controller/sink_get.json, schema/examples/controller/sink_list.json
Fix up JSON schema for docs generation.
=> schema: Fix sink schema examples

appliance/mongodb/dump.sh, test/test_mongodb.go
=> appliance/mongodb: Fix dumping empty databases

host/state.go
Makes CreatedAt consistent with other timestamps including StartedAt.
=> host: Use UTC time for CreatedAt in host state

router/server.go, router/tcp.go, router/tcp_test.go
=> router: Don't allow routes to bind to HTTP ports

test/rootfs/setup.sh, util/_toolchain/build.sh
=> util/_toolchain: Update to Go 1.7.5

router/http.go, router/http_test.go
Add support for top level wildcard route
Closes #3779
=> router: allow catch-all route

cli/resource.go
Makes the `resource` command slightly more ergonomic.
=> cli: Resolve resource automatically where possible

Vagrantfile
This fixes #3904
Signed-off-by: Onni Hakala <onni@keksi.io>
=> Bump vagrant version requirement from 1.6.0 to 1.9.0

docs/content/architecture.html.md
Signed-off-by: Onni Hakala <onni@keksi.io>
=> Docs: Update Ubuntu version 14.04->16.04

controller/release.go, controller/schema/queries.go, test/test_docker_receive.go
=> controller: Don't delete layers referenced by multiple images

router/http.go, router/http_test.go
If a client specifies a Request-ID request header, it will be passed to a backend without replacement it meets some basic criteria: the value must be between 20 and 200 characters, and consist of ASCII letters, digits, or the characters +, /, =, and -. Invalid IDs will be ignored and replaced with a randomly generated UUID.
Closes #3939
=> router: Pass client-specified Request-ID header

discoverd/client/watch.go
This ensures we don't leak a stream if a call to `Watch.Close` happens during a stream reconnect.
=> discoverd: Prevent race between Watch.Close and Watch.Connect

appliance/mongodb/restore.sh, cli/mongodb.go
=> appliance/mongodb: Use a data volume for restore job

host/host.go, host/start.sh
To help debug why `TestUpdateLogs` continues to fail.
=> host: Send flynn-in-flynn host logs to stdout

controller/worker/deployment/context.go
We were previously sending the deploy complete event before marking the deployment as done, meaning the client may try and perform another deployment and get an error as one is still in progress.
=> controller/worker: Fix deployment event race

cli/scale.go
=> cli: Fix 'flynn scale' with older clusters

controller/controller.go, controller/jobs.go, controller/jobs_test.go
=> controller: Allow some job operations for deleted apps

appliance/redis/cmd/flynn-redis-api/main.go, test/test_redis.go
=> appliance/redis: Fix REDIS_HOST and REDIS_URL

cli/cluster.go, controller/controller_test.go, controller/sink.go, controller/types/types.go, host/cli/log_sink.go, host/logmux/sink.go, test/test_host.go
So that it is encoded as raw JSON rather than a base64 string.
=> controller: Make Sink.Config a *json.RawMessage

cli/scale.go, controller/scheduler/scheduler.go, dashboard/app/lib/javascripts/dashboard/stores/app-history.js, discoverd/main.go, docs/content/languages/ruby.md, flannel/backend/vxlan/device.go, host/attach.go, host/discoverd_wrapper.go, host/volume/zfs/zfs.go, pkg/cors/README.md, pkg/cors/cors.go, pkg/lru/lru.go, pkg/stream/stream_example_test.go, test/test_cli.go
Signed-off-by: ferhat elmas <elmas.ferhat@gmail.com>
=> all: Fix some typos

host/cli/bootstrap.go
The controller stores various records about jobs and volumes in its database during normal operation, and these records are stored in cluster backups. When starting a new cluster, these records are no longer needed and the stale volume records can cause the scheduler to get confused if hostnames are reused.
This patch deletes all old job and volume events, job/volume associations, jobs, and volumes from the controller database during bootstrap.
=> host/cli: Delete job/volume records during bootstrap

dashboard/api.go
Closes #3267
Signed-off-by: Philip Lehmann-Boehm <philip@philiplb.de>
=> dashboard: added a route GET /robots.txt disallowing all crawling

pkg/httpclient/json.go
If a custom dialer is not specified and the scheme is https, Hijack should use HTTPS, not plaintext HTTP.
Closes #4080
=> pkg/httpclient: Use TLS dialer for Hijack

Vagrantfile, cli/route.go, router/api.go, router/data_store.go, router/http.go, router/http_test.go, router/schema.go, router/schema/queries.go, router/server.go, router/tcp.go, router/tcp_test.go, router/types/types.go, test/test_router.go
This probably still needs a lot of work, but I've got what I think is a good core of a solution for #2633. @titanous, can you give it a quick glance, tell me if you see problems with the changes thus far.
=> Multiple HTTP/HTTPS ports (for #2633)

builder/build.go, builder/export.go, builder/manifest.json, script/build-flynn, script/release-flynn
This includes a few other fixes too.
=> builder: Switch to production TUF repository

Vagrantfile, builder/img/go.sh, test/rootfs/setup.sh
=> builder,test: Move protoc installation logic into builder

Vagrantfile, cli/update.go, script/build-flynn
See the individual commits for details.
=> Various build fixes

cli/docker.go, script/build-flynn
Replaces #4160
Closes #4156
Closes #3466
=> cli: Handle removal of Docker --email flag

docs/content/basics.md
Fixes #4280 
Signed-off-by: Mriyam Tamuli <mbtamuli@gmail.com>
=> docs: Add `flynn route` command in basics doc

builder/manifest.json, dashboard/app/Gemfile.lock, util/assetbuilder/build.sh
=> dashboard: Update yajl-ruby

docs/content/development.html.md
=> docs: Update "Releasing Flynn" section

test/runner/runner.go
Fixes #464
Signed-off-by: Jorge Ferreira <imjorge@users.noreply.github.com>
=> test/runner: skip build with "[ci skip]"

Vagrantfile, appliance/postgresql/cmd/flynn-postgres/main.go, appliance/postgresql/img/packages.sh, appliance/postgresql/process.go, docs/content/databases/postgres.md
The tests for this pass locally.
Closes #4265
=> appliance/postgres: Update to PostgreSQL 10

host/state.go, test/test_host.go
Only keep 25 down jobs per app in memory, the rest are garbaged collected and only available when fetched by ID.
Closes #4334
=> host: Limit the number of stopped jobs in memory

script/start-flynn-host
=> script: Look for enp network interface to bind to and fallback to lo

dashboard/api_test.go, dashboard/app/lib/javascripts/dashboard/views/app-processes.js.jsx, dashboard/app/lib/stylesheets/dashboard/app-processes.scss, dashboard/bindata.go, script/dashboard-dev
Also updated the dashboard-dev script (related: #1452)
=> dashboard: Show processes diff in confirmation dialog when scaling

pkg/exec/exec.go
This fixes a race in gitreceive where Wait is called after the connection closes for cleanup as well as during the request lifecycle. Sometimes the close notify is delivered just before the request
finishes resulting in two calls to Wait.
=> pkg/exec: Allow multiple calls to Wait

router/http.go
=> router: Add connection idle and header read timeouts

gitreceive/server.go
When this flag is the default of on, repos uploads can be corrupted when they happen in parallel with the forked `git gc --auto`.
=> gitreceive: Turn off git gc autoDetach

script/build-flynn, test/README.md, test/cluster/instance.go, test/img/packages.sh, test/scripts/setup.sh
This updates the `test/scripts/setup.sh` to support creating and deploying the CI app, as well as updating the docs in `test/README.md`.
=> CI updates

pkg/httpclient/json.go
=> pkg/httpclient: Add OAuth header to Hijacked requests
