discoverd/client/dialer/dialer.go, discoverd/client/dialer_test.go
Instead of trying to dial a single random instance once, try to dial each instance in the list in random order before giving up.
This should fix one or two intermittent test failures.
Refs #686
=> discoverd/client/dialer: Try to dial each service before giving up

slugbuilder/builder/buildpacks.txt, slugbuilder/builder/install-buildpack
This adds support for specifying the npm version in `package.json`, among other things.
https://github.com/heroku/heroku-buildpack-nodejs/compare/fae41898...1ebb095a
=> Bump nodejs buildpack

host/cli/bootstrap.go, host/cli/download.go
This is much less confusing than hanging waiting for STDIN.
=> Add default manifest paths to download and bootstrap

discoverd2/server/state.go, discoverd2/server/state_test.go
This implements the core list of services and instances that will be hooked up to a consensus/communication backend like etcd as well as the HTTP and DNS read APIs.
I'm trying to send review-sized PRs instead of just the final result, so this is an intermediate (working, with 84% test coverage) patch for #145.
=> discoverd2: Add state implementation

bootstrap/manifest_template.json
This adds the dashboard link and token to the log message, and a link to the CLI installation page:
```
12:47:19.635648 log log-complete
12:47:19.635819 log log-complete 
Flynn bootstrapping complete. Install the flynn-cli (see https://cli.flynn.io for instructions) and paste the line below into a terminal window:
flynn cluster add -g dev.localflynn.com:2222 -p tMq6CLHmv2g9ys2Zf/2n4WnC63tdscFsNMflk91538k= default https://controller.dev.localflynn.com aa01ab76e5a68bb33e2678e67813baa4
The built-in dashboard can be accessed at http://dashboard.dev.localflynn.com with login token 3daf12f05c20f88edcf201f386f8818f
```
=> bootstrap: Log dashboard link and token

discoverd2/server/backend.go, discoverd2/server/etcd_backend.go, discoverd2/server/etcd_backend_test.go, discoverd2/server/state.go, discoverd2/server/state_test.go
This implements the etcd backend for discoverd2, and is an incremental patch for #145.
The unit test coverage is at 89.2% with only some simple error paths left untested.
=> discoverd2: Implement etcd backend

script/run-integration-tests
The integration scripts run test checks against output which was changed in the "Log dashboard link and token" commit ( https://github.com/flynn/flynn/pull/699 ), so this is changing to match.
=> fix bootstrap success detection in integration test kickoff script

website/lib/markdown_html.rb
There was a typo in their docs, it’s ‘sections’, not ‘section’.
=> website: Fix swiftype section annotation

flannel/runner.go, host/manifest_template.json
[RFC 6598](https://tools.ietf.org/html/rfc6598) defines 100.64.0.0/10 as shared address space to be used for carrier-grade NAT, but it also allows its use as private address space.
Using this instead of 172.16.0.0/12 will avoid a ton of conflicts.
Closes #724
=> flannel: Use RFC 6598 shared address space

discoverd2/client/instance.go, discoverd2/server/backend.go, discoverd2/server/etcd_backend.go, discoverd2/server/etcd_backend_test.go, discoverd2/server/state.go, discoverd2/server/state_test.go
Incremental patch for #145.
There are zero code changes here, just namespace changes. Instead of creating a `types` package, the shared types will live in the client package, the tests will remain in the server package.
=> discoverd2: Move Instance, Event, and EventKind to client package

controller/client/client.go, pkg/cluster/client.go, pkg/cluster/host.go, pkg/httpclient/stream.go
This makes creating http client streams significantly terser at the cost of a tiny bit more reflection, by automatically producing message objects based on the output channel's element type.
=> simplify httpclient.Stream invocation

controller/formation.go, controller/jobs.go, host/http.go, host/sampi/http.go, pkg/sse/sse.go
Remove a redundant interface, remove stutter, and force usage of the constructor function.
=> pkg/sse: Minor Writer refactor

pkg/httpclient/stream.go
This unblocks the SSE decoder if the stop request comes in while we are blocked in a read.
=> pkg/httpclient: Close stream http response body when stopping

pkg/httpclient/json.go
`RawReq` does not close the response body if the out parameter is nil. This patch adjusts `Send` to close the body if out is nil, as it does not expose the response to callers.
=> pkg/httpclient: Ensure we don’t leak HTTP response bodies

bootstrap/run_job_action.go, controller/client/client.go, controller/jobs.go, controller/testutils/fake_host_client.go, host/cli/log.go, host/cli/stop.go, host/host.go, host/http.go, host/sampi/http.go, pkg/cluster/client.go, pkg/cluster/host.go, pkg/exec/exec.go, pkg/httpclient/json.go, test/helper.go, test/test_host.go, test/test_scheduler.go
One tiny change suggested by @archSeer; and a rename that will make sense as the volumes API comes in next to this.
=> host API cleanup

util/cedarish/Dockerfile
Heroku added these packages to their official cedar-14 stack, which we track:
OpenJDK:
https://devcenter.heroku.com/changelog-items/585
heroku/stack-images@2d3932e431f2f8c165d9ec8c1b7a016fa6de5e11
Postgres headers:
https://github.com/heroku/stack-images/commit/d15c442831ac39d4c7a952d833127369af209569
=> util/cedarish: Add new upstream packages

dashboard/app/lib/javascripts/dashboard/routers/apps.js, dashboard/app/lib/javascripts/dashboard/stores/app-jobs.js, dashboard/app/lib/javascripts/dashboard/stores/app.js, dashboard/app/lib/javascripts/dashboard/stores/job-output.js, dashboard/app/lib/javascripts/dashboard/stores/taffy-jobs.js, dashboard/app/lib/javascripts/dashboard/views/app-logs.js.jsx, dashboard/app/lib/javascripts/dashboard/views/app.js.jsx, dashboard/app/lib/javascripts/dashboard/views/github-deploy.js.jsx, dashboard/app/lib/javascripts/dashboard/views/nav.js.jsx, dashboard/app/lib/stylesheets/dashboard/app-logs.css.scss
Note that only apps deployed through the dashboard with this version or later will have deploy logs visible in the dashboard UI.
=> dashboard: Show deploy logs in UI + minor fixes

discoverd2/health/check.go, discoverd2/health/check_test.go
Incremental patch for #145.
This adds a simple package that can check the health of HTTP(S) and TCP endpoints, it will be used to automatically register/unregister services (probably from containerinit). The tests cover 100% of the statements.
=> discoverd2: Add healthcheck package

discoverd2/health/check.go, discoverd2/health/monitor.go, discoverd2/health/monitor_test.go
Incremental patch for #145.
This builds on the health check capabilities to provide a monitor that runs checks on a regular basis and signals a channel when a check changes state.
=> discoverd2: Implement health monitor

controller/client/client.go, pkg/cluster/client.go, pkg/cluster/host.go, pkg/httpclient/json.go, router/api.go, router/client/client.go
If a non-200 response has an `application/json` Content-Type and decodes successfully into a `JSONError`, return it. If not, fallback to the old behavior of returning generic errors.
=> pkg/httpclient: Decode JSON errors

controller/client/client.go, host/attach.go, pkg/cluster/attach.go, pkg/httpclient/json.go
Since we're using an uniform client for doing http requests, we can provide a
convenience method for hijacking. This also standardises hijacking -- the attach
endpoint used status 200, but http.SwitchingProtocols seems more appropriate.
Whereas Stream is defined as a SSE stream of JSON objects, Hijack is more
general and unspecified, allowing for custom protocols where SSE would not work
well.
=> pkg/httpclient: Consolidate HTTP hijacking.

util/commit-validator/validate-dco
At some point the sanitizer for anchor generation changed, this adds a missing apostrophe to the anchor.
=> util/commit-validator: Fix DCO link

.travis.yml, router/api_test.go, router/setup_test.go
This code is brittle as it makes many assumptions about the behavior of etcd/discoverd, which may not be correct. It was originally added to make the tests faster, but inaccurate tests are useless, no matter how fast.
Closes #771
=> router: Remove fake etcd/discoverd from tests

appliance/postgresql/runner.go
Follow-up to b95e7ad5 / #772.
Remove code that references discoverd and is unused after disabling the follower code. This will make landing discoverd2 easier.
=> appliance/postgresql: Remove some dead follower code

cli/app.go, cli/git.go, test/test_cli.go
=> cli: Adding --remote flag on "flynn create" command

router/http.go, router/http_test.go, router/server.go, router/tcp.go, router/tcp_test.go
This is an initial attempt at implementing #267. I'm still getting up to speed on the code base so I'd love to get some feedback on this approach & any style issues.
The keypair passed into the new `HTTPListener` is used as the default `tls.Certificate` for SNI & non-SNI clients alike. This is handled by `tls.Config`'s `NameToCertificate` map, which is populated in the `tls.Server` call.
=> router: add default tls keypair to server

router/http.go, router/http_test.go
Some http clients do not down-case the hostname in the Host header of the HTTP request and the servername in the TLS client-hello. Matching route domains in a case-insensitive way prevents 404 and TLS handshake errors for such clients. The request's Host header is not altered and keeps the original casing.
=> router: make domain name lookup case insensitive

router/handlers.go, router/handlers_test.go, router/http.go, router/http_test.go
This PR switches Flynn's router away from using the somewhat-deprecated `httputil.ClientConn` and `httputil.ServerConn` to using `net/http` HTTP parsers and handlers.
Because there are subtle differences between handling protocol upgrades (i.e. for websockets) and regular request proxying, there's a lot of duplicated logic between the functions that handle these paths. I think we'll be able to clean that up a lot, but would rather this doesn't spend too much more time in a side branch :)
We pretty quickly had to move away from `httputil.ReverseProxy` as it makes it basically impossible to do some of the stuff we want to do with trying conns to multiple backends, and it also wouldn't work for the websocket upgrade. In doing so, we've currently lost some of the nice parts of that package …
=> router: switch to from net/http/httputil to net/http

host/libvirt/types.go
The empty fields were causing the following error:
```
[Code-27] [Domain-19] XML error: Missing required address attribute in network 'flynn'
```
=> host: Fix libvirt network XML

test/cluster/cluster.go, test/rootfs/setup.sh, test/scripts/test-unit.sh
Move unit tests into flynn CI.  Will deprecate travis.
Adds dependencies of unit tests to the rootfs used in CI.
Adds a script 'test/scripts/test-unit.sh' which can drive unit tests.  In the future, this script can be modified without requiring updates to the main CI binary.
If unit tests fail, the entire run will be halted; cluster bootstrapping and integration tests will not be run.
=> Run unit tests in flynn CI

router/http.go, router/http_test.go
It is totally valid for a Host header to look like:
Host: example.com:80
or
Host: example.com:443
This will cause a 404, as the route doesn't contain the port. So when doing the backend lookup, we need to strip the port off if it is included.
This fixes the "controller: resource not found" error that slipped through broken CI.
Closes #789.
/cc @bgentry @benburkert
=> router: Strip port from Host header when looking up route

router/http.go, router/http_test.go
Without this, some of our streaming clients would hang forever waiting for SSE events that would just hang out in the response body buffer. It may make sense to switch to an interval instead of flushing every write, but I want to get this in immediately, as it is breaking a bunch of stuff.
=> router: Flush HTTP response headers and body writes

controller/client/client.go, controller/jobs.go, controller/jobs_test.go, controller/utils/hijack.go, host/attach.go, pkg/cluster/attach.go, pkg/httpclient/json.go
The previous implementation was not compliant with the HTTP spec, and broke when the router was refactored. The new protocol dance looks like:
POST /attach
Connection: upgrade
Upgrade: flynn-attach/0
...
101 Switching Protocols
Connection: upgrade
Upgrade: flynn-attach/0
<attach frames>
=> all: Fix attach HTTP upgrade protocol

host/libvirt_lxc_backend.go
If we don’t do this, and there is an error, we’ll end up panicking later.
=> host: Check error from reading flannel config

test/test_host.go
This was failing intermittently, 15s should be enough.
=> test: Bump service timeout in TestNetworkedPersistentJob

host/host.go, host/http.go, host/sampi/http.go, pkg/shutdown/handler.go, test/runner/runner.go
Use of multiple handlers as written will result in the first one of them to finish exiting the whole process without waiting for other handler instances, which may result in incomplete cleanup.  There is now only one allowed handler instance.
=> shutdown handler should be a singleton.

discoverd/health/check_test.go
`CheckSuite.TestHTTPConnectRefused` is failing intermittently, this will log the actual error that is being received.
=> discoverd/health: Add more logging to tests

test/cluster/cluster.go
The command sometimes hangs in CI, so we want to be able to see the output when sending SIGQUIT.
=> test: Output stderr of `flynn-host ps` when dumping logs

controller/client/client.go, host/cli/cli.go, host/cli/upload-debug-info.go, host/host.go, pkg/cluster/client.go, pkg/exec/exec.go, pkg/httpclient/json.go, router/api_test.go, router/client/client.go, test/helper.go, test/test_scheduler.go
Primarily used for the way old discoverd managed service discovery.
Because of this simplification, we can now get rid of Close().
=> httpclient: Remove Dial and DialClose.

util/release/status.go
We are no longer using Travis, so the only commit status will be from Flynn CI.
=> util/release: Drop minimum commit statuses to one

discoverd/server/etcd_backend.go
Previously we were using the `ModifiedIndex` of the returned node, which is incorrect, as we can enter an infinite loop if that index is old. Instead we use the `EtcdIndex` which is the current index of the server and will be the most recent index.
=> discoverd: Use current etcd index for watch after full sync

discoverd/health/check_test.go
Small test fix for timeout seen several times (https://s3.amazonaws.com/flynn-ci-logs/20150126220052-213c7255-build-98a56e88f4541c015c91954c7438e3748ad9239f-2015-01-26-22-02-27.txt an example).
=> discoverd/health: Increase timeout in tests.

controller/types/types.go
This makes the JSON consistent with other controller resources
=> controller: Remove "_id" suffixes from deployment json

router/http.go, router/http_test.go
Add a test to make sure that hop-by-hop headers, such as `Connection`, are
removed before the request is proxied to the backend.
=> router: RFC7230-compatible Connection header handling, more tests for header behaviors

router/client/client.go
=> router/client: Get rid of HTTPError.

util/packer/ubuntu-14.04/template.json
The eu-central-1 region requires v4 signatures, which are unsupported by packer and its fork of goamz. Trying to copy to this region results in an AuthError and the release does not continue.
See https://github.com/mitchellh/packer/issues/1646 for the upstream issue tracking this.
=> util/packer: Don't attempt to copy AMI to eu-central-1

test/cluster/instance.go
Refs #753
This resolves a long-standing networking instability issue on CI. The default qemu NIC driver is apparently broken and was dropping/mangling packets right and left. This patch changes the NIC driver to virtio which is used by everybody and works correctly.
The problem and fix were extensively verified by running a program that exercised the network by making many connections and transferring many bytes.
Unfortunately this does not appear to resolve all of the intermittent CI failures, but it's a step forward.
=> test/cluster: Use virtio network interface

controller/resource_test.go
Creating another appHandler was used back when we reconfigured a few things
using the old discoverd version.
=> controller: Simplify resource testing.

test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/upgrade.sh
The default trusty kernel is 3.13, but the backported “LTS Enablement” package is already available and will be the default in 14.04.2
=> util/packer,test/rootfs: Install kernel 3.16.0

router/http.go, router/http_test.go
Rather than just pulling the forwarding port out of the input address,
determine it based off of the listener's actual address. This makes sure
that the value isn't 0, even in tests where that was previously the
case.
=> router: properly determine fwd port from listener

controller/deployer/main.go
If this is not set, it defaults to zero which will peg the CPU querying for jobs from postgres.
=> Set deployer worker interval

test/scripts/debug-info.sh
We’ve eliminated most of the network instability, so this output is not useful.
=> test/scripts: Disable network debug logging

test/test_cli.go
If these tests fail, it is useful to have the stderr output logged.
=> test: Add stderr logging to CLI log tests

controller/controller.go, pkg/httphelper/httphelper.go
Calling `json.Marshal` on `JSONError` instead of `*JSONError` causes the
detail field to be base64 encoded.
https://play.golang.org/p/xzPIPOrfoO
https://play.golang.org/p/55jQt2QD_e
=> httphelper: Fix marshalling of JSONError

router/http.go, router/http_test.go
As reported in #872, http.Transport will call Close() on any Request.Body after it encounters any error. We are retrying the same request under certain circumstances (dial errors in particular), so we need to keep the body open until we're done retrying.
Adds some test coverage for the error case reported in #872 by also testing `POST` requests with bodies, and fixes the underlying issue as well.
=> router: fix request retries with bodies

pkg/shutdown/handler.go
Just remove the remaining indirections of methods on the singleton struct.  Stack depth is now uniform again (the '3' offset for the log output is thus again correct).
=> Fix stack depth in shutdown log

router/http.go, router/http_test.go, router/proxy/reverseproxy.go, router/proxy/stream_conn.go, router/proxy/transport.go, router/tcp.go
The `router/proxy` package contains the (reverse)proxy functionality extracted from `router/http.go` & `router/tcp.go`. The package is broken up into two main types: `ReverseProxy` & `transporter`. They are broken up this way to keep features (like sticky-sessions) orthogonal to protocols (like HTTP & TCP) and out of `ReverseProxy`.
The `ReverseProxy` is a modified version of `httputil.ReverseProxy` from stdlib. There are a few changes to how it behaves internally that differ from the stdlib implementation. Additionally, support for generic TCP proxying has also been added via `ServeConn`. `ReverseProxy` is able to handle HTTP upgrades internally by using the same dialing logic as `ServeConn`. `transport` is based off `http.Transport` and implements the `http.RoundTripper` interface, but …
=> router: add proxy package

discoverd/server/dns.go, discoverd/server/dns_test.go
The race detector really doesn’t like us swapping out the recursors field, so make a new server for each recursion test.
Closes #882
=> discoverd/server: Fix race in DNS tests

test/test_scheduler.go
If we don't do this and need to dump the logs, they will not be dumped from the pending host.
=> test: Add instance to local state when adding new hosts

router/data_store.go
Without this patch, if/when etcd goes down it will fill up the logs with errors due to a tight retry loop.
=> router: Add wait between retries if connection to etcd fails

host/volume/zfs/zfs.go, host/volume/zfs/zpool.go, host/volume/zfs/zpool_test.go
ZFS volume providers should re-import file vdevs if already existing.
This makes it possible for the system to easily reassemble itself after a host reboot in which zfs has forgotten about the zpools based on file vdevs.
=> Zfs file vdev recovery

controller/app.go, controller/controller.go, controller/crud.go, controller/deployment.go, controller/formation.go, controller/jobs.go, controller/resource.go, pkg/ctxhelper/ctxhelper.go, pkg/httphelper/httphelper.go, pkg/httphelper/request_logger.go
Following the conventions outlined in the [context blog post](https://blog.golang.org/context#TOC_3.2.), I've moved to context getters and setters to a separate subpackage. This allows the context keys to be internal, unexported types, and provides users of the package with stronger type guarantees (since you can't set something on a context with a key whose type you can't access).
I also renamed the `Handle` type to `HandlerFunc` since it is analogous to `http.HandlerFunc`.
Finally, I introduced an `httphelper.Handler` type that is analogous to `http.Handler`.
I plan to use all this stuff to bring context into the router.
=> Clean up context-based Handler type, move context setters/getters to ctxhelper pkg

test/runner/runner.go
If we've uploaded the log, the local log file will not be available, but we can redirect to the copy on S3.
Closes #877
=> test/runner: Redirect local log requests to log URL

test/cluster/client/client.go, test/cluster/cluster.go, test/main.go, test/runner/assets/index.html, test/runner/runner.go, test/test_scheduler.go
Use `httprouter` in the test runner and create a client for making HTTP requests from the test builds.
This is an extraction of changes in #840, and that PR will be rebased on top of these changes once merged.
=> test: Improve cluster HTTP API

Godeps/Godeps.json, Godeps/_workspace/src/github.com/flynn/docker-utils/registry/registry.go, Tuprules.tup, bootstrap/Tupfile, bootstrap/manifest_template.json, host/Tupfile, host/cli/download.go, host/cli/update.go, host/host.go, host/http.go, host/manifest_template.json, pinkerton/context.go, pinkerton/registry/docker.go, pinkerton/registry/registry.go, pinkerton/registry/tuf.go, pkg/cluster/host.go, pkg/httpclient/json.go, pkg/sse/sse.go, pkg/tufutil/tufutil.go, script/release-packages, tup.config, util/release/Tupfile, util/release/export.go, util/release/main.go, util/release/manifest.go, util/release/version_template.json
Summary of changes:
* Modify manifest URIs to point at a TUF repo
* Modify `flynn-host download` to initialize the local TUF db using embedded root keys, download the version, host and bootstrap manifests from a TUF repo, and download all necessary images
* Add `flynn-host update` which updates the local TUF db then calls `PullImages` on each host in the cluster via HTTP, passing the updated TUF db in the request body (so that each host downloads the same images)
The root keys here are for a test repo at `https://s3.amazonaws.com/flynn-test/images` so will need changing before merging this into master.
An example download:
```
$ sudo flynn-host download \
--repository https://s3.amazonaws.com/flynn-test/images \
--tuf-db /tmp/tuf.db \
--manifest-dir /tmp
flynn/receiver …
```
=> Download images from a TUF repository

discoverd/health/check_test.go
gocheck doesn’t like assertions in goroutines.
Closes #900
=> discoverd/health: Fix race in check test

test/test_controller.go
There's no need to use the controller since we are using pkg/exec.
=> test: Remove unnecessary setup from TestExampleOutput

controller/examples/config.go
The previous default was to discard any messages, which will suppress errors.
=> controller/examples: Send log output to STDERR by default

Tuprules.tup, pkg/pprof/nopprof.go, pkg/pprof/pprof.go, router/api.go, router/server.go
Profiling the router with the `net/http/pprof` handler is useful for debugging the router, but it has a lot of baggage. Pulling in the `runtime/pprof` dependency should not be done by default. This adds a `pkg/pprof` package that only pulls in the `runtime/pprof`/`net/http/pprof` packages when the `pprof` build tag is set (`go build -tags=pprof`).
=> router: enable pprof handler via build flag

controller/examples/examples.go
Run the provider_create example first so that discoverd has lots of time to propagate our address.
Closes #869
=> controller/examples: Avoid discoverd race

flannel/build.sh, host/libvirt_lxc_backend.go
The combination of these two fixes should prevent the panic in #905.
Flannel patch: https://github.com/flynn/flannel/commit/04ff05d566d705715882b20a566be6113ca50679
=> Flannel fixes

host/libvirt_lxc_backend.go, test/test_host.go
Instead of only looking up the containerinit client when we need it, always look it up, and only error when we need it. This allows us to get retrieve the exit status in cases where stdin is provided and the job is not in TTY mode.
Closes #810
Closes #626
=> host: Fix exit status attach return with no stdin

controller/testutils/fake_host_client.go, host/cli/update.go, host/http.go, host/libvirt_lxc_backend.go, pinkerton/context.go, pinkerton/layer/layer.go, pkg/cluster/host.go
This is so that components don't need to import pinkerton, which introduces a dependency on libdevmapper.
=> pinkerton: Move LayerPullInfo into package

host/host.go, host/manifest.go, host/manifest_template.json, host/volume/manager.go
Create persistent volumes when evaluating manifests.  Add simple name->volume mapping so if the manifest is run again, services get the same volumes again if were created previously.
Using etcd appliance as canary.
Once this and other `volume.Manager` state is persisted via boltdb, this will allow etcd appliances to keep their disk state across flynn-host daemon reboots.
=> Manifests and named volumes

discoverd/server/etcd_backend_test.go, discoverd/server/http_test.go, discoverd/server/state_test.go
Instead of booting a new server, we can just use a different prefix for each test case.
This shaves ~20s off of the test runtime.
=> discoverd/server: Run a single etcd server for all tests

discoverd/client/client.go, discoverd/client/instance.go, discoverd/server/backend.go, discoverd/server/etcd_backend.go, discoverd/server/etcd_backend_test.go, discoverd/server/http.go, discoverd/server/http_test.go, discoverd/server/state.go, discoverd/server/state_test.go, pkg/httphelper/httphelper.go
Service metadata provides events, read access, and consistent CAS writes for metadata associated with a service. This metadata may be used to store service-level information such as credentials, configuration, and state machine fields.
The first usecase for service metadata is the state machine for the new PostgreSQL appliance.
=> discoverd service metadata

util/packer/ubuntu-14.04/scripts/upgrade.sh
These will typically fail to install when we install the latest kernel, and we install the latest version of the additions later.
=> util/packer: Remove pre-installed guest additions

pinkerton/registry/docker.go, pinkerton/registry/image.go, pinkerton/registry/registry.go, pinkerton/registry/tuf.go
Previously the ancestor layers would not have ParentID set because we did not fetch the layer JSON, so the layer would not get the correct JSON when extracted into the graph driver.
Incremental patch for #617.
=> pinkerton: Fix fetching image ancestors

host/host.go, host/http.go, host/libvirt_lxc_backend.go, host/manifest.go, host/volume/api/http.go, host/volume/backend.go, host/volume/manager/manager.go
Upcoming changes were running aground on import cycles: the manager needs to refer into the provider implementation packages as it gains responsibility for initializing them during restores from prior state; and the providers of course need to refer to the volume basic types.
The new import graph is host|api -> manager -> {providers} -> volume.
=> split volume manager into separate package

blobstore/blobstore_test.go, controller/controller_test.go, host/volume/zfs/zfs_basics_test.go, host/volume/zfs/zpool_test.go, pkg/testutils/checkers.go, pkg/testutils/postgres/utils.go, pkg/testutils/utils.go
Gather test utils.
Shuffle some postgres stuff; the general package needn't carry pg references.
(This is triggered by more import cycle avoidance for volume persistence work.)
=> gather test utils together

cli/main.go
`shutdown.Fatal`'s behavior is to format output as a log line, which isn't relevant here.  Replace it with a plain log statement and explicit exit code.
Fixes #938.
=> cli: Output flag parse errors plainly.

pkg/ctxhelper/ctxhelper.go, router/http.go, router/proxy/reverseproxy.go, router/proxy/transport.go
This includes everything from #926 except for the CloseNotify stuff (which became an issue due to conflicts w/ Hijack).
Introduce contexts into the router stack. Use them to carry request metadata (currently just start time) down the stack.
Also, add a 120 second timeout for response headers from backends. There's no test for this yet, and I'm not sure if/how I should add one. Perhaps we could just test that the value is indeed set on the `httpTransport` since we can already trust that to use the setting correctly?
=> router: context

router/proxy/close_notify.go, router/proxy/reverseproxy.go, router/proxy/reverseproxy_test.go, router/proxy/transport.go, router/tcp.go
Wrap downstream TCP connections in a net.Conn that implements CloseNotify so that early termination can be detected before dialing a backend.
I'm not sure how to write a test for this, any ideas?
=> router: detect early termination of downstream TCP connections

dashboard/app/lib/javascripts/dashboard/stores/app.js
Releases no longer require an artifact as of 6be3d4376bb4d2405b622f9b7f2444cd4c0743de and the artifact being created here is not used.
=> dashboard: Don't create release artifact when deploying

website/source/docs/installation.html.md
Hello,
I've made 2 changes:
- Use `sudo` in the commands and make their presentation consistent with other commands (which assume the running user is unprivileged)
- Remove the 'assume yes'  from `apt-get install` flag for consistency
I'm happy to spit/remove one of the changes if necessary.
Thanks,
Jay
=> Modify ZFS installation instructions to keep them consistent

host/cli/destroy-volumes.go, host/host.go, host/volume/backend.go, host/volume/manager/manager.go, host/volume/zfs/zfs.go
Adds a command to `flynn-host` which destroys volumes and their configuration in an attempt to return the host to a clean state for a future run.
=> Flynn host cli volume-destroy command

bootstrap/manifest_template.json, controller/deployer/main.go, controller/deployer/strategies/all-at-once.go, controller/deployer/strategies/main.go, controller/deployer/strategies/one-by-one.go, controller/deployment.go, test/test_deployer.go
The main change here is to make the deployer log more verbosely, as currently it only really logs on error. I also made the log messages more consistent by always using lower case, and starting error messages with the word "error" to make the logs easier to scan down.
=> Deployer updates

discoverd/server/dns.go, discoverd/server/dns_test.go
Before this patch, passing a bare IPv6 address with no port resulted in the error "too many colons in address". If we get this error, we should treat it as an IPv6 address with no port.
=> discoverd: Handle bare IPv6 upstream resolver addresses

host/libvirt_lxc_backend.go, host/manifest.go
Allocate IP addresses on job restore. Setup networking on restarts.
IPs from running containers should be marked as used. Log any errors in doing so. Additionally, ConfigureNetworking needs to be ran regardless of whether flannel was already running or not.
Note that for this functionality to work correctly, --force should not be set on flynn-host, as that will run Cleanup() before starting it, destroying all of the old containers.
Closes #60.
=> host: Allocate IP addresses on job restore.

util/packer/ubuntu-14.04/scripts/install.sh, util/packer/ubuntu-14.04/scripts/upgrade.sh
The default daily crontab has a bunch of apt/dpkg commands and runs at ~06:00 which can coincide with releases and one-off builds. This will cause lock errors, as only one command at a time can manipulate the dpkg/apt databases.
This should resolve the intermittent errors during releases like this:
Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
=> util/packer: Disable cron before starting work

controller/deployer/strategies/main.go, controller/scheduler/main.go, controller/schema.go, test/test_deployer.go, website/schema/controller/job.json
A crashed job means the job exited non-zero, but was running at some point, so the only case when a deployment will receive a crashed event is when scaling down an old formation, in which case it doesn't matter that the job crashed as we want it to be down anyway.
=> deployer: Only rollback if jobs fail to start

script/bootstrap-flynn, script/install-flynn.tmpl, script/kill-flynn, script/release-flynn, script/run-integration-tests
Missing a flag like `script/run-integration-tests DeployerSuite` is ignored and runs all the tests (it should be `script/run-integration-tests -f DeployerSuite`).
=> script: Print usage when too many arguments given

router/data_store.go, router/http.go, router/tcp.go
Switch to a single, synchronous `Sync` method for `DataStore`. This is part of the work to address #1002, but doesn't include the fix.
=> router: datastore sync

script/generate-examples
This was broken by the change in URL format added during the TUF
transition.
=> script: Fix image URL used by example generator

controller/deployer/main.go
This fixes a race where consumers of the events assume the deployment rollback has completed when receiving a failed event (for example `DeployerSuite.TestRollback`).
Fixes #1012.
=> deployer: Only send failed event after rolling back

controller/jobs.go, controller/scheduler/main.go, controller/schema.go
This is so that the down event of the scheduler leader is forwarded to the controller by the non-leaders (previously they would miss the event as only the leader watched for events).
This also ensures that deploying a scheduler will wait for the new scheduler to be watching host events before killing old schedulers.
=> scheduler: Make all schedulers watch events

test/cluster/cluster.go
The scratch image can no longer be pulled (see https://github.com/docker/docker/issues/10737).
This was originally added as building many images at once in CI was failing with a claim that the scratch image did not exist. Given it is no longer an image which gets downloaded, there is no need to pull it.
=> test: Don't pull the scratch Docker image

dashboard/app/lib/javascripts/dashboard/views/install-cert.js.jsx, pkg/certgen/certgen.go
Make it clearer what is happening and point out that the CA certificate is ephemeral.
=> dashboard: Improve CA certificate installation flow

dashboard/app/lib/javascripts/dashboard/views/app-routes.js.jsx
Properties previously found in `config` are now in the root object
refs 4ebafaa3078786fb6561b5ca61a541ca57e0442f
refs #1030
=> dashboard: Use new route JSON structure

dashboard/app/lib/javascripts/dashboard/stores/job-output.js
Remove unused assignment which causes an error in Chrome/Safari
refs 985209b6041bf0076a6294f5e5f09c3c54b35e7c
closes #1030
=> dashboard: Fix log output in Chrome/Safari

test/rootfs/build.sh, test/rootfs/setup.sh
Some daemons were starting in the chroot (e.g. upstart-udev-bridge, docker, rsyslogd) and preventing unmounting the rootfs.img.
The `initctl` + `policy-rc.d` hacks were good enough for most daemons, but for some reason `docker` was managing to circumvent that, so `jchroot` is needed so that `docker` gets killed by the kernel when the PID namespace goes away.
Fixes #1026.
=> test: Don't start daemons when building the rootfs

website/source/docs/development.html.md
It makes more sense directly after the testing section.
=> website: Move pull request section of development doc

host/volume/backend.go, host/volume/manager/manager.go, host/volume/manager/persistence_test.go, host/volume/util.go, host/volume/volume.go, host/volume/zfs/zfs.go, host/volume/zfs/zfs_snapshots_test.go, host/volume/zfs/zfs_test.go
Added permanent snapshots.  Snapshot mounts are readonly, but otherwise act mostly like other volumes.  Snapshots can be forked again into live filesystems.
Snapshots can now be serialized and transmitted to other matching providers (once connected to the http API, this will make snapshot transfer possible between hosts).  The provider interface supports negotiation for existing data objects so that transmission can use incremental deltas when possible.
=> Volume snapshots

host/attach.go, host/backend.go, host/cli/log.go, host/cli/upload-debug-info.go, host/containerinit/init.go, host/libvirt_lxc_backend.go, host/types/types.go, pkg/cluster/attach.go, test/cluster/cluster.go
In order to debug #907, it would be useful to know what is happening internally in containerinit, and exposing logs is a start at that.
My first aim was to redirect the console of the containers to a file, but that is not supported ([the console must be a PTY](http://libvirt.org/git/?p=libvirt.git;a=blob;f=src/lxc/lxc_process.c;h=f1b36f1;hb=7212990#l1060)), and the consoles can't be connected after a container has exited to get the log, so instead I have exposed the logs via RPC and used logbuf to pipe them to a file.
Ideally I would like to call something like `flynn-host log --init ID` to see these logs but would like to get feedback on how that can be achieved? A new flag for attach to return the init logs?
=> Expose containerinit logs

pkg/sse/sse.go
`writer.Write` also tries to lock the mutex, so `writer.Error` was previously causing a deadlock.
=> pkg/sse: Fix writer.Error

bootstrap/manifest_template.json, controller/app.go, controller/client/client.go, controller/controller_test.go, controller/formation.go, controller/schema.go, controller/types/types.go, dashboard/app/lib/javascripts/dashboard/routers/apps.js, dashboard/app/lib/javascripts/dashboard/stores/app.js, dashboard/app/lib/javascripts/dashboard/stores/apps.js, dashboard/app/lib/javascripts/dashboard/views/app.js.jsx, dashboard/app/lib/javascripts/dashboard/views/apps-list.js.jsx
This changes the concept of a "protected" app to a "system" app, and lifts the restriction that such apps cannot be scaled to zero (so that they can be deployed).
@jvatic this requires a change to the dashboard, could you push a change to this PR?
=> Replace App.Protected with app metadata

appliance/postgresql2/postgres.go, appliance/postgresql2/postgres_test.go
This is a concrete implementation of `state.Postgres` that configures/manages a Postgres daemon based on requests from the state machine. The unit tests cover all normal functionality, for expediency of shipping there are error cases that are not currently covered.
=> appliance/postgresql: Implement postgres daemon manager

Godeps/Godeps.json, Godeps/_workspace/src/github.com/kylelemons/godebug/diff/diff.go, Godeps/_workspace/src/github.com/kylelemons/godebug/diff/diff_test.go, Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/.gitignore, Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/doc.go, Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/examples_test.go, Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/public.go, Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/public_test.go, Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/reflect.go, Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/reflect_test.go, Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/structure.go, Godeps/_workspace/src/github.com/kylelemons/godebug/pretty/structure_test.go, appliance/postgresql2/.gitignore, appliance/postgresql2/cmd/simcli/main.go, appliance/postgresql2/postgres.go, appliance/postgresql2/postgres_test.go, appliance/postgresql2/simulator/simulator.go, appliance/postgresql2/state/state.go, appliance/postgresql2/state/state_test.go, appliance/postgresql2/xlog/xlog.go, pkg/iotool/safewriter.go
First, I'd like to apologize for the size of this. You're not reading the diff wrong, there are indeed over 4k lines of new code here. Most of that is the tests and the simulator supporting the tests, the state machine itself weighs in at 1k lines. I couldn't come up with an incremental way to deliver this, as it is a direct translation that doesn't make much sense in a partial state.
---
This adds a Go translation of the [manatee-state-machine project](https://github.com/joyent/manatee-state-machine/tree/d441fe941faddb51d6e6237d792dd4d7fae64cc6) from Joyent. It is translated verbatim with the following minor differences:
- A few extra tests were added for completeness
- Changes were made to translate from the Node.js async model to a more
straightforward single-threaded model that uses …
=> postgres appliance state machine

host/upstart.conf
It is currently unlikely that respawning flynn-host will fix anything, it usually results in the daemon continuously flapping and filling up the logs.
=> host: Don't respawn in upstart.conf

appliance/etcd/build.sh
https://github.com/coreos/etcd/compare/v2.0.0...v2.0.3
=> appliance/etcd: Bump etcd to v2.0.3

logaggregator/main.go, logaggregator/main_test.go, logaggregator/rfc5424/rfc5424.go, logaggregator/ring/ring.go, logaggregator/ring/ring_test.go
This is my first batch of progress on a log aggregator component. This component takes syslog-over-TCP input (RFC 6587 / RFC 5424), parses the messages, and buckets the logs into individual buffers based on the `AppName` field in the syslog header.
Buffers currently have a fixed size of 10,000 log messages. I think I'd like to change this to be configurable and maybe make it work based on the number of bytes in the buffered messages, rather than be based on the count of the messages. It would probably be good if all buffers weren't pre-allocated with a slice of capacity 10,000.
Logs will be sent to this aggregator by the “collectors” running on each instance, a component that @benburkert is working on.
The log aggregator will provide an API that the controller will use to fetch logs out …
=> logging: Add a log aggregator component

discoverd/client/client.go, discoverd/client/heartbeat.go, discoverd/server/backend.go, discoverd/server/dns_test.go, discoverd/server/etcd_backend.go, discoverd/server/etcd_backend_test.go, discoverd/server/http.go, discoverd/server/http_test.go, discoverd/server/state.go, discoverd/server/state_test.go, host/containerinit/init.go
This patch adds support for creating services with a configuration that selects a leader election type. It also adds a manual leader election type that can be used instead of the default oldest instance election.
Manual leader election is useful if an external state machine is responsible for choosing the leader, but the discoverd API (DNS and HTTP) should be kept in sync. The first use case for this is the postgres appliance state machine (#986) which takes into account more than the instance age when doing leader election.
=> discoverd: Implement manual leader election

test/cluster/client/client.go, test/cluster/cluster.go, test/cluster/instance.go, test/rootfs/setup.sh, test/runner/runner.go
Putting the auth key in the URL gets leaked in the test logs because the run script is executed with trace on.
=> test: Use Basic Auth with cluster API

slugbuilder/Dockerfile, slugbuilder/builder/build.sh, slugbuilder/builder/install-buildpack
Signed-off-by: Nathaniel Eliot <nathaniel.eliot@bazaarvoice.com>
=> slugbuilder: Fix buildpack ordering (to explicit ordering set in buildpacks.txt)

cli/cluster.go, cli/config/config.go, cli/main.go, test/cluster/cluster.go, test/test_cli.go
=> Cli multiple clusters

gitreceived/gitreceived.go, pkg/archiver/archiver.go, test/test_gitreceive.go
Allows us to consistently cache repos across different gitreceived instances. Fixes #212
=> gitreceived: Cache repos in blobstore.

appliance/postgresql/discoverd.go, appliance/postgresql/start.sh, bootstrap/add_app_action.go, bootstrap/bootstrap.go, bootstrap/deploy_app_action.go, bootstrap/manifest_template.json, bootstrap/run_app_action.go, bootstrap/scale_app_action.go, docs/content/installation.html.md, test/test_deployer.go, test/test_scheduler.go
This changes bootstrap to detect whether it should run in singleton mode by first checking the `SINGLETON` environment variable and if not set, checking if the number of expected nodes is 1.
If singleton mode is not enabled, enough instances of each process are run to make the control plane tolerate the loss of a node without having to start new instances.
=> Run HA clusters

test/test_deployer.go, test/test_scheduler.go
This allows `DeployerSuite` to run concurrently.
=> test: Move TestDeployController into SchedulerSuite

appliance/postgresql/postgres.go, appliance/postgresql/postgres_test.go
We need to scan into a string, otherwise we’ll get an error.
Also added tests for both paths through the method.
=> appliance/postgresql: Fix xlog position scan

discoverd/client/client.go
Before this the fields were capitalized in the JSON, which doesn’t match our conventions.
=> discoverd: Add json tags to ServiceMeta

pkg/syslog/rfc5424/parser.go, pkg/syslog/rfc5424/parser_test.go
The syslog message parser was including an extra space at the beginning of the message byte slice. It was `panic`ing when the syslog message did not contain a `MSG` field, in which case there is `SP` after `STRUCTURED-DATA`. For fields containing a nil value ('-'), the header member is set to nil instead of `[]byte{'-'}`.
/cc @bgentry
=> logging: fix syslog parser

discoverd/client/heartbeat.go
This allows us to read the generated metadata from an Instance after registering it.
=> discoverd/client: Expose automatic metadata to register caller

test/cluster/cluster.go, test/main.go, test/runner/runner.go
Reverts flynn/flynn#1110
This change is being reverted due to `AddHosts` not working (new hosts do not get any flynn-host peers). The patch needs re-thinking.
=> Revert "test: Support booting multiple clusters"

script/bootstrap-flynn
I was getting strange errors in postgres tests and I realised it was because service meta was persisting between test runs. I don't think there is any benefit in doing that.
=> script: Destroy volumes before running integration tests

test/cluster/cluster.go, test/main.go, test/runner/runner.go
This is similar to #1110 but updated so that `AddHosts` adds hosts to the default cluster.
=> test: Support booting multiple clusters

cli/main.go, controller/client/client.go, controller/controller.go, controller/deployer/main.go, controller/types/types.go, host/cli/update.go, pinkerton/context.go, pinkerton/layer/layer.go, pkg/httpclient/json.go, pkg/pinned/pinned.go, test/cluster/client/client.go, test/helper.go, test/test_release.go, updater/.gitignore, updater/Dockerfile, updater/Tupfile, updater/updater.go, util/release/version_template.json
This will deploy all system apps (except for `postgres`) in a specific order, then will deploy all other apps which use the slugrunner image.
=> Deploy apps when running `flynn-host update`

util/cedarish/Dockerfile
Reverts flynn/flynn#1129
We need to keep the `cedarish` image inline with Heroku's `cedar-14` image.
=> Revert "Added the FreeTDS library to the default cedarish image."

appliance/postgresql/Dockerfile, appliance/postgresql/api/server.go, appliance/postgresql/main.go, bootstrap/manifest_template.json, cli/env.go, cli/main.go, cli/psql.go, cli/run.go, controller/jobs.go, controller/jobs_test.go, controller/types/types.go, dashboard/app/lib/javascripts/dashboard/stores/app.js, pkg/httpclient/json.go, schema/controller/common.json, schema/controller/new_job.json, schema/controller/process_type.json, test/test_postgres.go, test/test_taffy_deploy.go
This adds a new `flynn psql` command that opens a console to the Flynn Postgres database configured for the application.
It retrieves the postgres details from the app’s current release and then uses the release from the referenced postgres service for a one-off job that runs the psql command.
I also added a few bug fixes while implementing this and a commit that adds plv8 and postgis as they are the only extensions we didn't have installed that are supported on Heroku Postgres.
=> Add `flynn psql`

test/test_release.go, updater/types/types.go, updater/updater.go
Although taffy does not have any processes, it needs to be deployed so that it's release uses the latest image.
=> updater: Deploy taffy as part of the update process

cli/scale.go, test/test_cli.go
If a process type is not specified when running `flynn scale foo=2` it should not touch it, otherwise we need to specify every process type for every scale action.
Closes #1140
=> cli: Don't scale unspecified types

bootstrap/manifest_template.json
This gets us TLS for default routes out of the box if the CA certificate is installed via the dashboard. It also changes the behavior when there is no valid TLS certificate for a route to serving the wildcard, which will result in an untrusted certificate warning, instead of just closing the connection which causes cryptic errors in clients.
=> bootstrap: Use cluster domain wildcard cert as router fallback

cli/psql.go, test/test_postgres.go
This makes it easier to get machine-readable results out of psql, so that it can be used in shell pipelines, etc.
=> cli: Allow arbitrary arguments to psql

bootstrap/manifest_template.json, controller/app.go, controller/client/client.go, controller/controller.go, controller/controller_test.go, controller/examples/examples.go, controller/log_test.go, docs/api-examples/controller.json, logaggregator/api.go, logaggregator/api_test.go, logaggregator/client/client.go, logaggregator/main.go, logaggregator/main_test.go, schema/controller/app.json, schema/examples/controller/app_log.json
This adds an API to the logaggregator, as well as a Client for that API. It also adds a controller action to be able to access that API and return logs to external clients, and attempts to add JSON schema for that action.
Currently, I'm somewhat mimicking the output of Heroku's log tails:
```
2009-11-10T23:00:00.123450Z app[web.12345]: testing message
```
That's what is actually returned by the logaggregator API as of now. It's nice that it's concise, but it loses a lot of metadata that might be important to be able to get from places like the controller. For example, the hostname and stream ID (as encoded in the syslog message's `SEVERITY` field) are both lost before the controller gets ahold of the messages. That means the controller can't currently do things like return SSE events that …
=> log aggregation: Log aggregator API, controller actions, and associated clients

appliance/postgresql/Dockerfile, cli/psql.go
`psql` uses `more` by default, most distros/people use `less`. This patch adds environment variables that configure `psql` to use `less` for paging along with some basic, sane `less` configuration defaults.
=> Use less for psql paging

test/cluster/cluster.go
CI is intermittently hanging indefinitely running `go test`. We need to investigate why, but we should also not allow the test to hang indefinitely.
=> test: Timeout the unit tests after 5 minutes

cli/install.go
Instead of spaces, double-hyphen args need to be set with equal signs:
```
-n <instances>,     --instances=<instances>            Number of instances to launch [default: 1]
-t <instance-type>, --type=<instance-type>             Type of instances to launch [default: %s]
--aws-access-key-id=<key-id>       AWS access key ID. Defaults to $AWS_ACCESS_KEY_ID
--aws-secret-access-key=<secret>   AWS access key secret. Defaults to $AWS_SECRET_ACCESS_KEY
--aws-region=<region>              AWS region [default: us-east-1]
```
=> Updated flynn install cmd line usage

controller/client/client.go
There is a chance that service discovery could return an address of a controller and that instance subsequently goes down, meaning when a HTTP request is actually made, there will be an i/o timeout.
Previously the client would use a connect timeout of 30s (set by `http.DefaultTransport`) which is too long to wait in this case.
This change lowers the connect timeout to 1s, and retries dialling the controller multiple times if an error occurs, giving up after 30s.
=> controller: Retry requests after dial errors

test/cluster/cluster.go
This will make it easier to debug issues when things timeout.
=> test: Add timestamps to cluster log messages

appliance/postgresql/postgres.go
There are some scenarios where this can be the case, and it isn't an error. See https://smartos.org/bugview/MANATEE-263 for details.
This most likely happens when postgres is setting up replication and trying to figure out exactly what it has most recently sent to the remote peer.
Upstream change: https://github.com/joyent/manatee/commit/fb8d0f788000cdc24be5eb7b43a286c19f38fb69
=> appliance/postgresql: Don't error if sync xlog is greater than primary

bootstrap/manifest_template.json, bootstrap/run_app_action.go, controller/scheduler/main.go, controller/types/types.go, controller/utils/utils.go, discoverd/server/etcd_backend_test.go, discoverd/server/state.go, discoverd/server/state_test.go, host/backend.go, host/host.go, host/libvirt_lxc_backend.go, host/manifest.go, host/manifest_template.json, host/state.go, host/state_test.go, host/types/types.go, host/volume/manager/manager.go, host/volume/manager/persistence_test.go, script/bootstrap-flynn
This implements support for full-cluster restarts (both due to hard crashes and clean shutdowns). See the individual commit messages for implementation details. A few bugs found in discoverd and flynn-host were fixed along the way. Named volumes were removed as they are only usable from layer 0 bootstrap.
Closes #235.
Implements resurrection as described in #1170.
Makes #1168 a non-issue, as legacy volumes are no longer used. Legacy volumes will be removed in a future PR.
=> Cluster resurrection

host/upstart.conf
The upstart job saves the state database in `/tmp`, which will not persist between reboots. Since the default is in `/var/lib/flynn` we can just remove the flag to fix this.
Refs #235.
=> host: Don't save state database in /tmp

test/cluster/cluster.go, test/scripts/wait-for-docker, test/test_release.go
Tests were intermittently failing in CI with:
`dial unix /var/run/docker.sock: no such file or directory`
Closes #1102 
Closes #1104
=> test: Wait for Docker to start before using it

test/scripts/wait-for-docker
The timeout was hit in CI (see [here](https://s3.amazonaws.com/flynn-ci-logs/20150308031603-ad79e92d-build-5305600de6dc5095280db6a4fda22d304f20adf3-2015-03-08-03-19-38.txt)), which indicates Docker is failing to start, rather than just being slow to start.
=> test: Dump the Docker log if it doesn't come up

router/http.go, router/server.go, router/setup_test.go, router/tcp.go
Binding to :0 and specifying the SO_REUSEPORT flag are mutually incompatible, as the kernel may pick a port that is already in use.
Closes #893
Closes #822
=> router: Don't use SO_REUSEPORT in test suite

appliance/postgresql/client/client.go, appliance/postgresql/http.go, appliance/postgresql/main.go, appliance/postgresql/postgres.go, appliance/postgresql/state/state.go
This adds an HTTP API and `/status` endpoint to the postgres instance manager. The first use for the endpoint is waiting for the upstream server to come up before pulling a base backup.
=> Add status endpoint to postgres, use it to wait for upstream

discoverd/health/register_test.go
I don't understand the code well enough to know *why* this is sometimes nil, but I think it's a scheduling race with one of the empty calls.
This guard prevents an occasional deadlock.
Closes #1203
=> discoverd/health: Avoid deadlock in register test

appliance/postgresql/main.go, bootstrap/bootstrap.go, controller/controller.go, controller/deployment.go, controller/deployment_test.go, controller/testutils/fake_host_client.go, discoverd/client/client.go, discoverd/client/heartbeat.go, discoverd/server/etcd_backend.go, discoverd/server/etcd_backend_test.go, discoverd/server/http.go, discoverd/server/http_test.go, host/containerinit/init.go, host/http.go, host/volume/api/http.go, pkg/cluster/host.go, pkg/httphelper/httphelper.go, test/test_host.go
Signalling a job can be achieved via the attach protocol but only when also requesting logs.
Sending a signal without requesting logs currently fails as the remote end hangs up the connection, but in this case establishing an attach connection is overkill, so I've added a simpler host API method.
I also refactored `pkg/httphelper` along the way.
Fixes #1196.
=> host,pkg/cluster: Add SignalJob

host/cli/upload-debug-info.go
=> host/cli: Don't print error if logs do not exist

host/cli/gist.go, host/cli/upload-debug-info.go
Sample output (has colour in the terminal):
```
INFO[03-11|16:48:56] uploading logs and debug information to a private, anonymous gist 
INFO[03-11|16:48:56] this may take a while depending on the size of your logs 
INFO[03-11|16:48:56] getting flynn-host logs 
EROR[03-11|16:48:56] error getting flynn-host log "/var/log/upstart/flynn-host.log" err="open /var/log/upstart/flynn-host.log: no such file or directory"
INFO[03-11|16:48:56] getting job logs 
INFO[03-11|16:48:56] getting system information 
INFO[03-11|16:48:57] creating anonymous gist 
223.56 KB / 223.56 KB [===========================================================================================================] 100.00 % 51.57 KB/s 4s
INFO[03-11|16:49:01] debug information uploaded to: …
```
=> host/cli: Be more verbose in upload-debug-info

docs/content/development.html.md, host/cli/cli.go, host/cli/collect-debug-info.go, host/cli/gist.go, host/host.go
This is useful if the logs are too big for a gist, or if the gist service is unavailable.
Closes #401.
=> host/cli: Optionally create tarball in upload-debug-info

test/runner/assets/builds.js, test/runner/assets/index.html, test/runner/assets/style.css, test/runner/runner.go
We are getting a lot of failures in CI and it would be useful if some were marked as either expected (e.g. an expected error which happens locally) or linked to an existing failure via a GitHub issue.
Unexplained failures have a link:
Clicking the link shows a modal:
Marking a failure as expected shows an "expected" label, and assigning an issue shows a button linking to the issue:
=> test: Support assigning failed builds to GitHub issues

installer/stack_template.go
This is to make it easier to identify flynn generated resources while browsing the aws web console.
Open to suggestions on the exact naming scheme, currently we just Name tag most (relevant, browsable in the ui) items with the generated cloud-formation stack name.
Tested manually, there didn't seem to be unit tests for the template specifically the existing codebase.
=> installer: add Name tags to aws resources

bootstrap/run_app_action.go, controller/scheduler/main.go, controller/utils/utils.go
Outside of flynn-host, job IDs must contain the host ID so that operations like attaching to the job know which host to dial.
=> controller: Include host ID in job env FLYNN_JOB_ID

host/host.go, host/libvirt_lxc_backend.go, host/logmux/logmux.go, host/logmux/logmux_test.go, host/logmux/service_conn.go, host/logmux/service_conn_test.go, pkg/syslog/rfc5424/message.go
Send container output on STDOUT, STDERR, and containerinit to the logaggregator service over TCP as rfc5424 encoded syslog messages.
=> logging: send container stdout/stderr to logaggregator service

script/install-flynn.tmpl
ubuntu-zfs does not depend on linux-headers, but it needs the headers to compile the kernel modules, giving the following warning when absent:
```
Module build for the currently running kernel was skipped since the
kernel source for this kernel does not seem to be installed.
```
so install them explicitly first to ensure they are present when building the kernel modules.
Fixes #1231.
=> script: Install linux-headers package before ubuntu-zfs

controller/jobs.go, controller/jobs_test.go
This logic was broken in https://github.com/flynn/flynn/commit/bc37712.
=> controller: Fix ignoring job event uniqueness errors

appliance/etcd/build.sh
https://github.com/coreos/etcd/compare/v2.0.3...v2.0.5
This may fix i/o timeout errors: https://github.com/coreos/etcd/issues/2338
=> appliance/etcd: Bump to v2.0.5

test/cluster/cluster.go
=> test: Manually kill containers after stopping flynn-host

Godeps/Godeps.json, Godeps/_workspace/src/github.com/flynn/go-tuf/client/remote_store.go, Godeps/_workspace/src/github.com/flynn/go-tuf/data/types.go, cli/.gitignore, cli/Tupfile.lua, cli/dev.go, cli/main.go, cli/tuf.go.tmpl, cli/update.go, cli/version.go, host/cli/download.go, host/cli/update.go, pinkerton/context.go, pkg/version/version.go, script/export-components, test/test_release.go
This removes the old distribution toolchain inherited from hk and replaces it with an updater that uses TUF. The same TUF repo that is used to distribute the rest of the container images and binaries is used.
`script/export-components` is updated to add the cross-compiled flynn CLI binaries to the repo tagged with their version. The CLI will be released and versioned as part of the nightly build process instead of using a separate version tag and build system.
Closes #1087 
**TODO**
=> CLI updates with TUF

cli/release.go
Image URIs must contain a `name` parameter.
=> cli: Fix example image URI

test/test_git_deploy.go
The receiver already adds a `web=1` formation, so the scale command after the push always exits with `requested scale equals current scale, nothing to do!`.
=> test: Remove unnecessary scale after git push

test/test_host.go
The job started by `TestAttachFinishedInteractiveJob` hung in the following CI failure:
https://ci.flynn.io/builds/20150314222600-99faafa7
```
goroutine 135 [chan receive, 19 minutes]:
github.com/flynn/flynn/pkg/exec.(*Cmd).Wait(0xc2080fa000, 0x0, 0x0)
/home/ubuntu/go/src/github.com/flynn/flynn/pkg/exec/exec.go:286 +0x265
github.com/flynn/flynn/pkg/exec.(*Cmd).Run(0xc2080fa000, 0x0, 0x0)
/home/ubuntu/go/src/github.com/flynn/flynn/pkg/exec/exec.go:315 +0x71
main.(*HostSuite).TestAttachFinishedInteractiveJob(0xc20802e660, 0xc208358960)
/home/ubuntu/go/src/github.com/flynn/flynn/test/test_host.go:45 +0x28c
```
=> test: Wrap interactive job in timeout

cli/README.md, docs/content/installation.html.md, test/README.md
The `cli.flynn.io` server is deprecated and will serve one last update, the first release of the CLI with the TUF updater. A new redirect endpoint is provisioned at `https://dl.flynn.io/cli` that serves the same function and reads from the TUF repo.
Refs #1250
=> all: Use new redirect endpoint for CLI download

docs/content/installation.html.md
The name of the provider was removed with the CLI interface.
=> docs: Fix `flynn install` doc

test/test_git_deploy.go
`TestGoBuildpack` started failing intermittently, and I think it is related to the fact that the inital release crashes. This change is not critical so I am reverting and will open an issue to investigate any issues with deploying a crashed release.
Reverts flynn/flynn#1261.
=> Revert "test: Remove unnecessary scale after git push"

test/test_release.go
Otherwise the goroutine sticks around for no reason.
=> test: Defer pipe close in TestReleaseImages

slugrunner/runner/init, test/test_git_deploy.go
This fixes running commands with simple quoting and spaces like:
flynn run bash -c "echo 'foo bar'"
I have not tested more advanced cases, as I suspect that this is good enough for the majority of use cases (even this does much quoting does not work on Heroku).
The leading space in the `printf` format string is necessary for some unknown reason that I didn't track down.
The test is in the git deploy suite because it requires an SSH key to be set up and we don't use git anywhere else in the test suite.
Closes #656
=> slugrunner: Fix command quoting

host/host.go, logaggregator/client/client.go, logaggregator/main.go
The logaggregator server listens on two ports, but only registers a single discoverd service for the syslog port. The api port should be inferred by the client.
=> logaggregator: register one discoverd service

cli/Tupfile.lua, installer/installer.go, util/release/amis.go, util/release/types/manifest.go, util/release/vagrant.go, util/release/version.go
The installer (and other programs in the future) want to read these manifests. Currently the installer imports the main release package, which is brittle and adds 1-2MB to the binary size.
This patch moves the manifest types into a separate release package to make them easy to work with. No code is changed, just moved.
=> util/release: Move manifest types into separate package

host/cli/init.go
This is unnecessary, and can result in etcd failure when restarting the host.
Closes #1262
=> host/cli: Error when creating discovery token for single node

router/http.go, router/server.go, router/tcp.go
Errors from listen don't include the bound address, so wrap it in an error that prints the address along with an error.
Closes #1149
=> router: Show useful error when listen fails

slugbuilder/builder/build.sh, slugrunner/runner/init, test/apps/empty-release/bin/compile, test/apps/empty-release/bin/detect, test/apps/empty-release/bin/release, test/test_git_deploy.go
For example the apt buildpack makes a release file containing `---` which is parsed to `nil` by Ruby:
https://github.com/ddollar/heroku-buildpack-apt/blob/master/bin/release
=> slugbuilder: Fix parsing release files with no default types

appliance/etcd/Dockerfile, appliance/etcd/start.sh, bootstrap/manifest_template.json, host/manifest.go, host/manifest_template.json
This moves the argument building logic out of the bootstrap manifest and into the container image, reducing the knowledge of etcd in the manifest.
Incremental patch for #1170.
=> Use start script to pass arguments to etcd

host/host.go, host/libvirt_lxc_backend.go, host/logmux/logmux.go, host/logmux/service_conn.go
Avoid hanging on termination of `flynn-host` by passing EOF's to stream readers, and fix the check in logmux for closed connections. 
fixes #1177
=> host: fix shutdown

discoverd/start.sh, host/manifest_template.json
Move the configuration flags for discoverd from the layer 0 bootstrap manifest to the start script. The start script now waits for the bridge to appear and parses the IP address from it.
This removes knowledge of the flags used by discoverd from the layer 0 manifest and allows the same environment to be used for the discoverd instance on each node.
Incremental patch for #1170.
=> discoverd,host: Move args to start script

README.md
Signed-off-by: Joe Johnston <joe@simple10.com>
=> docs: Fix broken links in README

router/http.go, router/tcp.go
Limit logspam on a datastore sync errors, see #1145. I wasn't able to reproduce the `cannot acquire from closed pool`, but I was able to trigger logspam for `the database system is in recovery mode (SQLSTATE 57P03)`, and this change helped recovery.
=> router: add sleep backoff on datastore sync error

slugrunner/runner/init
discoverd domains are internal to the cluster, so will not work if the user has set http_proxy, as the proxy is most likely not within the cluster.
I tested this by starting a proxy and setting `http_proxy`, then seeing that the build uses the proxy (by viewing the proxy logs) but the slugrunner does not.
=> slugrunner: Don't use a proxy for .discoverd hosts

router/server.go
Shutdown the `Router` before `DataStore` to avoid logspamming pgx pool errors.
fix for #1145.
=> router: shutdown router before datastore

script/release-components
If the tag already exists, we end up overwriting the previous release and the tag doesn't end up being written to GitHub.
=> script: Don't force release tag

gitreceived/gitreceived.go
Two quick fixes for gitreceived paths.
Closes #1237.
=> Fix gitreceived path handling

controller/client/client.go, pkg/httpclient/json.go
This avoids the need to parse the URL and rewrite it to confuse net/http.
=> controller/client: Use DialTLS with pinned

bootstrap/manifest_template.json, controller/controller.go, controller/controller_test.go, controller/examples/examples.go, gitreceived/gitreceived.go, receiver/cache-key/main.go, receiver/flynn-receive.go, receiver/key-check/main.go, test/test_controller.go, updater/updater.go
Changing the controller key looks like this:
```text
NEW_KEY=$(openssl rand -hex 16)
flynn -a controller env set -t web AUTH_KEY=$NEW_KEY,$(flynn -a controller env get AUTH_KEY)
flynn -a gitreceive env set CONTROLLER_KEY=$NEW_KEY
flynn -a taffy env set CONTROLLER_KEY=$NEW_KEY
flynn -a dashboard env set CONTROLLER_KEY=$NEW_KEY
flynn -a controller env set AUTH_KEY=$NEW_KEY
flynn -a controller env unset -t web AUTH_KEY
```
Closes #1324
=> Add support for controller key rotation

script/run-integration-tests, test/runner/runner.go
This is so that the tests can use discoverd DNS (for example to connect to a postgres DB at `leader.postgres.discoverd`).
Extracted from #1301.
=> script,test: Add flynnbr0 to /etc/resolv.conf before running tests

logaggregator/api.go, logaggregator/api_test.go, logaggregator/filter.go, logaggregator/main.go, logaggregator/main_test.go
Add the `filterFunc` & `filterSlice` types and the `Filter` func to the `Filter` interface.
=> logaggregator: refactor filter interface

Godeps/Godeps.json, Godeps/_workspace/src/github.com/mitchellh/go-homedir/LICENSE, Godeps/_workspace/src/github.com/mitchellh/go-homedir/README.md, Godeps/_workspace/src/github.com/mitchellh/go-homedir/homedir.go, Godeps/_workspace/src/github.com/mitchellh/go-homedir/homedir_test.go, Tuprules.tup, cli/Tupfile.lua, cli/config/config.go, host/Tupfile, pinkerton/cmd/pinkerton/Tupfile, test/Tupfile
All but a few binaries can be built as fully static binaries with no cgo.
=> Static binaries

test/cluster/cluster.go, test/runner/runner.go
This introduced intermittent failures in CI when trying to resolve `xip.io` domains, e.g:
```
dial tcp: lookup controller.10.69.2.3.xip.io: No address associated with hostname
```
This reverts commit 41b6357c4a5a9dfbcc95b390e47cc2da71f47632.
=> Revert "test: Use xip.io domains"

host/cli/download.go, test/test_release.go
This avoids trying to replace a file which is in use.
Fixes #1371.
=> host/cli: Unlink destination path during download

appliance/postgresql/client/client.go, appliance/postgresql/http.go, appliance/postgresql/main.go, appliance/postgresql/postgres.go, appliance/postgresql/postgres_test.go, appliance/postgresql/state/state.go, appliance/postgresql/state/state_test.go, bootstrap/manifest_template.json, controller/deployer/strategies/main.go, controller/deployer/strategies/postgres.go, controller/schema.go, schema/controller/common.json, test/test_postgres.go
To minimise the impact of deploying postgres (i.e. to minimise the time in read-only mode), I have added a new deploy strategy which stops postgres jobs in a particular order, waiting for specific service discovery events before moving on.
To summarise the strategy:
* While the head async is from the old release, replace it
* If sync is present, replace it
* Replace the primary
Replacing a job involves:
* calling `Stop` via the API to stop postgres and unregister the service
* waiting for a service down event
* scaling up the new release (the new job will either become the sync or be appended to the asyncs)
* waiting for the new job to set `PG_ONLINE=true` in service discovery (which happens once it has run `pg_basebackup`)
Ideally this would just be a one-by-one deployment with the …
=> deployer: Support deploying postgres

cli/cluster.go
The string in `msg` is generated with `Sprintf` so it is not a format, which leads to the following being logged:
```
Cluster "default" removed.%!(EXTRA string=default)
```
=> cli: Fix log message

script/install-flynn.tmpl
This adds a `--clean` flag to the install script which will do the following before proceeding with the installation:
* prompt the user to confirm the clean
* stop flynn-host
* kill old containers
* destroy ZFS volumes
* remove Flynn files and directories
Closes #1208.
=> script: Support installing from a clean state

host/cli/collect-debug-info.go
This ensures we get debug info even if flynn-host isn’t running.
Closes #1065
=> host/cli: Fallback to collecting container logs from disk

host/cli/collect-debug-info.go, host/host.go, test/cluster/cluster.go
`/tmp` is commonly a tmpfs so rebooting a node can lose logs which are helpful for debugging purposes.
=> host: Store logs in /var/log/flynn rather than /tmp

dashboard/app/lib/javascripts/dashboard/stores/github-repo-buildpack.js, slugbuilder/builder/buildpacks.txt, test/test_git_deploy.go
When a Staticfile file is present in the root of the repo, this buildpack is used to serve files using nginx.
Closes #1398
/cc @jvatic
=> slugbuilder: Add static file buildpack

cli/app.go, cli/cluster.go, cli/env.go, cli/log.go, cli/pg.go, cli/release.go, cli/route.go, cli/scale.go
Currently, it is these two usages don't result in the same output:
```
$ flynn --something a
$ flynn --something=a
```
This PR fixes this.
> Note, writing --input ARG (opposed to --input=ARG) is ambiguous, meaning it is not possible to tell whether ARG is option's argument or positional argument. In usage patterns this will be interpreted as option with argument only if option's description (covered below) for that option is provided. Otherwise it will be interpreted as separate option and positional argument.
[Source](http://docopt.org/)
*Notes:*
* This is the follow-up to #1153
* I wasn't able to test it on my environment, please check if nothing got broken
=> cli: fixed command line usages

bootstrap/run_app_action.go
If there are no hosts running at this point, the host selection will panic with a divide by zero. Instead, if there are no hosts, return an error.
=> bootstrap: Avoid divide by zero in host selection

controller/client/client.go, pkg/cluster/client.go, pkg/httpclient/retry_dial.go
There is a small time window between a flynn-host leader being elected and the leader accepting sampi API requests, in which time `cluster.RegisterHost` will fail with:
```
dial tcp 10.76.22.3:1113: connection refused
```
In this case, and in general, the request should just be retried.
=> pkg/cluster: Retry requests with dial failures

bootstrap/gen_random_action.go, bootstrap/manifest_template.json, router/server.go
It is now required, as not setting it will result in an all-zero key, which could be used by attackers to cause the router to connect to a specific address.
=> Set router sticky key in bootstrap

cli/git.go, cli/main.go
Now it looks like this:
```text
error: Multiple apps listed in git remotes, please specify one with the global -a option to disambiguate.
Available remotes:
production
staging
```
Closes #1419
=> cli: Clarify multiple remotes error

docs/content/postgres.html.md
Old versions of bash (like the versions that ship with OS X) are not capable of sourcing a fd (like the one created during process substitution). This alternative that uses export should work with all versions of ZSH and Bash.
=> docs: Fix DATABASE_URL snippet on old versions of bash

dashboard/app/Gemfile, dashboard/app/Gemfile.lock
I'm not sure why it was in there, but puma isn't used.
=> dashboard: Remove puma from app Gemfile

dashboard/app/lib/stylesheets/dashboard/app-processes.css.scss
Wrap process types onto multiple lines instead of allowing a single line
to grow off the page.
=> dashboard: Fix dashboard css to accommodate many process types

test/test_git_deploy.go
The deploy fails with:
Downloading https://services.gradle.org/distributions/gradle-2.1-bin.zip
Exception in thread "main" javax.net.ssl.SSLHandshakeException:
java.security.cert.CertificateException: No subject alternative
DNS name matching services.gradle.org found.
=> test: Remove Gradle buildpack test

slugbuilder/builder/buildpacks.txt
https://github.com/heroku/heroku-buildpack-nodejs/compare/c8cb21e7...41f6b5cf
- User-defined cache directories from `package.json`
https://github.com/heroku/heroku-buildpack-python/compare/b3a98641...7074d5cb
- pip 6.0.8
- pypy 2.5.1
https://github.com/heroku/heroku-buildpack-scala/compare/ac5560bf...47e88712
- sbt 0.13.8
https://github.com/heroku/heroku-buildpack-php/compare/f23729a3...8da6b92a
- PHP 5.6.7
- PHP 5.5.23
https://github.com/heroku/heroku-buildpack-go/compare/98f37cce...faf0717a
=> slugbuilder: Bump buildpacks

test/cluster/cluster.go
This will help diagnose the apparent libvirtd crashes.
/cc @lmars
=> test/cluster: Dump libvirtd log

installer/http.go
The second return value from `DashboardLoginMsg` (an error which shouldn’t occur) was causing the log15 context to be unbalanced.
Closes #1395
/cc @jvatic
=> Fix installer log

test/cluster/cluster.go
The log file is owned by root and has 600 permissions.
=> test: Fix dumping the libvirt log

test/arg/arg.go, test/cluster/client/client.go, test/main.go, test/runner/runner.go
This is so that logs are dumped if the test binary exits abnormally (e.g. due to a `SIGQUIT` timeout).
=> test: Dump logs in runner

test/test_release.go
The update script has timed out a few times in CI, e.g.:
* https://s3.amazonaws.com/flynn-ci-logs/20150414220413-d9f8d7b9-build-9759f3cf65d2ee7cabbbe28df08a3c3d50a7c975-2015-04-14-22-26-31.txt
* https://s3.amazonaws.com/flynn-ci-logs/20150414220216-7d69dd7b-build-721727af900c0d430a4400f691b9f2a9ae874265-2015-04-14-22-24-44.txt
* https://s3.amazonaws.com/flynn-ci-logs/20150414211133-b285e88b-build-54b66f84443be75e42ddc5460cdef1306bae1713-2015-04-14-21-33-57.txt
Each build failure has the following in the stack trace:
```
goroutine 181 [chan receive, 16 minutes]:
github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/ssh.(*Session).Wait(0xc20838f200, 0x0, 0x0)
/home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/golang.org/x/crypto/ssh/session.go:380 +0x168 …
```
=> test: Wrap release update script in a timeout

test/test_host.go
This test fails quite regularly in CI, we know the fix, and this area of code (i.e. volume management) isn't currently being worked on, so skip for now until we fix the underlying issue.
Ref #1125.
=> test: Skip TestVolumePersistence

test/rootfs/setup.sh
This is in the latest release (1.6.0).
=> test: Remove Docker Upstart patch

cli/cluster.go, test/main.go, test/test_cli.go, test/test_git_deploy.go, test/test_gitreceive.go, test/test_postgres.go
OutputContains also validated success, and certain calls from the CLI returned errors with a successful error code. This refactor allows us to separate checking output from checking success, so we can correctly return error codes from the CLI and also check error content.
Tag @lmars since he suggested the refactor in IRC.
=> test: Refactored tests to separate asserting success and asserting output containing text

cli/scale.go, controller/controller_test.go, controller/deployment_test.go, controller/formation.go, controller/formation_test.go, test/test_cli.go
Blocked scaling nonexisting process types both in the controller and CLI. Tested both independently.
Fixes #1172
=> Prevented scaling process types that do not exist in the release

test/cluster/cluster.go
Building the CLI requires a large amount of RAM due to the embedded installer.
=> test: Increase build VM RAM to 4GB

Vagrantfile, demo/Vagrantfile, util/packer/ubuntu-14.04/template.json
dev/build to 4GB / 4 cores
demo to 2GB / 2 cores (with customizability via env vars)
=> all: Bump Virtualbox resources

cli/git.go, cli/main.go
This allows unambiguously picking an app if there is a single one for the specific cluster. Before this change, the “multiple remotes” error was always displayed even if one could be chosen automatically.
Fixes #1489
=> cli: Filter git remotes if explicit cluster specified

Makefile
gonative occasionally leaves temp files lying around.
=> Makefile: Clean up stale toolchain files

Makefile
`xargs` runs the command once by default even if there is no input, which results in an error from `rm`, because no arguments are provided.
=> Makefile: Don’t clean up if there is no reason to

installer/app/src/views/wizard.js.jsx
The right column's background did not have the same height as the content in Safari. Removing
height: 100% from the style solves this issue and works in Chrome and FireFox as well.
Screenshot in safari:
ping @jvatic
=> installer: Resolved issue with wizard in safari

host/libvirt/types.go, host/libvirt_lxc_backend.go
The `VCPU` option has no effect on containers.
Under libvirt, container CPU restrictions should be specified using "cputune" options:
https://libvirt.org/formatdomain.html#elementsCPUTuning
I have just removed the VCPU option rather than replacing with appropriate CPU tune options as it is unclear how we will expose the parameters to users.
=> host: Stop setting the libvirt VCPU option

cli/ps.go, cli/release.go
This adds the release ID to the `flynn ps` output, as well as adding `flynn release show` which together will help diagnosing rogue processes in #1434.
=> cli: Make releases more visible

receiver/flynn-receive.go, test/test_git_deploy.go
This means that as well as apps with no previous release, apps with a release but which haven't been scaled (e.g. the result of `flynn create foo && flynn env set FOO=BAR`) also get a default web=1 formation.
The test change can be reverted once #1474 lands.
=> receiver: Default scale apps which have no previous scale

bootstrap/run_app_action.go, controller/jobs.go, controller/log_test.go, controller/release.go, controller/types/types.go, controller/utils/utils.go, host/containerinit/init.go, host/libvirt/types.go, host/libvirt_lxc_backend.go, host/manifest.go, host/resource/resource.go, host/resource/resource_test.go, host/types/types.go, logaggregator/api_test.go, pkg/typeconv/typeconv.go, schema/controller/common.json, schema/controller/new_job.json, test/helper.go, test/test_cli.go, test/test_controller.go, test/test_host.go
This implements what was proposed in #1496 except for hosts declaring available resources.
You will notice calls to `resource.SetDefaults` in the controller / host code which I am using to explicitly fill in the resource specifications (rather than blank ones meaning default) so that it is clear to the end user from job / release config what the limits are, defaults or not.
=> all: Add resource specifications

installer/app/src/views/modal/credentials.js.jsx
The installer showed two times `AWS_ACCESS_KEY_ID` instead of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` for each the key and the secret
=> Installer: Fixed typo in AWS credentials dialogue

cli/scale.go, controller/client/client.go, controller/types/types.go, test/test_cli.go, test/test_controller.go, test/test_deployer.go, test/test_git_deploy.go, test/test_healthcheck.go, test/test_scheduler.go
Fixes #1475
Implemented an abstraction for waiting for job events instead of
re-implementing the channel loop each time we need to watch for jobs.
In instances where we need to multiplex job streams with other channels,
the original code is still in place.
=> Refactored job event waiting to use a new JobWatcher abstraction

bootstrap/manifest_template.json, controller/Dockerfile, controller/Tupfile, controller/start.sh, controller/worker/deployment/all_at_once.go, controller/worker/deployment/context.go, controller/worker/deployment/errors.go, controller/worker/deployment/job.go, controller/worker/deployment/one_by_one.go, controller/worker/deployment/postgres.go, controller/worker/main.go, test/test_scheduler.go
This will make it easier to handle more background jobs (e.g. #993).
=> controller: Convert the deployer to a generic worker

cli/scale.go, controller/client/client.go, test/test_cli.go
The previous check of `count < 0` was never true, meaning down events were not being waited for.
I have updated the tests to check all the expected events appear in the scale output.
@jzila FYI this was the cause of the intermittent failures in #1502.
=> cli: Fix scaling processes down

script/install-flynn.tmpl
Previous to this change, receiving EOF on stdin would not abort the removal, which is unexpected.
Fixes #1542.
=> script: Only remove Flynn if "yes" is sent on stdin

cli/cluster.go
`flynn cluster default` returns now  
```
$ ./flynn cluster default
NAME     URL
default  https://controller.dev.localflynn.com  (default)
```
instead of  
```
"default" is default cluster.
```
Closes #1517
=> cli: Output of cluster default now matches cluster

host/resource/resource.go, host/resource/resource_test.go, test/helper.go
The nprocs rlimit limits the process count of the user id of the process
it is applied to. This makes it useless currently, as most jobs end up
running as either root or nobody, resulting in errors like:
fork: Resource temporarily unavailable
When there are more than nproc process running for a specific uid. In
practice, this can happen when scaling a single app to a dozen or so
instances.
The long-term solution is to make sure every job has a different uid,
but this is a complex undertaking, so for now we’ll just remove the
default limit.
=> host: Remove default max procs limit

cli/scale.go, controller/app.go, controller/client/client.go, controller/controller.go, controller/deployment.go, controller/deployment_test.go, controller/events.go, controller/events_test.go, controller/jobs.go, controller/schema.go, controller/types/types.go, controller/worker/deployment/context.go, controller/worker/deployment/job.go, controller/worker/deployment/postgres.go, receiver/flynn-receive.go, test/test_deployer.go, test/test_postgres.go, test/test_scheduler.go
This will make it easier to add more event types which can be streamed to clients (e.g. app deletion events in #1533), as well as removing duplication in the controller.
=> controller: Move events into single app event stream

cli/release.go, controller/client/client.go, controller/controller.go, controller/controller_test.go, controller/release.go
This lists all releases which have a formation for the given app.
This will aid in adding a `flynn release delete <id>` command to delete a release and related resources (e.g. slugs) by allowing users to identify old releases.
=> cli: Support listing app releases

test/test_host.go
This job intermittently times out in CI, and it looks as though it is just congestion on the host slowing it down.
=> test: Increase timeout for resource limits job

slugbuilder/builder/buildpacks.txt
They fixed the compatibility issue we forked to work around
=> slugbuilder: Move back to upstream staticfile buildpack

script/release-vm-images
The 20150611 image is apparently corrupt, the SHA256 doesn't match what the server is serving up.
=> script: Use older Ubuntu Virtualbox image

test/cluster/cluster.go
This got dropped by mistake from #1597.
=> test: Fix booting Flynn in CI

test/test_postgres.go
Now that we can potentially skip received states (commit 3000177), we may have already received all the expected states when we receive a deployment event, so we need to make sure we do not wait for further states when we do not expect them.
=> test: Fix potential timeout in PostgresSuite

host/cli/ps.go, test/buildlog/log.go, test/cluster/cluster.go, test/runner/assets/build-log.html, test/runner/assets/build-log.js, test/runner/assets/index.html, test/runner/assets/style.css, test/runner/runner.go
The file in S3 is now a multipart document and the output of each command from `DumpLogs` gets added to a separate part with an appropriate filename.
I chose to use a single multipart file rather than uploading multiple files to S3 so that we can easily fallback to viewing the raw log in S3 if necessary (it will just include some extra multipart header lines which can be ignored).
Once a build has finished, rather than redirecting to the log in S3, I have added a new page which shows a list of generated files on the left, and the corresponding logs on the right. The logs are delivered to the browser via an SSE stream, one line at a time.
I have added a `-f` flag to `flynn-host ps` to format the output so that `DumpLogs` can create descriptive filenames (e.g. …
=> Improve viewing logs in CI

host/logmux/logmux.go
`m.sc` can be nil if discoverd failed to boot.
Tested manually by causing discoverd to not boot correctly, killing flynn-host and seeing the panic avoided.
Fixes #1386.
=> host/logmux: Fix nil pointer dereference

bootstrap/manifest_template.json, docs/content/installation.html.md
Fix the last two references to `cli.flynn.io`.
=> CLI docs fixes

script/run-integration-tests, test/arg/arg.go, test/main.go
The default of five parallel jobs is too much for the dev VM.
=> Fix dev VM concurrency

cli/export.go, cli/main.go, cli/pg.go, cli/run.go, test/test_cli.go
`flynn export` exports the app config, slug, and database to a local tar file that can be imported into any other Flynn cluster using `flynn import`.
`flynn import` creates a new app using a tar file from `flynn export`. This allows cloning and migration of apps between clusters.
/cc @temujin9 
Closes #1473
=> cli: Implement app export/import

bootstrap/run_app_action.go, controller/app.go, controller/jobs.go, controller/jobs_test.go, controller/scheduler/main.go, controller/schema.go, controller/utils/utils.go, host/cli/inspect.go, host/cli/log.go, host/cli/ps.go, host/cli/stop.go, host/libvirt_lxc_backend.go, host/state.go, pkg/cluster/utils.go, pkg/exec/exec.go, test/helper.go, test/test_scheduler.go
This means that job IDs can always be resolved to the host the job is running on.
Closes #1238
=> all: Always include host ID in job ID

test/cluster/cluster.go
app names can contain dashes, so just take the last two strings from the split, with the assumption that the job ID only contains one dash.
=> test: Fix job ID parsing in DumpLogs

installer/cluster.go
These flags are required to bootstrap the cluster as opposed to a single node.
Closes #1637
=> installer: Add min-hosts and discovery flags to bootstrap

host/Tupfile, host/cli/download.go, host/host.go, host/libvirt_lxc_backend.go, host/nsumount/nsumount.c, pkg/mounts/mounts.go, script/bootstrap-flynn, script/export-components, test/test_host.go
When a mount namespace is created, it inherits all of the mounts from its parent. If they are not `umount(2)`'ed, they will remain and prevent devices from being cleaned up. This currently causes problems when destroying ZFS volumes and cleaning up temporary container rootfs mountpoints.
The libvirt-lxc container system creates two mount namespaces for each container: one in the `libvirt_lxc` supervisor process, and one in the process that execs the actual container process. The latter cleans up the mounts that leak in, but the former does not. This is tracked upstream at https://bugzilla.redhat.com/show_bug.cgi?id=1067489
We work around this issue by adding a small `flynn-nsumount` executable that can reach into an arbitrary mount namespace (using a pid) and call `umount(2)` against a …
=> host: Clean up mounts that leak into libvirt_lxc

script/install-flynn.tmpl
This ensures that our apt-get installs don’t get stuck waiting for input.
Closes #1665
=> script: Set noninteractive env var in install script

controller/events.go, controller/worker/deployment/context.go
One logging fix, and a fix for out-of-order event delivery introduced in #1667.
=> Fix event notify

controller/scheduler/main.go
The v2 scheduler will handle this better by retrying the host lookup: https://github.com/flynn/flynn/issues/1484#issuecomment-125691878
=> controller/scheduler: Handle no available hosts when starting jobs

util/packer/ubuntu-14.04/scripts/upgrade.sh
This should resolve this complaint from the AWS builder:
linux-generic-lts-vivid : Depends: linux-image-generic-lts-vivid (= 3.19.0.25.12) but it is not going to be installed
=> util/packer: Explicitly install linux-image-generic-lts-vivid

script/lib/tuf.sh, script/release-components, script/release-timestamp, script/test/helper.bash, script/test/release.bats, script/test/tuf.bats
Includes a fix for #1684 by running `tuf snapshot` if the snapshot has expired.
=> script: Add release-timestamp

appliance/postgresql/http.go, blobstore/blobstore.go, blobstore/os_filesystem.go, blobstore/postgres_filesystem.go, bootstrap/manifest_template.json, controller/controller.go, controller/scheduler/main.go, controller/worker/main.go, dashboard/api.go, discoverd/server/backend.go, discoverd/server/etcd_backend.go, discoverd/server/http.go, gitreceived/gitreceived.go, logaggregator/api.go, logaggregator/main.go, pkg/status/status.go, router/api.go, router/data_store.go
This PR adds health status endpoints at `/.well-known/status` to all services, including a few that didn't have HTTP servers previously. The reasoning for this is that we will want to add more diagnostic endpoints in the future including metrics, debugging, profiling, etc.
The only service that does not have an endpoint is flannel, which will be added in a separate PR to the flannel repo.
=> Add health status endpoints to all services

bootstrap/add_route_action.go, bootstrap/bootstrap.go, bootstrap/manifest_template.json, controller/client/client.go, controller/controller.go, controller/scheduler/main.go, controller/worker/main.go, dashboard/api.go, discoverd/cache/cache.go, discoverd/daemon.go, flannel/build.sh, flannel/runner.go, host/discoverd.go, host/libvirt_lxc_backend.go, logaggregator/client/client.go, logaggregator/main.go, pkg/status/status.go, router/http.go, router/setup_test.go, router/tcp.go, status/Dockerfile, status/Tupfile, status/status.go, test/test_healthcheck.go, updater/updater.go, util/release/version_template.json
This adds a status service that is exposed via the router at `status.$CLUSTER_DOMAIN` and aggregates the health status endpoints of all of the Flynn services. Here's example output:
```json
{
"data": {
"status": "healthy",
"detail": {
"blobstore": {
"status": "healthy"
},
"controller": {
"status": "healthy"
},
"controller-scheduler": {
"status": "healthy"
},
"controller-worker": {
"status": "healthy"
},
"dashboard": {
"status": "healthy"
},
"discoverd": {
"status": "healthy"
},
"flannel": {
"status": "healthy"
},
"gitreceive": {
"status": "healthy"
},
"logaggregator": {
"status": "healthy"
},
"postgres": {
"status": "healthy"
},
"router": {
"status": "healthy"
}
}
}
}
```
=> Health status service

docs/content/how-to-generate-ssh-key.md
An SSH keypair is a pre-requisite for using e.g. demo dashboard. This describes how one generates that keypair.
Signed-off-by: Alex Nobert <alex@flynn.io>
=> Documentation: How to generate an SSH key for Flynn

Vagrantfile
By default, the root volumes stick around after the Vagrant goes away. This is not a good default if builder instances are cycled regularly.
=> Vagrantfile: Adding DeleteOnTermination to root volume for AWS

docs/content/how-to-generate-ssh-key.md
Secret: whitespace instead of a blank line keeps the ordered list instead of starting a new one for each item. Confirmed locally with site generator. Inconsistent markdown renderers :-1: 
Signed-off-by: Alex Nobert <alex@flynn.io>
=> Documentation: "Fixed" markdown to work with redcarpet's renderer

controller/controller.go, controller/events.go, test/test_controller.go
The Events handler is not wrapped in appLookup, so there will never be an app in the context.
The appID is also passed as a query string rather than a param, so we can't use appLookup.
=> controller: Fix app lookup when streaming events

appliance/postgresql/Dockerfile, appliance/postgresql/postgres.go, docs/content/postgres.html.md
This enables additional GIS workloads including importing and working with the Open Street Map dataset.
=> appliance/postgresql: Add PGRouting extension to PostgreSQL appliance

pkg/syslog/rfc5424/parser.go, pkg/syslog/rfc5424/parser_test.go, pkg/syslog/rfc5424/structured_data.go, pkg/syslog/rfc5424/structured_data_test.go
This is a prerequisite for work I'm doing on logaggregator replication. I also put in a fix for a bug that I found while fuzzing the main parser. Both parsers have been extensively fuzzed with go-fuzz.
=> Add syslog structured data encoding/parsing

gitreceived/gitreceived.go, test/test_git_deploy.go
Switching to full repositories (rather than bare) so that "git checkout" and "git submodule update --init" can be performed prior to passing to the receiver.
(Per conversation with @lmars, we will probably refactor how gitreceived -> receiver -> slugbuilder works, so this went in the simplest-to-implement place. We will still need to address distributing keys into containers, separately.)
Closes #62.
=> gitreceived: adding support for submodules, by switching to full repos (instead of --bare)

receiver/flynn-receive.go, receiver/start.sh, slugbuilder/builder/build.sh, test/test_git_deploy.go
This allows the use of an SSH private key specified in the gitreceive environment as `SSH_CLIENT_KEY` and `known_hosts` entries in `SSH_CLIENT_HOSTS`.
This key and hosts will be used for SSH client operations performed by slugbuilder, including cloning buildpacks.
Closes #1662
@temujin9 Please give this a try and let me know if it meets your needs.
=> receiver,slugbuilder: Allow specifying SSH private key for buildpacks

installer/app/src/views/aws-region-picker.js.jsx, script/release-vm-images, util/packer/ubuntu-14.04/template.json
Now that Packer has migrated away from goamz v4 signatures are used and eu-central-1 can be supported.
Note: Requires packer version of 0.8.0 or greater.
Closes: #1758
=> release: Restore eu-central-1

gitreceived/gitreceived.go, pkg/archiver/archiver.go, test/apps/build-cache/bin/compile
The change in #1617 to checkout a git working directory instead of using `git-archiv`e caused a permissions handling bug that mangled permissions and omitted the +x flag from some directories when the working directory was restored from the repo cache.
This was fixed by stripping the (redundant) checked out working directory when creating the cache. A test was added to verify that the permissions bug does not return.
refs #1757
=> Fix git cache directory permissions issues

cli/scale.go, controller/client/client.go, controller/events_test.go, controller/jobs.go, controller/types/types.go, controller/worker/deployment/job.go, controller/worker/deployment/postgres.go, receiver/flynn-receive.go, test/test_cli.go, test/test_controller.go, test/test_postgres.go, test/test_scheduler.go
This makes the events endpoint more useful for apps such as the dashboard which need job meta for identification (e.g. in the case of taffy jobs).
Dependency of #1768
=> controller,cli,test: Use Job in place of JobEvent

test/test_scheduler.go
The test assumed the controller formation would always have 2 processes.
This fixes the test by interrogating the current formation before initiating the restart process.
Closes #1668
=> test: Fix controller restart test

bootstrap/run_app_action.go, cli/run.go, discoverd/client/heartbeat.go, discoverd/health/register.go, discoverd/health/register_test.go, host/discoverd.go, host/host.go, host/libvirt_lxc_backend.go, test/test_cli.go
=> host: Various updates

controller/app.go, controller/events_test.go, controller/schema.go, controller/types/types.go
This makes watching for app releases much easier (i.e. not having to hold onto all release events until an app event containing the release id is received).
Dependency of #1768
=> controller: Create app_release event instead of app event when setting app release

util/cedarish/Dockerfile
Reverts flynn/flynn#1749
Something about this is broken, the package doesn't appear to exist.
=> Revert "util/cedarish: Add postgres client libraries"

test/runner/runner.go
This is because the CLI now does more than just encode the config into `~/.flynnrc` (it also creates CA cert files)
=> test: Use `flynn cluster add` before running tests

cli/release.go
This makes it easier to use this command in a pipeline, for example listing the scale of all releases:
```
$ flynn release -q | xargs -L1 flynn scale -r
```
Closes #1664.
=> cli: Add --quiet flag to `flynn release`

test/runner/assets/build-log.js
HTML dom IDs with colons in doesn't fly.
=> test: Fix CI build-log

test/test_git_deploy.go, test/test_gitreceive.go
`TestPrivateSSHKeyClone` deploys gitreceive (via `flynn env set`) so can be disruptive to other tests.
=> test: Don't deploy gitreceive concurrently

cli/export.go, cli/pg.go, test/test_cli.go
There's no reason to read the app from the git remote.
Closes #1797
=> cli: Fix import without git remote available

router/api.go, router/api_test.go, router/data_store.go, test/test_cli.go
If the router receives a request to add a duplicate route it will now respond with a 409 Conflict.
The resultant error on the command line now looks like this:
```
$ flynn route add http example.com
conflict: Duplicate route
$ echo $?
1
```
Closes #708
=> router: Report conflict on duplicate route

cli/route.go, test/test_cli.go
Allows users to specify the port they wish to allocate.
If the port is take it will return a duplicate route error.
Closes #1524
=> cli: Allow selecting port for TCP routes

blobstore/blobstore.go, blobstore/postgres_filesystem.go, router/data_store.go
Migrates the actual datapath of blobstore to pgx but retains logic tied to pkg/postgres for now for migrations etc.
Migration of pkg/postgres to follow.
Closes #988
=> blobstore: Migrate to pgx

discoverd/main.go, discoverd/main_test.go
This pull request updates the discoverd DNS store proxy to use the HTTP port instead of the Raft port.
=> discoverd: fix proxy peer port

router/api.go, router/server.go
This is to help diagnose intermittent `TestOmniJobs` failures, but is also useful in general.
=> router: Add logging to main function

controller/scheduler-v2/discoverd.go, controller/scheduler-v2/formation.go, controller/scheduler-v2/scheduler.go, controller/scheduler-v2/scheduler_test.go, controller/testutils/fake_controller_client.go
The main change here is making sure the scheduler is in sync with hosts and formations before starting the main loop.
I have also changed the startup so that the scheduler only registers in service discovery once it is in sync
with the hosts so that a deployment doesn't kill old schedulers before the new schedulers are watching events, which could lead to events being missed. This meant doing discoverd related things in `Run`, so I moved the functionality into an interface to avoid running a discoverd server in the tests.
=> Scheduler V2 Fixes

bootstrap/manifest_template.json, discoverd/main.go, discoverd/start.sh, flannel/runner.go, host/cli/cli.go, host/host.go, host/http.go, host/libvirt_lxc_backend.go, pkg/cluster/host.go, router/server.go, script/bootstrap-flynn, script/kill-flynn, script/run-integration-tests
This is made possible by creating virtual network interfaces for each node and binding all host network services (i.e. flynn-host, discoverd, flannel and router) to those interfaces. 
My main motivator here is being able to test updating a discoverd cluster on my local machine, but this is also pretty useful in general.
Boot a 5 node cluster:
```
$ script/bootstrap-flynn --size 5
```
or run integration tests against a 5 node cluster:
```
$ script/run-integration-tests --size 5
```
It works fine for me on an EC2 instance, but I would appreciate other people testing this out in their own environments.
/cc @titanous @jvatic @jzila @benbjohnson
=> Support running Flynn clusters on a single machine

Godeps/Godeps.json, Godeps/_workspace/src/github.com/inconshreveable/gonative/gonative.go, Godeps/_workspace/src/github.com/inconshreveable/gonative/platform.go, Makefile, cli/Tupfile.lua, script/export-components, test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/install.sh
Also tweaked the CLI OS/architecture pairs to match the available builds:
- darwin 386 was removed
- freebsd amd64 was added
=> all: Update Go to 1.4.3

installer/cluster.go
Added this export, per suggestion [here](https://github.com/flynn/flynn/issues/1887#issuecomment-140901222). Tried it out locally and was able to complete an install on DigitalOcean with this change.
=> Fixes #1887 - Hanging DigitalOcean installer

controller/scheduler/formation.go, controller/scheduler/job.go, controller/scheduler/scheduler.go
Added job state to represent jobs that are stopping but not yet stopped, to ensure they get saved to the controller
=> Stopped jobs now get saved to the controller

controller/scheduler/scheduler.go
=> scheduler: Instead of directly assigning s.isLeader, use HandleLeaderChange to populate logs correctly

controller/scheduler/scheduler.go
=> scheduler: To prevent host.StopJob from blocking, put it in a goroutine

gitreceive/receiver/flynn-receive.go, test/test_git_deploy.go
When the type is in the job meta, the new scheduler kills some slugbuilder jobs while they are running.
Closes #1929
Closes #1934
=> gitreceive/receiver: Drop process type from slugbuilder job meta

util/packer/ubuntu-14.04/scripts/upgrade.sh
The Ubuntu cloud mirrors seem to be finicky.
Switching to achive.ubuntu.com brings the EC2 image inline with the Virtualbox and VMware images.
Closes #1829
=> util/packer: Normalize apt sources across releases

slugbuilder/builder/build.sh, test/main.go, test/test_git_deploy.go, test/test_gitreceive.go
This fixes a bug where Python deploys fail if a custom SSH client key is configured.
/cc @temujin9
=> Fix slugbuilder permissions

util/packer/ubuntu-14.04/scripts/upgrade.sh
The idea here is that the failures we are seeing indicate that the trusty release is either untrusted or not correctly downloaded, by clearing the existing state we eliminate some sources of uncertainty.
It's unlikely this will fix the problem but it makes it easier to reason about what could be wrong.
=> script: Clear apt lists to ensure clean slate

installer/app/src/views/aws-region-picker.js.jsx, util/packer/ubuntu-14.04/template.json
Reverts flynn/flynn#1759
Revert this temporarily until `flynn-release` is fixed to handle publishing ec2 manifests to the eu-central-1 region.
=> Revert "release: Restore eu-central-1"

script/release-components, script/release-flynn
We already create the tag in `release-flynn` so we shouldn't try retag it with the same tag here, it will fail.
=> script: create local git tag in tag_release rather than in release-components

host/cli/signal.go, host/host.go
Adds a `signal` command to `flynn-host` for signalling jobs.
Could potentially add a mapping from string => int signals to allow usage of any of SIGQUIT, QUIT or 3 as the SIGNAL argument.
=> host: Add signal command

bootstrap/manifest_template.json, bootstrap/status_check_action.go
This introduces another step into the bootstrap process that queries the status app to ascertain the health of the cluster before completing the bootstrap.
Example output with a single unhealthy service:
```
19:17:35.309024 wait status-wait
19:17:38.062046 status-check status-check
19:18:08.068476 status-check status-check unhealthy services detected!
The following services are reporting unhealthy, this likely indicates a problem with your deployment:
dashboard
19:18:08.068492 log log-complete
19:18:08.068593 log log-complete
Flynn bootstrapping complete. Install the Flynn CLI (see https://flynn.io/docs/cli for instructions) and paste the line below into a terminal window:
flynn cluster add -p AnKjz+VOD1ndlsUKhGjc/JiiQ4QfsNVQu9Gjg4Cduf0= default dev.localflynn.com …
```
=> bootstrap: Report service status details in bootstrap

host/cli/inspect.go
When a task is yet to end it's EndedAt time is zero.
This change prints the empty string instead of of the zero data in `flynn-host inspect`.
Closes #1958
=> host: Don't display EndedAt if zero

host/libvirt_lxc_backend.go
This should fix #38.
Also, threw in a patch that avoids some memory leaks by freeing libvirt objects.
=> Fix pinkerton cleanup

bootstrap/gen_tls_cert_action.go, bootstrap/manifest_template.json
This allows a cluster to be bootstrapped using a previous cluster's certificates, so a cluster can be seamlessly replaced without breaking clients.
Closes #1039 
/cc @temujin9
=> bootstrap: Allow passing pre-generated TLS details in env vars

util/release/amis.go
Fixes a bug introduced by switching to `aws-sdk-go` inadvertently.
=> util/release: Deference device names when updating EC2 manifest

test/cluster/cluster.go, test/runner/runner.go
Where it was being set previously was ineffective. I have added the domain in the correct place (just before running the test binary) and removed the ineffective `setLocalDNS`.
/cc @jvatic
=> test: Fix setting dashboard domain

bootstrap/status_check_action.go
The status check was racing with the dashboard starting up and reporting it unhealthy falsely.
By retrying until the max wait period is reached we avoid reporting false positives to the user.
=> boostrap: When checking status in bootstrap, retry if unhealthy

bootstrap/manifest_template.json, bootstrap/resource_check_action.go, host/http.go, host/types/types.go, pkg/cluster/host.go
This introduces a stage into bootstrap that runs ahead of starting any services to try ascertain if there are any resources in-use that might cause the bootstrap to fail. Currently this only checks that required ports are available.
Example output when `tcp:1111` is in use on a bootstrap target:
```
00:28:39.479409 check online-hosts
00:28:40.496625 require-env require-env
00:28:40.498279 resource-check resource-check
00:28:40.499529 resource-check resource-check error: conflicts detected!
The following hosts have conflicting services listening on ports Flynn is configured to use:
10.0.2.15: tcp:1111
After you correct the above errors re-run bootstrap to continue setting up Flynn.
```
Closes #1824
=> bootstrap: Check if ports are available prior to bootstrap

slugrunner/runner/init
This prevents slugrunner jobs failing immediately if started when the blobstore is temporarily unavailable (e.g. when resurrecting the cluster and the job starts before the blobstore).
Tested manually by scaling the blobstore down to zero, scaling my app up, scaling the blobstore back up after 10s and seeing that my job started ok (albeit delayed by 10s).
Fixes #1428.
=> slugrunner: Retry downloading slugs

discoverd/server/store.go
The current timeout of five seconds is clearly not high enough, as users are hitting it in the wild in otherwise normal situations.
30 seconds is the timeout that Consul, the primary user of the raft package uses.
Closes #1899 
/cc @benbjohnson
=> discoverd/server: Bump raft apply timeout to 30 seconds

docs/content/faq/how-can-i-deploy-a-docker-image.md, docs/content/faq/how-can-i-pass-configuration-to-my-app.md, docs/content/faq/how-can-i-use-multiple-clusters-with-cli.md, docs/content/faq/how-can-i-use-my-own-domain.md
=> docs: Various FAQ updates

appliance/postgresql/api/server.go, docs/content/postgres.html.md
=> appliance/postgres: Add DATABASE_URL to postgres provider

controller/scheduler/scheduler.go
Introduces debug logging filter and switches some logging in `SyncFormations` to debug.
Closes #2011
=> scheduler: Logging improvements

cli/config/config.go
Previously all configs with conflicts and multiple clusters resulted in the conflict error even if there were not multiple conflicts.
=> cli/config: Fix multiple cluster conflict error

docs/content/index.html.md, gitreceive/receiver/flynn-receive.go, test/README.md, test/apps/http/Procfile, test/test_controller.go
Very new to Flynn, so correct me if there are other ways of doing this.
The problem I'm trying to solve is that I have multiple processes in my app that I want to accessible via the web. Specifically, I have an API, JS frontend and admin UI all running as individual processes in my Procfile, but I can only have one of them routed with `flynn route add http`.
How would it be to extend the "web" process type behaviour to also include process types ending in "-web"?
=> Make more Procfile process types routable via HTTP

script/bootstrap-flynn
The new logmux system needs isolated log directories per `flynn-host` as it no longer namespaces the jobs the same way.
=> script: When using multi-host cluster use separate log directories

util/packer/ubuntu-14.04/template.json
The idea here is to try workaround the race that is causing the apt failures.
If it doesn't help will probably revert it but if it does I will try track down the actual root cause properly (it's just proven elusive).
=> util/packer: Wait 60s before running provisioning scripts on EC2

installer/aws_cluster.go, installer/bare_cluster.go, installer/cluster.go, installer/digital_ocean_cluster.go, installer/stack_template.go
This avoids the initialization cost of EBS volumes provisioned from snapshots, which all boot volumes are. The initial `read(2)`/`write(2)` of a section of an EBS volume can take many seconds due to an underlying read from the snapshot in S3.
This was the cause of discoverd instance expiry, heartbeat writes were taking many seconds while the volume was initializing.
The solution also has the added benefit of not using a sparse file layered on top of ext4 for the ZFS pool.
Closes #2027
Closes #2060
/cc @temujin9
=> installer: Use a separate EBS volume for data

bootstrap/bootstrap.go, bootstrap/run_app_action.go, bootstrap/status_check_action.go, bootstrap/wait_action.go, cli/cluster.go, cli/export.go, cli/pg.go, cli/tar_writer.go, host/cli/bootstrap.go, host/libvirt_lxc_backend.go
`flynn cluster backup` saves a full-cluster backup to a local tar file. The backup consists of expanded app details for the discoverd, flannel, postgres, and controller apps and a SQL dump of all databases in the postgres cluster.
`flynn-host bootstrap --from-backup` bootstraps a cluster and restores a backup. First the discoverd, flannel, and postgres apps are started on the cluster, then the SQL is restored along with some extra commands that update the artifact URLs to the latest ones from the bootstrap manifest.
After the data is restored, the controller/scheduler is started and the scheduler handles starting the rest of the Flynn and user apps.
Refs #1244
/cc @temujin9
=> Full cluster backup/restore

controller/worker/deployment/all_at_once.go, controller/worker/deployment/one_by_one.go
The deployer previously only scaled the old formation down if there were running jobs for the old release, so if the jobs were crashed at the time, the formation would stay scaled up and the jobs would be restarted.
=> worker: Always scale old formations down after deployment

script/run-integration-tests
When moving to the new IP addresses this address was missed.
=> script: Fix multi-host router IP to match new IPs

host/cli/download.go, script/install-flynn.tmpl
I forgot to add this as part of closing #1100.
This means an explicit version can be installed like:
```bash
sudo FLYNN_VERSION="v20151104.1" bash < <(curl -fsSL https://dl.flynn.io/install-flynn)
```
/cc @temujin9
=> script: Support installing explicit version

Makefile
Using `git describe --exact-match` was just returning the first tag seen
for a commit. From `git help describe`:
If an exact match is found, its name will be output and searching
will stop.
So at the current master which is tagged with both v20151113.0 and
v20151114.0, GIT_TAG was being set to v20151113.0, whereas we want it to
be the latest value of v20151114.0:
$ git tag --points-at master
v20151113.0
v20151114.0
$ git describe --tags --exact-match --match "v*"
v20151113.0
Using `git tag --sort | tail -n1` fixes this:
$ git tag --list "v*" --sort "v:refname" --points-at HEAD | tail -n1
v20151114.0
=> Makefile: Fix git tag determination

logaggregator/client/client.go
This prevents errors like the on in CI build https://ci.flynn.io/builds/20151115010657-73c9f645 where the test got a connection refused as it was connecting to a logaggregator which just went down (but whose address was still being returned by discoverd).
=> logaggregator: Use retry dialer in client

bootstrap/manifest_template.json
Allows usage of the `flynn pg` tools with the default `postgres` database.
=> bootstrap: Set PG* env vars on postgres release

bootstrap/manifest_template.json, cli/release.go, controller/app.go, controller/client/client.go, controller/deployment.go, controller/schema.go, controller/schema/queries.go, controller/types/types.go, schema/controller/app.json, schema/controller/common.json, schema/controller/deployment.json, test/test_scheduler.go, updater/updater.go
Both the controller and postgres can take longer than the default 30s to deploy, and so we have some custom timeouts spread amongst the code, but the default timeout is used in cases like `flynn -a controller env set`, so is susceptible to timeouts.
I have added `App.DeployTimeout` which is the timeout in seconds, and added `Deployment.DeployTimeout` which is copied from the app so the client knows what the timeout is when creating a deployment without also looking up the app.
I have also made the schema change as a new migration now that we have a stable release :smile:
=> controller: Add App.DeployTimeout

test/runner/runner.go
The margin for tests taking a little longer is getting pretty thin with some new tests that take longer (domain migration, discoverd deployment etc) the timeout needs to be increased a bit to cover this.
It may be possible to speed the tests up by increasing concurrency also.
=> test/runner: Increase timeout for integration tests to 25m

pkg/httphelper/httphelper.go
A small oversight in the pgx migration. Tested this is correct.
=> pkg/httphelper: Fix retrying on pgx.PgError

discoverd/server/store.go, discoverd/server/store_test.go
This commit wraps the log store in a raft.LogCache to improve I/O performance.
Benchmark tests with the log cache show about a 33% improvement in throughput on my local SSD, however, more importantly, the disk I/O seems to be much more consistent. With the log cache, it was consistently writing about 70MB/sec and without the log cache it would write anywhere from 8-50MB/sec The performance improvement should be more significant on spinning disk.
Signed-off-by: Ben Johnson <benbjohnson@yahoo.com>
=> Add raft log cache

controller/schema.go
Enums while great have proven to be somewhat troublesome when it comes to working with them in migrations.
Instead we will use single column tables which have several advantages, chief among them the ability to enumerate all possible values without the need to hardcode this value outside of the schema.
=> controller: Convert from enums to tables

gitreceive/receiver/flynn-receive.go, test/test_taffy_deploy.go
When the service is specified, it is used by the deployer to ensure that old jobs are not terminated until the new ones are registered in discoverd.
=> gitreceive/receiver: Set service on process type for zero-downtime deploy

controller/worker/deployment/all_at_once.go
=> deployer: skip rollback on all-at-once if old jobs failed to stop in timely fashion

host/cli/tags.go, host/discoverd.go, host/host.go, host/host_test.go, host/http.go, host/types/types.go, pkg/cluster/client.go, pkg/cluster/host.go, test/test_host.go
This is a prerequisite for implementing tag based constraints in the scheduler (i.e. run a job only on hosts tagged with `role=db`).
Tags can be set in a number of ways:
* Via the `--tags` flag when starting `flynn-host daemon`
* Via the host API (`POST /host/tags`)
* Via the CLI (`flynn-host tags set <hostid> key=val...`)
The tags are set in service discovery instance metadata so that they can be easily seen by services which already watch the `flynn-host` service (e.g. the scheduler), and the keys are prefixed with `tag:` so it is clear which metadata should be interpreted as tags.
=> host: Add configurable tags, broadcast via service discovery

test/scripts/upstart.conf
This makes it easier to know what is going on when tailing the log file.
=> test: Trace commands in runner Upstart script

bootstrap/manifest_template.json, discoverd/client/watch_test.go, discoverd/main.go, discoverd/main_test.go, discoverd/server/handler_test.go, discoverd/server/server.go, discoverd/server/store.go, discoverd/server/store_test.go, discoverd/start.sh, discoverd/testutil/testutil.go, host/cli/bootstrap.go, pkg/mux/mux.go, pkg/mux/mux_test.go
This pull request adds support for multiplexing a single TCP socket for `discoverd` to communicate over HTTP and Raft. This simplifies deployment and fixes an issue where HTTP ports are not managed by Raft (#2003).
The multiplexing is required for splitting off the forwarding of instance heartbeats to raft nodes without going through raft itself.
The bulk of the multiplexing code is isolated to the `pkg/mux`. The multiplexer works by checking the first byte of a connection and redirecting the connection to the appropriate listener. The Raft store expects a leading `0xFF` byte while the HTTP handler expects a byte corresponding to the first letter of one of the possible HTTP methods (`CONNECT`, `DELETE`, `GET`, `HEAD`, `OPTIONS`, `POST`, `PUT`, `TRACE`).
---
/cc @titanous @josephglanville
=> discoverd: mux

bootstrap/run_app_action.go, controller/client/client.go, controller/controller_test.go, controller/deployment_test.go, controller/events_test.go, controller/formation.go, controller/formation_test.go, controller/jobs.go, controller/jobs_test.go, controller/scheduler/formation.go, controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go, controller/schema/queries.go, controller/testutils/fake_controller_client.go, controller/utils/utils.go, host/cli/fix.go, host/state.go, pkg/cluster/utils.go, pkg/exec/exec.go, test/test_scheduler.go
Apologies for the big diff with lots of small changes, but it was hard to split these up and still have the tests pass.
To summarise:
* Add `Job.InternalID`, distinct from `Job.JobID`, making jobs easier to track (see [this comment](https://github.com/flynn/flynn/blob/scheduler-updates/controller/scheduler/job.go#L44-L49))
* Reduce logging
* Support getting only "active" formations from the controller (i.e. ones with at least one process scaled up) so the scheduler only needs to make a single request in `SyncFormations` (rather than getting all apps, then a request per app for formations)
* Support getting expanded formations from the controller to avoid the scheduler needing to lookup apps / releases / artifacts separately
* Start jobs in a goroutine (part of fixing #1920), using …
=> Scheduler Updates

test/test_z_domain_migration.go
Ideally this would be isolated from the rest, which is doable, but this is a quicker fix for now.
=> test: Run domain migration tests after other tests

pkg/status/status.go
=> pkg/status: Return version in status

controller/deployment.go, controller/deployment_test.go, controller/schema.go, controller/schema/queries.go
This will allow the controller endpoints `/apps/:app_id/deployments` and `/deployments/:id` to return the `deploy_timeout` value that was used at the time the deployment was created. Currently it always returns 0 despite whatever is set on the app record, which is somewhat surprising.
=> controller: Copy deploy_timeout to deployment on insertion

discoverd/main.go
This works around a strange behavior during deployments where the mux
socket is unable to be bound to be the new process because it's still
in use. Despite having just been closed... by closing it before closing
the store the race is avoided.
=> discoverd: Close mux before closing store

host/cli/download.go
Add a temporary workaround that avoids an apparent intermittent segfault in the buffer pool implementation of `ioutil.Discard.ReadFrom` observed on EC2 with Go 1.4.3.
This patch should be removed on Go 1.5 to test if the problem still exists.
Closes #2211
=> host/cli: Work around segfault in TUF update

pkg/version/version.go, test/test_release.go, updater/types/types.go, updater/updater.go
This introduces behaviour into the updater to manage skipping system applications that can't be updated if the running version is not recent enough.
=> Make updater aware of versions

util/release/types/manifest.go
=> util/release: Strip leading "v" from version in vagrant manifest

controller/controller.go, dashboard/api.go, installer/http.go, pkg/cors/cors.go, pkg/cors/cors_test.go, pkg/httphelper/httphelper.go
Avoid a double `WriteHeader` call by only calling the next handler when the request is not an OPTIONS request.
Closes #2229
=> all: Fix CORS handler usage

cli/cluster.go, cli/export.go, controller/backup.go, controller/client/client.go, controller/controller.go, pkg/backup/backup.go, pkg/backup/tar_writer.go, pkg/httphelper/httphelper.go, test/test_controller.go
=> controller: Add cluster backup endpoint

test/cluster/cluster.go
The introduction of `ControllerSuite.TestBackup` has caused the following types of errors in CI:
```
t.Assert(run(t, exec.Command("cp", "-r", filepath.Join("apps", nameOrURL), dir)), Succeeds)
... result *main.CmdResult = &main.CmdResult{Cmd:[]string{"cp", "-r", "apps/empty", "/tmp/check-6334824724549167320/0/repo"}, Output:"", Err:(*os.PathError)(0xc23fc6f3b0)}
... command failed with error: fork/exec /bin/cp: cannot allocate memory
```
Giving the initial VM more memory should prevent this from being an issue.
=> test: Give initial VM more memory for running tests

bootstrap/manifest_template.json
Populates the `flynn-system-app` meta value on jobs that are started before the controller.
=> bootstrap: Populate flynn-system-app meta on jobs before controller start

logaggregator/buffer/buffer.go, logaggregator/buffer/buffer_test.go, logaggregator/iterator_test.go
Duplicate log lines can be sent when flynn-host is reconnecting.
Closes #2056
=> logaggregator/buffer: Skip duplicate log lines

test/test_z_discoverd.go
The deploy fails and leaves the cluster totally broken.
=> test: Don't deploy discoverd in single node cluster

logaggregator/api.go, logaggregator/server.go
This endpoint is always requested at startup, but the implementation was never committed.
=> logaggregator: Add missing GET /snapshot endpoint

pkg/syslog/rfc6587/rfc6587.go, test/test_logaggregator.go
This fixes a bug that caused logaggregator to stop showing new log lines for some apps when they emitted lines that were 10,000 bytes or longer.
/cc @temujin9
=> pkg/syslog/rfc6587: Fix parsing of lines that are the maximum length

host/http.go, host/libvirt_lxc_backend.go, host/state.go, host/state_test.go, test/test_host.go
This means that if a job fails to start, event consumers will always be notified.
Fixes #2134.
=> host: Add jobs to state as early as possible

controller/schema/queries.go, test/test_controller.go
This prevents an error when two or more apps with the same name (all but one deleted) are selected by the query.
Closes #2257
=> controller: Ignore deleted apps when inserting new resource records

controller/scheduler/scheduler.go
They don't provide useful information and just bloat the log.
=> scheduler: Don't log triggers

host/cli/run.go
Having this flag off ends up mangling output.
Closes #2276
=> host/cli: Disable log round-trip during `flynn-host run`

updater/updater.go
- The app version should be before the MinVersion to be skipped, not the reverse.
- If an image is skipped it should actually be skipped.
=> updater: Fix MinVersion logic

router/schema.go
This allows updates and backup restores to work. Before this change they would fail with:
ERROR: column "path" contains null values (SQLSTATE 23502)
=> router: Add default to HTTP route path column

host/libvirt_lxc_backend.go
Before this patch, each job leaked the three fds used for log streams plus one for the app log file. After this patch, no fds are leaked after a job is cleaned up (verified with `lsof`).
Refs #1556
Closes #2178
=> host: Ensure log stream fds are closed

.gitignore, script/bootstrap-flynn, script/kill-flynn, script/update
This adds a `--version` argument to `script/bootstrap-flynn` so you can boot a released version of Flynn:
```
$ script/bootstrap-flynn --version v20151104.1
===> 00:20:49.408 downloading v20151104.1 into /home/ubuntu/go/src/github.com/flynn/flynn/tmp/v20151104.1
INFO[12-16|00:20:49] initializing TUF client 
INFO[12-16|00:20:50] downloading components with version v20151104.1 
INFO[12-16|00:20:50] downloading images 
flynn/router image 8c39bc6460719e982ec9d43a2f274c0f3fc8255661bcd6eee8343cb1217ab894 exists
flynn/slugbuilder image 9f0e2d019b848ab6cf2d9f82a5c8fc5b0a5ad323305f41bd30d1068e9be1ae3c exists
flynn/slugrunner image 0d5e9340854252b197f3ffcf24879fe25884bc103e3d0192441fe37b8b97c431 exists
flynn/flannel image f855ca6aabc6dcd7529d9547d92d338e723292198b333d0145e0956c0740dc98 exists …
```
=> script: Support booting clusters using released versions

controller/scheduler/job.go, controller/types/types.go, controller/worker/deployment/job.go
It can be NULL in the database, so fetching a NULL value into a string will result in a "Cannot decode NULL into type string" error.
This affects any users updating to the latest released version, so we need to release this soon.
=> controller: Make Job.HostError a pointer

router/data_store.go, router/http.go, router/http_test.go, router/setup_test.go, router/tcp.go
This tracks which routes were removed while the sync is disconnected and removes them on reconnect.
Right now on reconnect we still fetch the entire route table from the database.
Closes #1002
=> router: Handle route deletions missed on reconnect

Godeps/Godeps.json, Godeps/_workspace/src/github.com/boltdb/bolt/batch_benchmark_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/batch_example_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/batch_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/bucket_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/cursor_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/db_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/simulation_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/tx_test.go, Godeps/_workspace/src/github.com/jackc/pgx/.travis.yml, Godeps/_workspace/src/github.com/jackc/pgx/CHANGELOG.md, Godeps/_workspace/src/github.com/jackc/pgx/bench_test.go, Godeps/_workspace/src/github.com/jackc/pgx/conn.go, Godeps/_workspace/src/github.com/jackc/pgx/conn_pool.go, Godeps/_workspace/src/github.com/jackc/pgx/conn_pool_test.go, Godeps/_workspace/src/github.com/jackc/pgx/conn_test.go, Godeps/_workspace/src/github.com/jackc/pgx/doc.go, Godeps/_workspace/src/github.com/jackc/pgx/logger.go, Godeps/_workspace/src/github.com/jackc/pgx/msg_reader.go, Godeps/_workspace/src/github.com/jackc/pgx/query.go, Godeps/_workspace/src/github.com/jackc/pgx/query_test.go, Godeps/_workspace/src/github.com/jackc/pgx/stdlib/sql_test.go, Godeps/_workspace/src/github.com/jackc/pgx/stress_test.go, Godeps/_workspace/src/github.com/jackc/pgx/values.go, Godeps/_workspace/src/github.com/jackc/pgx/values_test.go, controller/controller.go, pkg/postgres/migrate.go
This change implements a listen/notify setup on the `schema_migrations` table in order to reset the connection pool after a migration takes place. This is to ensure any session level cached or prepared query plans can be refreshed.
Refs #2295 
Closes #2235
=> controller: Migration listener

test/runner/runner.go
`Config.Domain` was removed in 1c4d4be.
=> test: Fix `flynn cluster add` command

Vagrantfile, appliance/postgresql/Dockerfile, script/release-flynn, slugbuilder/builder/build.sh, slugrunner/runner/init, test/rootfs/setup.sh, util/assetbuilder/Dockerfile
This ensures that the shell pipeline terminates on error instead of continuing with useless output from curl.
Refs #2308
=> all: Use curl --fail whenever we pipe output with --silent

bootstrap/manifest_template.json
When deploying the controller under heavy load, the web process can actually take a few seconds before it starts listening for HTTP requests, so we need to use service events so that there is always a functioning web process during the deployment.
=> controller: Deploy web processes using service events

cli/ps.go, cli/scale.go, controller/client/client.go, controller/controller.go, controller/controller_test.go, controller/events_test.go, controller/examples/examples.go, controller/jobs.go, controller/jobs_test.go, controller/migrate_test.go, controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go, controller/schema.go, controller/schema/queries.go, controller/testutils/fake_controller_client.go, controller/types/types.go, controller/utils/utils.go, controller/worker/deployment/job.go, pkg/postgres/postgres.go, pkg/testutils/postgres/utils.go, pkg/typeconv/typeconv.go, schema/controller/job.json, test/test_cli.go
Pending jobs are ones which are scheduled to start in the future (either they have been created in-memory by the scheduler and a host is being picked to place the job on, or it is a scheduled restart of a crashed job).
Since pending jobs do not have a host ID, I have migrated the database so the primary key for jobs is the UUID part of the job ID, and the UUID is shown by the CLI whenever the job ID is not set (e.g. `flynn ps` showing pending jobs).
I have also changed the schedulers so that only the leader persists job state to the database, meaning we can drop the state transition validation and use a table rather than an enum.
=> controller: Add "pending" job state

controller/examples/examples.go, test/test_controller.go
The examples attempt to migrate the cluster domain to `127.0.0.1.xip.io` [here](https://github.com/flynn/flynn/blob/master/controller/examples/examples.go#L549-L552), which breaks the cluster and is unnecessary as the test [skips checking the output](https://github.com/flynn/flynn/blob/master/test/test_controller.go#L145) anyway.
=> test: Skip migrating cluster domain in TestExampleOutput

controller/scheduler/scheduler.go, controller/worker/deployment/context.go, controller/worker/deployment/job.go
Jobs which failed have a zero `StartedAt` time and should be treated as though they have been running for a zero amount of time, so therefore should not have their restarts reset.
=> scheduler: Fix restarting jobs which failed to start

controller/controller.go, controller/events.go, pkg/postgres/listener.go, pkg/postgres/migrate.go
I also patched the postgres listener to simply close connections on shutdown rather than trying to unlisten as I ran into the same RxMsg bug from the initial migration. I think I might have a better idea of the root cause of that bug though so I might try work with with pgx maintainer to fix it.
Closes #2327
=> controller: Close database listeners on shutdown

bootstrap/bootstrap.go, cli/scale.go, controller/formation.go, controller/scheduler/host.go, controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go, controller/schema.go, controller/schema/queries.go, controller/testutils/fake_host_client.go, controller/types/types.go, controller/utils/utils.go, host/cli/fix.go, host/cli/tags.go, host/host.go, pkg/cluster/client.go, pkg/cluster/host.go, pkg/typeconv/typeconv.go, schema/controller/formation.json, test/test_host.go, test/test_host_update.go, test/test_scheduler.go
Still some changes I need to make + more testing, but opening for feedback.
Summary of changes:
* Add `Formation.Tags` which is a map of process types to tags for that process type
* Update `flynn scale` to handle adding tags (e.g. `flynn scale web=3,active=true db=2,active=true,disk=ssd`)
* Only place jobs on hosts whose tags are a superset of the process type's tags
* When either host or formation tags change, stop any jobs which no longer match the tags of the host they are on (e.g. if I have scaled to `web=3,active=true`, and I set `active=false` on one of my hosts, then I want the web job running on that host to be stopped and subsequently restarted on a different, still matching host)
Caveats:
* I originally planned to support more fine grained tags per process type (e.g. I want 3 …
=> Tag based scheduling

host/state.go
New jobs from API requests are now added to the state independently of the backend (see #2270), so we need to do the same when resurrecting jobs.
Fixes #2338.
=> host: Ensure new jobs are added to state when resurrecting

slugbuilder/builder/build.sh
This avoids removing `.git` directories in subdirectories. We still want to exclude the top level `.git` directory because there is a large overhead to storing it when working with large repositories.
Refs #2346
=> slugbuilder: Only exclude '.git' at the root of the slug

Vagrantfile, script/bootstrap-flynn, script/run-integration-tests, script/start-flynn-host
* Always use multi-node logic - this deprecates `dev.localflynn.com` in favor of always using `<size>.localflynn.com` even for single node.
* Split out start-flynn-host into it's own script so it can be launched manually to add or respawn a node.
=> script: Refactor multi-node bootstrap.

test/rootfs/setup.sh
Fixes CI issue where cover is unable to be found.
=> test/rootfs: Install go cover tool in rootfs

router/http_test.go
Go 1.4.3 reduced some new request smuggling protection that seems to be running amok with non-GET/HEAD requests. For now we will disable checking for connection liveliness here and track it in #2358 to re-enable it when migrating to Go 1.5 and also notify/work with upstream to get it resolved on the 1.4.X branch.
=> router: Workaround currently broken test in Go 1.4.3

test/rootfs/build.sh
Running into out of space errors during builds, this should give it some more breathing room.
=> test/rootfs: Increase size of sparsefile to 32GB

test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/upgrade.sh
Ubuntu kernel 3.19.0-39 is does not trigger this bug: https://github.com/docker/docker/issues/18180
Verified with:
docker run -it --rm akihirosuda/test18180
Fixes #2365
=> util/packer: Pin kernel version to work around Docker/AUFS bug

bootstrap/manifest_template.json
The Redis app wasn't using `deploy-app` or `add-app` so it wasn't being managed by the controller.
I moved it to `deploy-app` and also renamed it `redis` inline with the `postgres` provider.
=> bootstrap: Use deploy-app to launch Redis provider

appliance/redis/Dockerfile, appliance/redis/cmd/flynn-redis-api/main.go, appliance/redis/cmd/flynn-redis/main.go, appliance/redis/dump.sh, appliance/redis/handler.go, appliance/redis/process.go, appliance/redis/restore.sh, cli/redis.go, test/test_redis.go
Adds support for two new subcommands, `dump` & `restore`
```sh
$ flynn redis dump -f /path/to/mydump
```
```sh
$ flynn redis restore -f /path/to/mydump
```
=> appliance/redis: add dump & restore

script/start-flynn-host
Helpful when writing scripts to test things like resurrection or host reboots.
=> script: Add keep state option to start-flynn-host

test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/install.sh
godeb hasn't been updated to reflect the shutdown of code.google.com
for now use the Flynn fork at https://github.com/flynn/godeb
=> script: Use flynn fork of godeb

test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/install.sh
This reverts commit fce7e7da3da06d08829cf3510fef30a044612bdc.
Godeb accepted my patch upstream so we no-longer need our own fork.
=> script: Revert to upstream godeb

gitreceive/receiver/flynn-receive.go
Fixes setting BUILDPACK_URL via dashboard (issue reported in IRC: https://botbot.me/freenode/flynn/2016-02-01/?msg=59159087&page=2)
=> gitreceive: Fix passing BUILDPACK_URL via --env arg

util/packer/ubuntu-14.04/scripts/install.sh
It looks like this timeout is too low, EC2 can take longer than expected to start libvirt-bin.
Closes #2407
=> util/packer: Bump libvirt start timeout

host/upstart.conf, util/packer/ubuntu-14.04/scripts/install.sh
Disabled in EC2 and Vagrant images so that bootstrap scripts can do their thing.
=> host: Start flynn-host at boot by default

controller/scheduler/scheduler.go
Explicitly wait for the controller API to be registered in discoverd.
If we do not do this and it takes longer than expected to start, the scheduler may crash later when doing the initial job sync. This was observed during a restore from a backup by @temujin9.
=> controller/scheduler: Wait for controller API to start

installer/cluster.go
Only run the startScript on first boot.
=> installer: Ensure startScript only executes on first boot

installer/cluster.go
Fixes several bugs in the userdata script, currently preventing EC2 installs with the latest release.
=> Fix installer userdata

test/test_deployer.go
The scheduler occasionally does not receive job events from hosts, so only updates the job status in the controller when a sync happens. Bumping the deploy timeout to be greater than the sync period ensures deployments don't timeout because of this.
We should probably investigate why some events are being dropped, see for example `DeployerSuite.TestOmniProcess` in the following build:
https://s3.amazonaws.com/flynn-ci-logs/20160207043827-c2d85abb-build-1542c912ced512b896132a9b99eaa51ffcff1fde-2016-02-07-05-00-21.txt
=> test: Increase the deploy timeout

host/cli/inspect.go
The field was changed to a pointer in commit 23babab.
=> host: Fix displaying job ExitStatus in `flynn-host inspect`

host/attach.go, host/cli/log.go, host/http.go, host/types/types.go, pkg/cluster/attach.go
This means running `flynn-host log` for a job which has `DisableLog` set and is already attached now just returns as if there is no log.
I was lead to this by the fact that CI logs are currently around 100MB, with about 70MB of that being the output of the [controller backup test](https://github.com/flynn/flynn/blob/master/test/test_controller.go#L534-L537) because the postgres dump job is still running when the logs are dumped.
Fixes #1697.
=> host: Prevent multiple attachers to interactive jobs

controller/worker/deployment/context.go, controller/worker/deployment/job.go, controller/worker/domain_migration/domain_migration.go, controller/worker/types/types.go, pkg/httpclient/stream.go
A `DomainMigration` job deploys the controller and so may result in the worker which is performing the migration killing itself, in which case the domain migration needs to stop waiting straight away so a new worker can continue with both the controller deploy and the domain migration.
I've also increased the stream reconnect timeout (see explanation in b9d3e51).
=> worker: Stop DomainMigration jobs when worker is shutting down

appliance/postgresql/postgres_test.go, router/setup_test.go, router/tcp_test.go
Don't reuse TCP ports in unit tests.
Closes #1342
=> Fix test ports

bootstrap/add_route_action.go, bootstrap/bootstrap.go
There is a race that can occur when the router discoverd registration has not propagated to the controller, resulting in a 500 from the controller. Retry a few times before giving up.
=> Fix bootstrap route race

host/state.go
This avoids trying to reconnect to definitely dead containers when restarting flynn-host.
Closes #1461
=> host: Don’t persist backend state for containers that aren’t running

appliance/postgresql/postgres_test.go, router/setup_test.go
This avoids conflicting with kernel-allocated high ports.
=> Use lower TCP ports for unit tests

bootstrap/manifest_template.json, controller/worker/deployment/job.go, test/runner/runner.go
This means deployments will not succeed if the router job fails to register the service (e.g. if the `COOKIE_KEY` or TLS env vars are invalid).
=> router: Specify service in release

router/client/client.go
This prevents errors in the controller when trying to create routes during a router deployment as seen in some domain migration jobs.
=> router: Use a retry dialer in the client

host/host.go
When run as an Upstart job, stdout is connected to a pty which ultimately gets logged to a file, which means color codes and escape characters end up being logged to the file (e.g. see [this host log](https://gist.githubusercontent.com/anonymous/5da86fa3300212c642e1/raw/0dceef9f4483588819b893ff1e82929bf5f92327/upstart-flynn-host.log)).
=> host: Always use logfmt output when logging

test/rootfs/setup.sh
Allow the MariaDB unit tests to be run in CI.
=> test/rootfs: Add MariaDB unit test dependencies

test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/install.sh
Pinkerton isn't currently compatible with more recent Docker
versions so we must pin it for now.
Refs: #2459
=> util/packer: Pin docker version

bootstrap/bootstrap.go, bootstrap/wait_hosts_action.go
Improves logging when bootstrapping cluster and hosts are unreachable.
When checking for online hosts for example the new output will tell you which URLs it is still waiting on, including those found via discovery:
```
01:49:57.158452 check online-hosts
01:50:47.214339 check online-hosts error: timed out waiting for 3 hosts to come online (currently 2 online)
The following hosts were discovered but remained unreachable:
http://192.0.2.202:1113
```
Refs: #2454
=> bootstrap: Improve logging when waiting for hosts

blobstore/Dockerfile, controller/Dockerfile, controller/examples/Dockerfile, dashboard/Dockerfile, discoverd/Dockerfile, flannel/Dockerfile, gitreceive/Dockerfile, logaggregator/Dockerfile, router/Dockerfile, router/example-generator/Dockerfile, status/Dockerfile, taffy/Dockerfile, test/apps/Dockerfile, updater/Dockerfile, util/cedarish/Dockerfile
`flynn/busybox:trusty-20160217` was released after merging https://github.com/flynn/docker-busybox/pull/1.
I have not changed the slugrunner / slugbuilder base image references because they are [built after cedarish](https://github.com/flynn/flynn/blob/master/slugbuilder/Tupfile#L2), so will always use the latest cedarish as part of the build.
=> all: Update base images

controller/client/client.go
This ensures the controller client will work on systems not configured for UTC.
=> controller/client: Convert time to UTC when streaming formations

controller/formation.go
When reading back formations from the database it's possible some errors won't be returned on query and instead will be contained in `rows.Err()`.
For instance if the connection pool returns a dead connection.
It's likely this was the root cause of #2486
=> controller: Check rows.Err when listing/streaming formations

controller/types/types.go, schema/controller/common.json
This will allow deploying apps with larger slugs.
=> controller: Bump default deploy timeout to two minutes

host/host.go
Being able to connect to discoverd nodes on other peers doesn't necessarily mean the scheduler is healthy. We should resurrect our own jobs regardless so that if the cluster is damaged then the cluster-monitor will be able to fix it.
=> host: Always resurrect jobs

host/http.go, pkg/httphelper/httphelper.go
First fix for some issues we've seen during backup restores. This will avoid overloading flynn-host when starting everything up.
=> Backup restore fixes

discoverd/client/client.go, discoverd/client/heartbeat.go, host/containerinit/init.go
Before this patch, the discoverd heartbeater would attempt to log errors to `os.Stderr`, which for reasons that have not been fully investigated would hang permanently. The process would never restart heartbeating when discoverd came back and all RPC operations would also become wedged. This prevented the process from being killed and resulted in the fd exhaustion reported in #2461.
Logging to the fd we use for all other log messages from containerinit solves this problem.
=> Fix containerinit hang

cli/route.go, discoverd/cache/cache.go, router/api_test.go, router/data_store.go, router/http.go, router/http_test.go, router/schema.go, router/tcp.go, router/tcp_test.go, router/types/types.go, schema/router/route.json, test/test_cli.go
This implements a `--leader` switch to allow routing only to the leader. If no leader is elected "no backends available" will be logged and a service unavailable message returned.
The main usecase of this feature is to expose data appliances like PostgreSQL to the outside world.
For instance to use this changeset to add a route for postgres one would use the following:
```
flynn -a postgres route add tcp --service postgres --leader
```
TODO
Closes #2126
=> router: Leader routing

test/runner/runner.go
Test runs on the new infrastructure appear to take a bit longer.
=> test/runner: Bump test timeout to 35 minutes

router/api_test.go
Use our low port allocator. High ports can conflict with ephemeral kernel usage.
=> router: Fix hard-coded high port in tests

host/host.go, host/http.go, test/cluster/cluster.go
Allow configuring the maximum number of jobs the API will allow to be started concurrently from the command line.
=> host: Make max job concurrency configurable

discoverd/main.go
If the discoverd cluster doesn’t come up within this timeout, we can prematurely break the bootstrap process, bump it to a nice high ten minutes.
=> discoverd: Bump leader wait timeout at start

test/test_z_domain_migration.go
This will help debug an intermittent failure of the test.
=> test: Log domain migration stream error

controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go, gitreceive/receiver/flynn-receive.go, host/http.go, host/state.go, host/state_test.go, pkg/httphelper/httphelper.go
This updates the scheduler to stop trying to add a job when it knows it has already started (regardless of whether AddJob continues to fail).
The host has also been updated to reject duplicate jobs, meaning the scheduler can continue to try starting a job with the same ID until it actually starts without leading to duplicate jobs.
I've also thrown in an update to the receiver to add `type=slugbuilder` to slugbuilder jobs as the scheduler now handles this correctly.
Closes #2545.
=> scheduler: Don't try to start jobs which have already started

discoverd/client/heartbeat.go, discoverd/health/register.go
This fixes a bug in the discoverd registrar where the first registration fails and then there is no subsequent tries because a struct field (`h.hb`) that is supposed to be nil is not nil.
=> Fix containerinit registeration on error

appliance/mariadb/cmd/flynn-mariadb-api/main.go
MySQL can do some strange things if you don't use their non-standard backtick quoting for database and field names.
=> appliance/mariadb: Use more restrictive quoting

Godeps/Godeps.json, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/asset.go, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/cache.go, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/erb-asset.go, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/eslint_asset.go, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/generic-asset.go, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/javascript-asset.go, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/jsx-asset.go, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/matrix.go, Godeps/_workspace/src/github.com/jvatic/asset-matrix-go/scss-asset.go
This greatly speeds up asset build times in development for dashboard and installer by adding build caching.
See https://github.com/jvatic/asset-matrix-go/commit/2cb2227cdc3d81cfae144cfc1c5b50e0e407da8f
\\cc @titanous
=> Godeps: Bump asset-matrix-go

bootstrap/bootstrap.go, bootstrap/wait_hosts_action.go, host/cli/bootstrap.go
This was previously hard-coded. Also, bump the default to a less aggressive two minutes.
=> Fix host-wait timeout

cli/limit.go, controller/formation.go, controller/schema/queries.go, controller/utils/utils.go, gitreceive/receiver/flynn-receive.go, host/host.go, host/libvirt/types.go, host/libvirt_lxc_backend.go, host/resource/resource.go, host/types/types.go, test/helper.go, test/test_cli.go
CPU limits are implemented as a resource denominated in “milliCPUs”, a concept from Google. When doing placement, a request for 1000 milliCPUs will be equivalent to a single CPU core.
A limit of 1000 milliCPUs results in the Linux default of 1024 CPU shares, and the request portion of the resource spec can be used for scheduling in the future.
CPU shares are relative, the more shares a process has, the higher priority it is. When a host is under load, a job with 2000 milliCPUs will get twice the CPU time as a job with the default of 1000.
Limits can be specified on a per-process basis with:
```text
flynn limit set web cpu=1500
```
Resource partitions complement CPU limits in order to isolate system apps from user apps. A top-level set of cgroups is added that all jobs are nested under. …
=> Add CPU limits and resource partitions

discoverd/server/store.go
Not unlocking the mutex can result in a deadlock at startup.
=> discoverd/server: Fix mutex that doesn’t get unlocked in error path

host/cli/bootstrap.go
If this is not done, restores to a newer version of Flynn will fail with:
run-app mariadb error: bootstrap: host error while launching job: "registry: unexpected status 403"'
=> host/cli: Use current MariaDB artifact URI when restoring from backup

host/cli/bootstrap.go, pkg/backup/backup.go, pkg/backup/tar_writer.go
This fixes an issue with corrupt backups (#2504) and ensures that we don't fail if the user intentionally disabled MariaDB.
=> Fix cluster backup bugs

pkg/postgres/listener.go
Prevents leaking connections during reconnect phase of postgres failover.
This failure happened when reconnects happened fast enough that the pool would be fully consumed before the listener was re-established.
It always leaked connections but the effect was pronounced if multiple primary failovers happen as the connections are never reclaimed.
Closes #2439 
/cc @temujin9 @titanous
=> pkg/postgres: Fix connection leak when Listener errs out

test/rootfs/setup.sh
Facilitates testing the MongoDB branch in CI before merging.
=> test/rootfs: Add MongoDB unit test dependencies

controller/worker/deployment/job.go
This hard-coded timeout is too tight for many larger apps.
Closes #2604.
@lmars I think it makes more sense to use this timeout as the amount of time to wait for a single process to start. We should probably just completely drop some of the other timeouts related to watching the deployment stream.
=> controller/worker/deployment: Use configured deploy timeout when waiting for events

bootstrap/bootstrap.go, host/cli/bootstrap.go
This allows for example creating a Redis app in a cluster restored from a backup which did not have the Redis appliance:
```
$ export CONTROLLER_KEY=xxx
$ flynn-host bootstrap --steps controller-key,redis,add-redis-provider,redis-wait
```
=> bootstrap: Support running a subset of steps

bootstrap/manifest_template.json, controller/migrate_test.go, controller/scheduler/discoverd.go, controller/scheduler/formation.go, controller/scheduler/formation_test.go, controller/scheduler/host.go, controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go, controller/schema.go, controller/types/types.go
This adds a sanity check to make sure we do not scale down "critical" apps such as discoverd, because if we do then clusters break hard.
We should not actually ever be getting these critical apps being scaled down like this, but it happened in #2610, and I suspect it was the controller not handling an error and returning empty formations rather than some agent actively scaling things down.
I have also updated the scheduler tests to use log messages for synchronisation (rather than the make shift events we had previously) which feels a little cleaner.
Fixes #2613.
=> scheduler: Prevent completely scaling down critical apps

bootstrap/scale_app_action.go, host/cli/bootstrap.go
Manually start blobstore to ensure that slugrunner apps that the scheduler starts don’t crash because blobstore isn’t running.
Closes #2642
=> Bootstrap backup blobstore

appliance/postgresql/postgres.go, bootstrap/status_check_action.go, bootstrap/wait_action.go, bootstrap/wait_hosts_action.go
If there is any time skew, subtracting absolute times is not reliable. The timers in Go use monotonic time, which does not have this problem.
I'm not certain that this is necessary, but I have seen a few weird things on CI with no good explanation, and this change is correct.
=> Monotonic timeouts

host/cli/bootstrap.go
Subsequent job requests can race with the first scheduler and cause a ratelimit error during bootstrap. We only need one, as the rest will be started by the scheduler.
Closes #2540
=> host/cli: Only start one scheduler instance when restoring from backup

controller/worker/domain_migration/domain_migration.go, test/test_z_domain_migration.go
Create new routes for apps where old route doesn't have a TLSCert.
Closes #2616
=> controller: Fix domain migration route creation

discoverd/server/store.go
Newer versions of the Raft library update LastIndex differently
as such it's not as good for our usecase. However they also
added a new function AppliedIndex which returns the index of the
last log successfully applied to the FSM.
This is even better than what we had previously as the other did
have a possibility of returning an index of a log entry that was
yet to be applied on the leader.
=> discoverd: Use AppliedIndex instead of LastIndex

bootstrap/manifest_template.json, controller/worker/deployment/discoverd_meta.go, discoverd/deployment/deployment.go, discoverd/main.go
These are some preliminary fixes to issues that can occur during discoverd deployments.
The main one is the addition of the deployment ID to the discoverd metadata as it fixes stale reads of service meta.
=> Discoverd deployment fixes

controller/formation.go, controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/utils/utils.go
In [this CI failure](https://ci.flynn.io/builds/20160423202834-61474f73), the cluster fell over during a controller deployment because new schedulers were started, old ones were killed but the new schedulers all crashed with:
```
20:47:41.968254 scheduler.go:159: timed out waiting for current formation list
```
Whilst I am unsure why the scheduler was not getting the current event from the formation stream, I've made two patches which will improve the situation:
* Only register in service discovery once the current formation event has been received. This means that if there is the above error, the old schedulers will still be around and the deployment will just fail (rather than the old schedulers already being killed, and then the new schedulers also crashing, leaving no running …
=> scheduler: Formation stream fixes

appliance/postgresql/postgres.go
The default log level is `ERROR` which logs transaction errors to the pg log. These errors are also provided to the client, which can log them if they are relevant. Log messages that admins care about will have level of `LOG` or higher.
Closes #2739
=> appliance/postgresql: Don’t log transaction errors

controller/scheduler/job.go, controller/scheduler/scheduler.go
`job.restartTimer` is non-nil for any job that was a restart of another job, even when that job is running. This means that checking for a nil `job.restartTimer` causes `GetHostJobCounts` to ignore jobs which are restarts of others, regardless of whether those jobs are running or not, and thus can lead to too many jobs running on a single host.
This caused errors in a user's cluster because omni jobs were being placed unevenly, leading to the surplusOmniJobs routine stopping them, but then anti-entropy then placing the job unevenly again, leading to the omni job flapping indefinitely.
Fixes #2757.
=> scheduler: Include restarted jobs when counting host jobs

cli/export.go, controller/types/types.go
Fixes #2777.
Tested manually by booting a `v20160327.0` cluster and using the latest CLI to export an app (and also run a cluster backup, but that is unaffected).
=> cli: Fix exporting apps from legacy clusters

controller/scheduler/scheduler.go
When a host is shutting down, we need to make sure we don't restart omni jobs on other hosts, and also prepare for jobs on that host stopping.
Evidence of races were found in the logs of #2760.
=> Scheduler fixes for shut down hosts

router/http.go, router/server.go, router/tcp.go
Ensure that everything gets closed down before we close the database pool, otherwise we’ll deadlock.
Closes #2649
Refs #2784
=> router: Fix shutdown after startup error

test/test_host.go
We were previously relying on the artifact pull from example.com to return a 404, thus generating a "repo not found" error, but example.com recently starting returning a 500 instead. We probably shouldn't be relying on the reliability of example.com :wink:
=> test: Trigger a more reliable error in TestAddFailingJob

host/cli/inspect.go
This will help diagnose #2797 (i.e. is the image artifact set as the file artifact and vice versa, or does the job just have an image artifact and no file artifacts).
=> host/cli: Include artifact URIs in `flynn-host inspect` output

controller/migrate_test.go, controller/release.go, controller/schema.go, controller/schema/queries.go
We were seeing some jobs being started with the artifacts ordered incorrectly (i.e. the image artifact was the file artifact and vice versa). Adding an explicit array index should fix this.
Fixes #2797.
/cc @titanous @josephglanville
=> controller: Add index column to release_artifacts

bootstrap/status_check_action.go, host/cli/bootstrap.go
It can take a bit for all of the components to get started by the scheduler.
Closes #2802
=> bootstrap: Wait up to 10 minutes for cluster restored from backup

appliance/mariadb/cmd/flynn-mariadb-api/main.go, bootstrap/manifest_template.json, controller/worker/deployment/sirenia.go, pkg/sirenia/client/client.go, test/sirenia.go, test/test_healthcheck.go
This changes the MariaDB appliance to scale up the database formation only after the first resource is requested. This saves cluster resources in the case MariaDB goes unutilized.
Fixes #2595
=> MariaDB: Scale up on first resource request

cli/mysql.go, test/test_cli.go
The mysqldump --databases flag leads to both CREATE DATABASE and USE statements to be included in the dump. We are setting the --no-create-db to avoid including the CREATE DATABASE statement (the new app will already have a database), but the USE statement remained leading to the following error on import:
```
ERROR 1044 (42000) at line 22: Access denied for user '04f365e0e25e2c63668876c771ff8cf1'@'%' to database 'dcc6f9d2b76880dde63f975c3637df7f'
```
Given we only export one database, and we use the -D flag on import to use a specific database, there seems to be no reason to use the --databases flag.
=> cli: Fix importing mysql databases

controller/client/v1/client.go
This is to assist in tracking down why issues like #1689 occur.
=> controller/client: Log deployment stream errors

appliance/postgresql/postgres.go
Improves performance when database is doing a large amount of writes by allowing postgres more time to complete snapshots and to perform them less frequently.
=> appliance/postgres: Tune WAL checkpoint settings

cli/release.go, controller/app.go, controller/client/client.go, controller/client/v1/client.go, controller/controller.go, controller/formation.go, controller/release.go, controller/schema.go, controller/schema/queries.go, controller/types/types.go, controller/worker/app_garbage_collection/handler.go, controller/worker/deployment/context.go, controller/worker/main.go, controller/worker/release_cleanup/handler.go, test/helper.go, test/test_cli.go
This adds app garbage collection to remove old slug releases based on the value of `app.Meta["gc.max_inactive_slug_releases"]`:
* if not set or set to `false` then do nothing
* if set to an integer, ensure the app only has that many releases with distinct slugs
Garbage collection cycles are scheduled after every deployment.
For now I have left it as opt in so we can test it out in the real world and then potentially make it the default in the future.
To opt in, run:
```
$ flynn meta set gc.max_inactive_slug_releases=N
```
where `N` is a positive integer.
Ref #2750.
=> controller,worker: Add garbage collection to delete old slug releases

blobstore/README.md, blobstore/blobstore.go, blobstore/blobstore_test.go, blobstore/os_filesystem.go, blobstore/postgres_filesystem.go, bootstrap/manifest_template.json
A number of enhancements to the blobstore to aid in supporting a blobstore backend for a Docker registry (see #2763).
The directory indexes (which are GET requests to `/` with a `dir` param) are simpler versions of listing objects with a prefix from S3 (see [here](http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html#v2-RESTBucketGET-responses-examples-ex3)), and copying files (using the `X-Blobstore-Copy-From` header) is similar to [copying an object in S3](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html), which means we should still be able to make the blobstore an S3 gateway.
=> Blobstore enhancements

host/backend.go, host/cli/collect-debug-info.go, host/cli/inspect.go, host/cli/ps.go, host/host.go, host/http.go, host/libvirt_lxc_backend.go, host/state.go, host/types/types.go, test/cluster/cluster.go, test/test_host.go
See commit messages for more information, but the main change is an attempt to prevent jobs getting stuck in the starting state.
Ref #2773, #2820, #2735.
=> Various host updates

host/cli/bootstrap.go
The new status code is 200, as of #2800.
Closes #2837.
/cc @lmars
=> host/cli: Fix blobstore status check during restore

controller/formation_test.go, controller/schema/queries.go
Schedulers in a cluster restored from a backup were failing to stream formation updates with the following error:
```
t=2016-05-16T15:51:50+0000 lvl=info msg="connecting formation event stream" component=scheduler fn=streamFormationEvents
t=2016-05-16T15:51:50+0000 lvl=warn msg="formation event stream disconnected" component=scheduler fn=streamFormationEvents err="Server error: controller: resource not found"
```
The stream was being closed because the controller was trying to expand deleted formations, hitting `ErrNotFound` when looking up the associated release and returning that to the stream.
I have updated the `formation_list_since` query (along with some others) to check for `deleted_at IS NULL`.
=> controller: Don't include deleted formations in formation stream

script/configure-docker, script/run-integration-tests, test/runner/runner.go
Part of the docker-receive changes (#2763) but opening as a separate PR so we can get the tests to pass in CI.
=> script: Add script to configure Docker with a cluster's TLS CA certificate

blobstore/blobstore.go, blobstore/blobstore_test.go, blobstore/os_filesystem.go, blobstore/postgres_filesystem.go
This is necessary to support [this interface](https://github.com/docker/distribution/blob/6ba799b69ed19ebc0c8ef8325ccaf5d105facfc5/registry/storage/driver/storagedriver.go#L58-L62) when using the blobstore as a backend for a Docker registry.
=> blobstore: Support non-zero file offset for PUT requests

host/http.go
These were added to track down a deadlock that is long since fixed.
=> host: Remove noisy “getting job” log lines

Vagrantfile, demo/Vagrantfile
This plugin can cause the VM to fail to start.
Fixes #2874
=> Vagrantfile: Disable vagrant-vbguest plugin

router/http_test.go
=> router: Add test coverage for http route TLS

discoverd/client/client.go, discoverd/client/heartbeat.go, discoverd/client/service.go, discoverd/client/watch.go, discoverd/main.go, discoverd/server/handler.go, discoverd/server/handler_test.go, discoverd/server/store.go, discoverd/server/store_test.go, discoverd/testutil/testutil.go, host/cli/discoverd.go, pkg/httphelper/httphelper.go, script/bootstrap-flynn, test/test_z_discoverd.go
This changeset makes the discoverd client cluster aware.
It can now be initialised with a connection string of comma delimited servers.
The first server is considered to be preferred and it will use it unless it's unavailable.
If it does become unavailable then the rest of the servers configured will be tried until a working one is found, this server will then be pinned for 60 seconds, after the TTL expires the client will attempt to use the preferred server once more.
Writes are directed to the leader by recording where redirects are sent, if at any point the leader becomes unavailable we will try issue the write to another server and have it redirect us to the new leader.
Closes #2091
=> discoverd/client: Cluster awareness/failover

gitreceive/receiver/flynn-receive.go
This typically happens on the first deploy of an app.
Closes #2827
=> gitreceive/receiver: Use deploy timeout when waiting for web job

controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go
This means that if multiple hosts have zero jobs of a given type, we pick one at random rather than always picking the first one, thus avoiding always scheduling n=1 apps on the same host.
Fixes #2796.
=> scheduler: Shuffle hosts when placing jobs

bootstrap/manifest_template.json, cli/cluster.go, cli/config/config.go, cli/config/git.go, cli/docker.go, cli/export.go, controller/artifact.go, controller/controller.go, controller/types/types.go, controller/utils/utils.go, docker-receive/Dockerfile, docker-receive/Tupfile, docker-receive/auth.go, docker-receive/blobstore/blobstore.go, docker-receive/main.go, gitreceive/server.go, host/libvirt_lxc_backend.go, pinkerton/context.go, script/run-integration-tests, status/status.go, test/cluster/cluster.go, test/helper.go, test/main.go, test/runner/runner.go, test/test_cli.go, test/test_controller.go, test/test_docker_receive.go, test/test_healthcheck.go, updater/types/types.go, util/release/version_template.json
This adds a `docker-receive` app which receives Docker images from `docker push` and creates corresponding artifacts, and `flynn docker push` which also deploys them to the cluster.
Running `flynn cluster add ...` will attempt to configure the local Docker client using `docker login`, but this can fail if the Docker daemon does not trust the Flynn cluster's CA certificate, in which case a warning is printed like:
```
WARN: docker configuration failed with a TLS error.
WARN:
WARN: Copy the TLS CA certificate /home/ubuntu/.flynn/ca-certs/default.pem
WARN: to /etc/docker/certs.d/docker.1.localflynn.com/ca.crt
WARN: on the docker daemon's host and restart docker.
```
Following the instructions then re-running the `flynn cluster add ...` command (or `flynn docker login`) should work.
Assuming …
=> Implement Docker Receive App

slugbuilder/builder/install-buildpack
The Go buildpack is currently failing to clone due to a missing .gitmodules file (see https://github.com/heroku/heroku-buildpack-go/pull/134).
Given we checkout an explicit version, there is no need to checkout origin/HEAD first.
=> slugbuilder: Don't checkout origin/HEAD when cloning buildpacks

slugbuilder/builder/install-buildpack
This fixes `GitDeploySuite.TestStaticBuildpack` which is currently failing on master.
=> slugbuilder: Update buildpack submodules after checkout

host/cli/collect-debug-info.go, host/cli/gist.go
Namely always collects full log files now.
Unless it needs to switch to fallback it will only collect system logs.
If the total file size exceeds the gist limit then it will automatically fallback to tarball.
=> host/cli: collect-debug-info improvements

discoverd/client/client.go, discoverd/deployment/deployment.go, discoverd/server/handler.go
Fixes a linearizability bug caused by using GetMeta in concert with event stream that may be connected to a different server.
=> discoverd: Deployment fixes

script/bootstrap-flynn, script/lib/util.sh, script/start-flynn-host
This makes it easier to test scenarios that require adding/removing
hosts from the cluster manually.
After bootstrapping a cluster with `bootstrap-flynn --size $SIZE` you can then add a new peer by providing it with the indices of the peers you want it to connect to. i.e `start-flynn-host --peers 0,1,2 3`.
This will start the new host at index 3 (`192.0.2.203`) connecting to the existing peers.
=> script: Add --peers to start-flynn-host

status/status.go
Users restoring from a cluster backup may not have a docker-receive release, so docker-receive will not start as part of bootstrap, causing the final status check to fail.
Given not all users will be using docker-receive, we should just make it optional and have a mechanism to create a release and scale it up when pushing an image.
=> status: Make the docker-receive app optional

cli/app.go
Fixes deleting apps that have been scaled to 0.
Fixes #2901
=> cli: Don't wait for job events if expected count is 0

discoverd/main.go, discoverd/server/store.go
This aims to make promotion and demotion requests idempotent.
Firstly by making requests to add/remove peers from the cluster idempotent and further by altering the promotion/demotion logic to be tolerant of being requested to demote/promote oneself when it appears it should already be in that state.
=> discoverd: Improvements to promotion/demotion

controller/scheduler/scheduler.go
This is particularly problematic if we fail to place an omni job, because subsequent placements will treat all hosts as having the requested number of omni jobs, and a host will be picked at random, leading to stopSurplusOmniJobs stopping the job just placed and leading to flapping jobs.
=> scheduler: Reset HostID when placing jobs

appliance/redis/cmd/flynn-redis-api/main.go, bootstrap/deploy_app_action.go, cli/docker.go, cli/env.go, cli/limit.go, cli/release.go, controller/app.go, controller/client/client.go, controller/client/v1/client.go, controller/worker/domain_migration/domain_migration.go, gitreceive/receiver/flynn-receive.go, test/test_cli.go, updater/updater.go
The `deploy_timeout` field is already used to time out waiting for individual jobs to start. Using the same value for an overall timeout is unnecessary and confusing.
Closes #2159
Closes #2826
=> controller/client: Remove deploy stream timeout

discoverd/main.go
If the DNS server hasn't been started yet it's likely we are
are waiting on the host network to be configured.
Because we hold the lock after waitHostDNSConfig() unblocks the DNS
configuration will block on us releasing the lock.
Once this happens the DNS server will be properly configured taking into
account the state after promotion/demotion.
This basically fixes a race where if a new node is added and promote is called before Flannel has come up and notified the host + discoverd has recognized and configured it's DNS server.
=> discoverd: Don't error if DNS isn't running during promote/demote

router/http_test.go
This test was broken by a bug in request smuggling protection in
Go 1.4.2. Re-enable the test that we have now upgraded to Go 1.6.2
Fixes #2358
=> router: Re-enable upgrade path test

controller/jobs_test.go, controller/scheduler/host.go, controller/scheduler/scheduler_test.go, controller/testutils/fake_host_client.go
See commit messages, hopefully fixes the recent flakiness in CI.
=> scheduler: Fix test races

router/data_store.go, router/migrate_test.go, router/schema.go
The hex-encoded hash can be too wide for the index, it appears to be variable length before this patch. Store it as a shorter bytea field.
ERROR: index row size 2792 exceeds maximum 2712 for index \"certificates_cert_sha256_idx\" (SQLSTATE 54000)
=> router: Store certificate SHA-256 as binary not hex

test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/install.sh
Required to build new `mgo` version with SASL authentication.
=> test/rootfs: Install libsasl2 in rootfs

taffy/main.go, test/test_taffy_deploy.go
As discussed on IRC my first attempt to get taffy to support deploying from repos that require key authentication.
=> taffy: Added support for deploying from repos that require key auth.

installer/stack_template.go
This doesn't appear to work with root volumes.
Closes #2983
Reverts flynn/flynn#2964
/cc @kenaniah
=> Revert "Adds encryption to EBS volumes"

host/backend.go, host/http.go, host/libvirt_lxc_backend.go, host/state.go
This prevents jobs which require discoverd & networking which start before discoverd or flannel from blocking the rate limiter (and thus not allowing discoverd or flannel to be started).
Tested manually by reducing `maxJobConcurrency` to 1, adding a new host to a cluster and seeing that the discoverd job initially gets rate limited but then eventually is accepted:
```
t=2016-06-26T23:41:56+0000 lvl=info msg="request started" component=host req_id=1b85897b-42d8-4e6f-a569-c9dd514c40d3 method=PUT path=/host/jobs/host6-4829179d-a95e-4712-b01f-2c98759ec8ce client_ip=100.100.70.3
t=2016-06-26T23:41:56+0000 lvl=warn msg="maximum concurrent AddJob calls running" app=host pid=47620 host.id=host6 fn=AddJob job.id=host6-4829179d-a95e-4712-b01f-2c98759ec8ce
t=2016-06-26T23:41:57+0000 lvl=info …
```
=> host: Unblock the AddJob rate limit when waiting for discoverd / network

controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go
This prevents data races when making assertions on Jobs which may be modified by the main scheduler loop.
Fixes #2980.
=> scheduler: Use InternalState in tests

controller/controller.go, controller/events.go, controller/formation.go, pkg/httphelper/httphelper.go, pkg/postgres/listener.go
A bunch of fixes which make controller shutdown cleaner and also quicker (it currently takes 10s before being forcibly killed, increasing the time of all controller deployments in CI).
=> controller: Shutdown fixes

script/dashboard-dev
@jvatic this puts [your gist](https://gist.github.com/jvatic/df346cfdf1632ca0ccd3) into a script.
Workflow:
* `script/dashboard-dev compile` compile assets into `dashboard/app`
* `script/dashboard-dev run` updates bindata.go, builds and runs the dashboard on port 4457
* make code change, re-run `script/dashboard-dev compile`
=> script: Add dashboard-dev to help testing dashboard changes

host/cli/discover.go, host/host.go
Closes #2150 
```
flynn-host discover -h
usage: flynn-host discover [options] <service>...
Return low-level information about a service.
Options:
--json                 Pretty print response as JSON
Examples:
Show information for service 'controller'.
$ flynn-host discover flynn-host
SERVICE     ID                                ADDR
flynn-host  8d0d15d0b14d9efe6316493a658e6b3f  10.0.2.15:1113
$ flynn-host discover --json controller
[
{
"Name": "controller",
"Leader": {
"id": "0bbd29d630f63b11ae999b1dabd565f9",
"addr": "100.100.36.4:80",
"proto": "http",
"meta": {
"AUTH_KEY": "9b7b3b382f13425da3a8cb390f0937b8",
"FLYNN_APP_ID": "2169984c-c15f-499d-be77-636612425330",
"FLYNN_JOB_ID": "host-b773161b-3e50-43ec-bb38-5c492c2ba2fa",
"FLYNN_PROCESS_TYPE": "web",
"FLYNN_RELEASE_ID": …
```
=> host: added `flynn-host discover` to discover services

test/rootfs/setup.sh
=> test: Add libseccomp-dev to rootfs

test/arg/arg.go, test/cluster/cluster.go
This allows us to test changing the default backend (for example to libcontainer) without needing to modify the test runner.
=> test: Use the default flynn-host backend

appliance/mongodb/cmd/flynn-mongodb-api/main.go, cli/mongodb.go, test/test_mariadb.go, test/test_mongodb.go, test/test_postgres.go, test/test_redis.go
Instead of creating users within the `admin` database create them within the resource databases.
This removes the need for user to authenticate using the `admin` database and is overall less surprising.
=> appliance/mongodb: Fix deletion of MongoDB resources

host/fixer/fixer.go
Enables recovery of MongoDB in the host fixer and cluster monitor.
=> host/fixer: Resurrect/repair MongoDB

Vagrantfile, util/packer/ubuntu-14.04/scripts/install.sh
Before this change, it started in provisioned EC2 instances as well.
=> util/packer,Vagrantfile: Only start Docker at boot in dev VM

test/rootfs/build.sh
CI jobs occasionally fail with `ENOSPC`, increase from 32G to 50G to fix.
=> test/rootfs: Bump rootfs size to 50G

blobstore/blobstore_test.go, blobstore/data/file_repo.go
This fixes a case where the parser will error if there are two spaces in a row.
=> blobstore: Fix parsing of double space in backend config

script/lib/tuf.sh, script/lib/ui.sh, script/release-channel, script/release-components, script/release-flynn
Summary:
* Support releasing an explicit branch (e.g. `script/release-flynn --branch v20160624.1-hotfix`)
* Support using an explicit version string (e.g. `script/release-flynn --version v20160624.1p1`)
* Only release the nightly channel if releasing the master branch
* Generate a changelog when releasing a channel using merge commit messages (there is a `--edit` flag so we can edit them in `vim` before releasing)
Closes #3040.
=> Release updates

appliance/redis/cmd/flynn-redis/main.go, discoverd/main.go, discoverd/server/dns.go, flannel/main.go, host/http.go, host/update.go, logaggregator/server.go, pkg/keepalive/keepalive.go, pkg/keepalive/reuseport.go, pkg/keepalive/sockopt_linux.go, pkg/keepalive/sockopt_stub.go, router/server.go
By default on Linux, TCP connections in the `ESTABLISHED` state do not get reaped for 5 days:
$ sysctl net.netfilter.nf_conntrack_tcp_timeout_established
net.netfilter.nf_conntrack_tcp_timeout_established = 43200
This means that if a `FIN` or `RST` packet is not received, for example if a user closes their laptop instead of shutting down their browser cleanly, the server will keep blocking on the fd for a very long time, resulting in what appears to be a slow fd leak.
The solution is to enable TCP keepalive on the socket which will tell the kernel ping the client periodically and if no response is received, will move the connection into the `CLOSE_WAIT` state, freeing the fd and server resources that were serving it.
The creator of the socket has to opt-in to this. By default `net/http` …
=> Enable TCP keepalive

controller/formation.go, controller/formation_test.go
Instead of closing the connection with an error, log it and move on.
This avoids bricking the streaming endpoint permanently if there is an issue with referential integrity or decoding a specific field.
=> controller: Log formation expansion error

bootstrap/manifest_template.json, controller/scheduler/scheduler.go, test/cluster/client/client.go, test/cluster/cluster.go, test/test_scheduler.go
The first five times a job crashes, restart it right away.
The next ten times, wait ten seconds before retrying.
After that, continue trying every thirty seconds.
Closes #2915
=> controller/scheduler: Simplify crash restart backoff algorithm

test/sirenia.go
Instead we rely on the controller to do the right thing.
Worst case the test will be terminated if it hangs.
=> test: Remove Sirenia deploy timeout

script/bootstrap-flynn, script/start-flynn-host
`FLANNEL_BACKEND` only affects bootstrap, not starting `flynn-host` (the variable was moved by accident in commit f5a2a23).
=> script: Move FLANNEL_BACKEND var back to bootstrap-flynn

pkg/cluster/attach.go
This prevents blocking other calls like Close and Write permanently.
Closes #1457
=> pkg/cluster: Unlock mutex if attach wait fails

router/tcp.go
A new route is built each time `Set` is called, and wrapping a go call in a mutex lock makes no sense in this case.
Closes #1034
=> router: Remove useless mutex lock in TCP handler

host/libcontainer_backend.go
`CAP_AUDIT_READ` does not exist in kernel 3.13, and we don’t need/want these capabilities.
Refs #3095
=> host: Remove unnecessary CAP_AUDIT_{READ,WRITE}

controller/scheduler/scheduler.go
If there are more than 1000 current jobs, the scheduler will deadlock as the `putJobs` channel will be full with no goroutine receiving from it.
=> scheduler: Start persistence loop before syncing jobs

test/rootfs/setup.sh
This is required for building `libcontainer` and was previously pulled in when installing libvirt-bin.
=> test: Add pkg-config to rootfs

test/test_release.go
This is so that the installation step doesn't install libvirt.
=> test: Bump version in TestReleaseImages

test/rootfs/setup.sh, util/packer/ubuntu-14.04/scripts/upgrade.sh
The bug causing us to pin the kernel version (see #2366) has been fixed so we should be safe to upgrade, and we need a newer kernel version for the upcoming squashfs / overlayfs image changes.
=> test,util/packer: Use latest Ubuntu xenial kernel

installer/.gitignore, installer/app/.gitignore, installer/http.go, script/installer-dev
Similar to the existing script for the dashboard (#3024).
Refs #1624
Workflow:
- `script/installer-dev compile` compiles the assets into `installer/app`
- `script/installer-dev run` updates `installer/bindata.go`, then builds and runs the installer on port 4455
- re-run the first step after each asset code change, and the second after changes to the Go code
=> Add dev script to compile/run the installer

host/backend.go, host/host.go, host/http.go, host/libcontainer_backend.go, host/state.go, pinkerton/context.go
This PR fixes two distinct issues, the first triggered the second.
Calls from pinkerton into the graph layer are not thread-safe, causing this flynn-host panic:
fatal error: concurrent map writes
goroutine 747 [running]:
runtime.throw(0xf00770, 0x15)
go/src/runtime/panic.go:547 +0x90 fp=0xc820a772a8 sp=0xc820a77290
runtime.mapassign1(0xbb70a0, 0xc820236690, 0xc820a77490, 0xc820a773c0)
go/src/runtime/hashmap.go:445 +0xb1 fp=0xc820a77350 sp=0xc820a772a8
github.com/flynn/flynn/vendor/github.com/docker/docker/daemon/graphdriver/aufs.(*Driver).Create(0xc82024e140, 0xc8208b4000, 0x31, 0xc820b48831, 0x40, 0x0, 0x0)
vendor/github.com/docker/docker/daemon/graphdriver/aufs/aufs.go:230 +0x6f3 fp=0xc820a77530 sp=0xc820a77350
github.com/flynn/flynn/pinkerton.(*Context).Checkout(0xc820382d80, …
=> Fix host crash due to race and recovery

appliance/mongodb/handler.go
Prevents the peer state machine from running `replSetReconfig` after it should have been stopped. Further work is required to ensure safety in some failure cases but this will stabilise the tests in CI.
=> appliance/mongodb: Stop peer before stopping heartbeater

host/upstart.conf
The previous stanza was causing Upstart to hang on boot, perhaps some kind of circular dependency (I'm not sure).
The runlevel check has the same effect (see http://upstart.ubuntu.com/cookbook/#startup-process), and does not cause Upstart to hang.
Tested by installing Flynn in a VM, modifying `/etc/init/flynn-host.conf` and rebooting successfully multiple times.
Closes #3134
=> host: Simplify Upstart start on stanza

cli/run.go, controller/types/types.go, pkg/backup/tar_writer.go, script/run-integration-tests
The CLI may be communicating with a cluster which still uses the deprecated fields.
Tested manually with:
```
$ script/run-integration-tests --version "v20160624.1" --filter "TestDumpRestore"
$ script/run-integration-tests --version "v20160624.1" --filter "CLISuite.TestExportImport"
```
which exercises most of the "run job" paths (e.g. `flynn pg` / `flynn redis` etc.).
Fixes #3146.
=> cli: Set deprecated newJob.Entrypoint / newJob.Cmd

controller/schema.go
Tested manually:
```
$ script/bootstrap-flynn --from-backup https://s3.amazonaws.com/flynn-test/backups/nodejs-v20160624.1-redis.tar
$ flynn -a nodejs redis redis-cli ping
PONG
```
Fixes #3148.
=> controller: Migrate Args for redis apps

appliance/mariadb/handler.go, appliance/postgresql/http.go
Mirrors the change made to the MongoDB appliance, this is more correct and may potentially close small windows where clients remain connected to the old primary for longer than necessary.
=> Sirenia stop peer heartbeater

cli/run.go
Tested manually:
```
$ script/bootstrap-flynn --from-backup https://s3.amazonaws.com/flynn-test/backups/nodejs-v20160624.1.tar
$ flynn run node --version
v0.10.46
```
Fixes #3154.
=> cli: Set slug Entrypoint for old clusters

pkg/postgres/listener.go
If we don't release the connection here we leak connections if connect attempts fail.
Closes #3018
Closes #1689
=> pkg/postgres: Release db conn if Listen() fails

cli/docker.go, test/test_cli.go
The convention `APPNAME-web` is used for routes by default in the CLI, use that convention when naming the service registration configured for a process type in a release based on a Docker image.
Closes #3097
=> cli: Fix service name for Docker processes

cli/docker.go
It's been removed from Docker: https://docs.docker.com/engine/deprecated/
We (@mnaughto and I) can't push from our OSX machines running the latest Docker for Mac with this option in place, we just get:
````
flynn -a helloworld:latest docker push google/nodejs-hello
flynn: getting image config with "docker inspect -f {{ json .Config }} google/nodejs-hello"
flynn: tagging Docker image with "docker tag --force google/nodejs-hello docker.flynn.domain.com/helloworld:latest"
unknown flag: --force
See 'docker tag --help'.
exit status 1
```` 
Unsure if there are any side-effects of just removing this?
Fixes #3105.
Signed-off-by: Brett Neese <brett@neese.rocks>
=> cli: Remove docker tag --force

router/data_store.go, router/http_test.go, router/migrate_test.go
Before this patch the router would happily add broken and mismatched keys/certs to the database, which would result in sync breaking after a restart.
=> router: Don't allow malformed certificates/keys

appliance/mariadb/Dockerfile
The percona apt repo now redirects to HTTPS.
=> appliance/mariadb: Add apt-transport-https package

cli/docker.go
Example output:
```
$ flynn docker login
WARN: docker configuration failed with a TLS error.
WARN:
WARN: Copy the TLS CA certificate /Users/lewis/.flynn/ca-certs/default.pem
WARN: to /etc/docker/certs.d/docker.54.154.214.235.xip.io/ca.crt
WARN: on the docker daemon's host and restart docker.
WARN:
WARN: If using Docker for Mac, go to Docker -> Preferences
WARN: -> Advanced, add "docker.54.154.214.235.xip.io" as an
WARN: Insecure Registry and hit "Apply & Restart"
WARN: (although it is labelled as "insecure", connections
WARN: will continue to use TLS)
Error configuring docker, follow the above instructions and try again.
```
=> cli: Add Docker for Mac instructions to docker TLS warning

vendor/github.com/awslabs/aws-sdk-go/aws/ec2.go
I'm hot patching this because the client is so old that the repo is gone. I'm not sure how this code ever worked. Fixes a panic while serializing the key import request to EC2.
INFO[07-22|03:24:31] Event: log: Creating key pair
panic: reflect: call of reflect.Value.NumField on uint8 Value
goroutine 173 [running]:
panic(0x8f5980, 0xc82040eb80)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
reflect.flag.mustBe(0x88, 0x19)
/usr/local/go/src/reflect/value.go:202 +0xa6
reflect.Value.NumField(0x7d1440, 0xc8205203e1, 0x88, 0x18d90a8)
/usr/local/go/src/reflect/value.go:1153 +0x2a
github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws.(*EC2Client).loadStruct(0xc82018d1a0, 0xc8203e2e10, 0x7d1440, 0xc8205203e1, 0x88, 0xc82040eb40, 0x13, 0x0, 0x0) …
=> vendor: Fix serialization bug in old EC2 client

pkg/mauth/compare/compare.go, pkg/mauth/compare/compare_test.go
I'm going to try to avoid one big PR for multi-user. Here's the first small component: a package that will be used for encoding comparison operators in macaroon caveats.
Refs #410
=> pkg/mauth/compare: Add compare package

pkg/sirenia/client/client.go
Sets the HTTP client timeout to avoid hanging the Sirenia client indefinitely.
=> pkg/sirenia: Set timeout on HTTP client

discoverd/client/service.go, discoverd/server/store.go, discoverd/server/store_test.go, pkg/sirenia/discoverd/discoverd.go
This allows us to transactionally set the leader and the service meta at the same time, which is in turn used by Sirenia to prevent the metadata from getting out of sync with the leader entry.
Closes #3219
=> discoverd: Allow setting service leader during SetServiceMeta

pkg/sirenia/client/client.go
* Increase the client timeout to 3 minutes, shutdown operations can occasionally take quite some time to complete.
* Drop the Retry dialer in favor of the Default dialer.
Closes #3218
=> pkg/sirenia: Adjust Sirenia client timeout

pkg/stream/basic_stream.go
This avoids copying the struct contents for every method call, which can cause data races.
Closes #3157
=> pkg/stream: Use pointer receiver for Basic struct

host/libcontainer_backend.go
During resurrection, the state database is open for reading, so `SetStatusFailed` (which tries to update the state database) will block until the resurrection has completed, but then that causes a deadlock with `UnmarshalState` which is waiting to receive the error on the ready channel, so this change sends the error before making the blocking `SetStatusFailed` call.
Fixes #3232.
=> host: Fix resurrection deadlock

appliance/redis/cmd/flynn-redis-api/main.go, controller/migrate_test.go, controller/schema.go, controller/types/types.go, host/cli/bootstrap.go, test/test_release.go, updater/types/types.go, updater/updater.go
This also fixes updating slug images during restore.
I have manually tested by rebuilding the Redis / slugbuilder / slugrunner images with a trivial change then restoring two backups, one still referencing `IMAGE_URI` variables and another using the more recent `IMAGE_ID` variables, and verifying the relevant changes happened:
list the new image IDs:
```
$ for name in redis slugbuilder slugrunner; do echo "$(printf '%12s' $name): $(docker images --no-trunc --quiet flynn/$name)"; done
redis: 0f452870faaa232cc3e5cf3b768dcf753dc1c16920a7a6cb063e1c74a848834f
slugbuilder: edc297bea0c70a3fad77ee6baefd3f86c466cb19ff5be3f255503ef1e1217837
slugrunner: c8c728a73ab01a66a6bde7d717e1393e04ccf6655e10d58439ff8da85663a04d
```
check the `IMAGE_ID` var for `gitreceive` / `taffy` / `redis`;
```
$ flynn -a …
```
=> host,updater: Update Redis app and resources

docs/content/apps.md, gitreceive/receiver/flynn-receive.go, test/test_git_deploy.go, test/test_gitreceive.go
`SLUGBUILDER_DEFAULT_MEMORY_LIMIT` will be used if a slugbuilder process type limit is not specified for the app's previous release.
Refs #3108
=> gitreceive/receiver: Allow changing default build memory limit

router/http_test.go, router/proxy/reverseproxy.go
CloseNotify can trigger early with HTTP/1.1 pipelined requests. Since there is no way to detect if a request is pipelined, we instead check if the request was made over HTTP/2 or if the method
is defined as idempotent. Pipelining is relatively rare in the wild, the most common client that uses pipelining is Safari on iOS, which also supports HTTP/2 so this is only relevant when no TLS certificate is configured for the route. There may be obscure non-browser API clients that use POST/PUT/DELETE with pipelining. If this issue comes up again, we can add a route tunable to disable CloseNotify or suggest that the client stop using pipelining or switch to HTTP/2. The issue presents itself as request cancellations that result in 503s in response to random pipelined requests. …
=> router: Fix incorrect cancellation of pipelined requests

router/proxy/transport.go
This gives gitreceive enough time to download/unpack large repos.
Refs #2848
Closes #2788
Closes #2787
=> router: Bump response header timeout to ten minutes

discoverd/client/heartbeat.go, discoverd/client/service.go
Move the logic from `maybeAddService` to `AddService` so that direct callers of `AddService` get retries as well. Fixes a intermittent failure while bootstrapping where the flannel wrapper errors out while discoverd is starting.
Thanks to @tianx2 for reporting this.
=> discoverd/client: Ensure that AddService is always retried

pkg/postgres/migrate.go
Previously an ACCESS EXCLUSIVE lock was held while performing database
migrations. This lock however cannot be attained while an ACCESS SHARE
lock is being held on the table, which is the case when `pg_dump` is
currently in the progress of dumping the database.
Advisory locks were also considered as they would be faster but they
are somewhat more complex and not the best fit as they don't honor
transaction semantics.
=> pkg/postgres: Switch to using EXCLUSIVE locking on schema_migrations

host/cli/inspect.go, host/cli/volume.go, pkg/cluster/host.go
This implements a CLI command `flynn-host volume` that provides operators with administrative tools for listing, creating, deleting and automatically garbage collecting unused volumes.
Closes #2976
=> host: Volume garbage collection

blobstore/Dockerfile, blobstore/Tupfile, blobstore/blobstore_test.go, blobstore/cmd/flynn-blobstore-cleanup/cleanup.go, blobstore/data/file_repo.go
Also, add a command that can cleanup files in external backends that have been marked as deleted:
flynn -a blobstore run /bin/flynn-blobstore-cleanup
Closes #3344
=> blobstore: Delete replaced files from external backend

bootstrap/manifest_template.json, flannel/wrapper/runner.go, host/cli/bootstrap.go, host/host.go, pkg/httphelper/httphelper.go, script/generate-backups, script/run-integration-tests, test/arg/arg.go, test/cluster/cluster.go, test/cluster/instance.go, test/runner/runner.go, test/scripts/upstart.conf, test/test_backup.go
This adds `script/generate-backups` which bootstraps a Flynn cluster at various versions, deploys the Node.js example app, adds a Redis resource and backs up the cluster to a file.
There is also a test which iterates through those backups, bootstraps a cluster then checks the app came up with Redis correctly.
We probably want to expand this a little going further (e.g. use docker push, provision different resources etc.) but this at least gives us a good starting point to start avoiding cluster restore regressions.
=> test: Test restoring historic cluster backups

gitreceive/receiver/flynn-receive.go, test/test_git_deploy.go
This ensures that custom port, service, and health check configurations are not replaced by subsequent deploys.
Closes #3387
=> gitreceive: Add support for customizing port config

bootstrap/bootstrap.go, dashboard/app/lib/javascripts/dashboard/views/provider-route-create.js.jsx, host/cli/bootstrap.go, script/generate-backups, status/status.go, test/test_healthcheck.go, test/test_zz_backup.go
- Ensures that MariaDB, MongoDB, and docker-receive are deployed,
and that STATUS_KEY is set in the dashboard
- Add mongodb to status app
<del>This isn't ready to merge just yet as MariaDB isn't healthy when it scales up. @josephglanville any input you can provide here would be appreciated.</del>
<br/>
Closes #3198
Closes #2988
=> Fix bootstrapping from older backups

controller/worker/deployment/all_at_once.go, controller/worker/deployment/one_by_one.go, test/test_deployer.go
If a formation change is accepted by the controller, we can then leave it up to the scheduler to actually stop the jobs. Failing the deployment if the events aren't received (e.g. because they are already down we just didn't know it yet) won't make any difference.
Fixes #3285.
=> worker: Don't wait for old jobs to actually stop

pkg/backup/backup.go
This emits a `FLUSH PRIVILEGES` command at the end of the dump to ensure
information restored from the `mysql` database is made active.
Closes #3394
=> pkg/backup: Use --flush-privileges when backing up MariaDB

controller/Dockerfile, controller/Tupfile
This ensures that the controller can make outbound HTTPS requests, for example to the telemetry endpoint.
=> controller: Add root CA certificates

host/containerinit/init.go
We also now close the heartbeaters synchronously.
The purpose of this change is to give the router additional grace period to remove backends that will be shutting down shortly from it's routing table.
This ensures that new client requests won't be sent on dead or soon to be dead connections during scale down events, like during a deploy for instance.
=> host/containerinit: Wait 2 seconds before forwarding SIGTERM/INT

discoverd/server/handler.go
Requests to non-leader nodes that can't find a current leader will now be retried.
Closes #3423
Closes #3318
=> discoverd: Return ServiceUnavailable when no current leader

controller/jobs_test.go, controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/schema.go, controller/schema/queries.go, controller/worker/deployment/all_at_once.go, controller/worker/deployment/job.go, controller/worker/deployment/one_by_one.go, schema/controller/job.json, test/sirenia.go, test/test_deployer.go
Change extracted from #3421.
I have also updated deployments so they don't send job events as deployment events (given clients can subscribe to both deployment and job events at the same time,  there isn't really a need for the duplication).
=> controller: Add "stopping" job state 

controller/controller.go, controller/events.go, controller/formation.go, controller/formation_test.go, controller/scheduler/scheduler.go, controller/schema.go, controller/schema/queries.go, controller/types/types.go
This simplifies formation streaming by subscribing to scale events, getting formations since the given time, and then streaming the events to the client, all in the HTTP handler rather than spread across multiple goroutines.
I've also updated the scheduler to ignore stale formation updates.
Fixes #3449.
=> controller: Use event listener for formation streams

discoverd/main.go, discoverd/server/handler.go
The heartbeater uses the HTTP API, so shutting down the API before closing the heartbeater leads to a "discoverd: shutting down" error, and since the error is a retriable one, the heartbeat close blocks for 10s.
When this happens on the leader during a deployment, it causes all service heartbeats to expire, wreaking havoc on the cluster.
=> discoverd: Fix closing the heartbeater on shutdown

appliance/postgresql/Dockerfile
Without the explicit 2.3 version, the package fails to install with:
```
The following packages have unmet dependencies:
postgresql-9.5-postgis-2.3-scripts : Conflicts: postgresql-9.5-postgis-2.2-scripts but 2.2.2+dfsg-7~137.gite11228b.pgdg14.04+1 is to be installed
```
This bug report seems related:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839182
@josephglanville @titanous I don't know if this is a change we actually want, but we can't currently build the pg appliance without it (so CI isn't coming back).
=> appliance/postgresql: Install explicit version of postgis

controller/client/v1/client.go, controller/formation.go, controller/formation_test.go
The test has been failing intermittently since merging #3456, this change makes it slightly more robust.
=> controller: Fix formation streaming test

demo/Makefile
This PR fixes #3450 by trying `xdg-open` first, which is the Linux equivalent of OS X `open`
Then, if that fails, use `open`... I don't know if there's a better way to do this, but this works for me! :)
Signed-off-by: Joe Marty <jmarty@iexposure.com>
=> demo: fix 'make dashboard'

host/cli/inspect.go, host/containerinit/init.go, host/http.go, host/libcontainer_backend.go, host/resource/resource.go, host/types/types.go, host/volume/backend.go, host/volume/manager/manager.go, host/volume/volume.go, host/volume/zfs/zfs.go
Summary of changes:
* Support importing raw (possibly sparse) filesystem images into zvols and then mounting them
* Add `host.Mountspec` having `URL` and `Hashes` which reference a SquashFS filesystem, allowing the host to download, verify and import it into a volume
* Add `job.Mountspecs` which is a list of SquashFS mountspecs which are layered at the root directory of the container using OverlayFS, with a read-write Ext2 volume on top
* Add `resource.TypeDisk` which controls how big the read-write Ext2 volume is for each job
Things to note:
* I have made the default disk limit 100MB because most jobs should not need to write to the filesystem, and if they do they should provision a data volume and use that, but in case this is problematic I've added support to make it configurable in a …
=> host: Use SquashFS + OverlayFS via Mountspecs 

cli/log.go, controller/app.go, controller/client/client.go, controller/client/v1/client.go, controller/controller.go, controller/examples/examples.go, controller/log_test.go, controller/types/types.go, host/containerinit/init.go, host/host.go, host/libcontainer_backend.go, host/logmux/logmux.go, logaggregator/api.go, logaggregator/api_test.go, logaggregator/client/client.go, logaggregator/filter.go, logaggregator/iterator_test.go, logaggregator/server_test.go, logaggregator/types/types.go, script/start-flynn-host, test/cluster/cluster.go, test/test_host_update.go, test/test_logaggregator.go, test/test_scheduler.go
Example:
```
$ flynn -a nodejs-flynn-example log --init --raw
t=2016-10-12T12:26:05+0000 lvl=info msg="starting the job" component=containerinit args="[/runner/init start web]"
t=2016-10-12T12:26:05+0000 lvl=info msg="monitoring service" component=containerinit name=nodejs-flynn-example-web port=8080 proto=tcp
t=2016-10-12T12:26:05+0000 lvl=info msg="adding healthcheck" component=containerinit name=nodejs-flynn-example-web port=8080 proto=tcp type=tcp interval=0s threshold=0
t=2016-10-12T12:26:05+0000 lvl=warn msg="healthcheck error" component=containerinit name=nodejs-flynn-example-web port=8080 proto=tcp component=monitor check=tcp://100.100.23.18:8080 err="dial tcp 100.100.23.18:8080: getsockopt: connection refused"
t=2016-10-12T12:26:06+0000 lvl=warn msg="healthcheck error" …
```
=> host,logaggregator: Include init logs in app log

host/cli/volume.go
Volumes from stopped jobs are still considered attached.
This fixes volume gc so that unless the volume is attached to a running
or starting job it will be collected.
=> host/cli: Fix volume garbage collection

gitreceive/receiver/flynn-receive.go, test/test_gitreceive.go
Before this patch, doing a `git push` deploy would remove the slugbuilder process type from the release, removing any custom per-app limits.
=> gitreceive: Persist slugbuilder limit across deploys

util/packer/ubuntu-14.04/scripts/install.sh
This key is generated by EC2 during the build process, and only lives in memory during the Packer build process. It never touches the disk and is not saved anywhere.
https://github.com/mitchellh/packer/blob/ae2b31c4ec2e677dce833371b02cdbf48adcf1cd/builder/amazon/common/step_key_pair.go
=> util/packer: Delete ephemeral Packer SSH public key

appliance/mariadb/Dockerfile
See this article for details on the key rotation.
https://www.percona.com/blog/2016/10/13/new-signing-key-for-percona-debian-and-ubuntu-packages/
=> appliance/mariadb: Update the Percona APT signing key

bootstrap/sirenia_wait_action.go, host/cli/bootstrap.go
This fixes a race condition where attempting to restore the MariaDB database would deadlock with the initial replication backup transfer. However it's also correct to use this for Postgres and MongoDB so updated both of those to use this new wait step too.
Fixes #3527
=> bootstrap: Wait for Sirenia databases to become read/write

controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go
Before this change, `findJobToStop` would continually choose the same `stopping` job when scaling down multiple jobs, causing the scheduler to thrash, trying to stop that job multiple times before then choosing another job to stop once that one has actually stopped.
`stopping` jobs are now considered as stopped, and `SyncJobs` has been updated to make sure that any jobs in the `stopping` state get stopped.
This also fixes #2774.
=> scheduler: Treat "stopping" jobs as stopped

appliance/postgresql/cmd/flynn-postgres-api/main.go
This mirrors what is done for MariaDB and avoids issues caused by the
user being able to run DROP, but not CREATE DATABASE.
Fixes #3537
=> appliance/postgres: Grant user privileges instead of owner

docs/content/production.html.md
Ran into this while migrating my blobs to s3. Was just missing the ```-```.
=> Fix syntax for blobstore migrate command in production docs

cli/export.go, cli/main.go, cli/pg.go, cli/run.go, controller/client/client.go, controller/client/v1/client.go, controller/jobs.go, controller/types/types.go, schema/controller/new_job.json
Allows altering the concurrency of the restore process.
This change also changes the default behaviour to use 4 jobs.
=> cli: Add --jobs to commands that invoke pg_restore

cli/main.go
While installing a test cluster tonight to try out the mongodb component, I noticed that the mongodb module is not mentioned by `flynn --help`.  This tiny PR adds that.  I looked through the CLI tests and didn't see anything explicitly testing the output of `--help`, but if I missed that, I'd be happy to update it.
```
vagrant@flynn:~/go/src/github.com/flynn/flynn$ flynn --help
usage: flynn [-a <app>] [-c <cluster>] <command> [<args>...]
Options:
-a <app>
-c <cluster>
-h, --help
Commands:
help        show usage for a specific command
install     install flynn
cluster     manage clusters
create      create an app
delete      delete an app
apps        list apps
info        show app information
ps          list jobs
kill        kill jobs
log         get app log
scale       change formation …
```
=> cli: Add mongodb to help message.

bootstrap/manifest_template.json
Fixes Sirenia scale up code for singleton clusters.
Without this change the formation will be scaled to 3 but the state
machine will start in singleton mode and freeze the cluster with only 1
active member but 2 extra unassigned instances.
This change ensures on scale up only 1 database instance will be
started.
=> bootstrap: Move SINGLETON flag on db appliances to app

cli/mysql.go
This ensures that dumps are not mangled by line splitting, and do not get stored in log files and buffers.
Closes #3573
=> cli: Don’t round-trip MySQL dumps through log tier

CONTRIBUTING.md
Old link is broken. The link from https://github.com/google/styleguide
=> docs: Fix missing Google Style Guide link

host/libcontainer_backend.go, host/logmux/logmux.go, host/state.go, host/types/types.go, logaggregator/api.go, logaggregator/filter.go, logaggregator/server_test.go, logaggregator/types/types.go, logaggregator/utils/utils.go, test/apps/Dockerfile, test/apps/Tupfile, test/apps/oom/main.go, test/test_host.go
As well as logging the OOM notifications to the init log, I have introduced a `MsgID` type which encapsulates the "IDx" message IDs used in raw syslog messages, plus a cleanup of the unused `ActiveJob.ContainerID`.
Closes #3375.
=> host: Log OOM kills to the job's init log

appliance/redis/cmd/flynn-redis-api/main.go, bootstrap/manifest_template.json, bootstrap/run_app_action.go, cli/release.go, controller/jobs.go, controller/migrate_test.go, controller/release.go, controller/scheduler/job.go, controller/scheduler/scheduler.go, controller/schema.go, controller/types/types.go, controller/utils/utils.go, host/cli/bootstrap.go, host/fixer/sirenia.go, schema/controller/process_type.json, schema/controller/volume_req.json
This gives us more flexibility for specifying extra configuration for volume provisioning (e.g. indicating that the volume should be deleted when the job stops).
I have introduced a `VolumeReq` type (rather than just `Volume`) because in the future we want to model actual volumes in the controller, whereas `ProcessType.Volumes` are just requests for volumes to be provisioned.
=> controller: Replace ProcessType.Data with ProcessType.Volumes

blobstore/Dockerfile, cli/export.go, controller/examples/examples.go, controller/jobs.go, controller/release.go, controller/types/types.go, controller/utils/utils.go, controller/worker/app_garbage_collection/handler.go, docker-receive/Dockerfile, docker-receive/Tupfile, docker-receive/artifact/graphdriver.go, docker-receive/artifact/main.go, docker-receive/main.go, gitreceive/receiver/flynn-receive.go, host/containerinit/init.go, host/libcontainer_backend.go, host/types/types.go, pinkerton/ref.go, pkg/exec/exec.go, pkg/typeconv/typeconv.go, slugbuilder/Dockerfile, slugbuilder/Tupfile, slugbuilder/artifact/main.go, slugbuilder/builder/build.sh, slugbuilder/builder/create-user.sh, slugbuilder/convert-legacy-slug.sh, slugrunner/runner/init, test/test_blobstore.go, test/test_cli.go, util/release/manifest.go
This includes the following changes:
* Add `Uid` / `Gid` to `ImageEntrypoint` which controls the User / Group used for the job process
* Build slugs as Flynn images containing `/app` and `/etc/{passwd,group}` with a `flynn` user
* Convert Docker images to Flynn images when pushed to `docker-receive`
* Update app import / export to support Flynn images
* Delete images from `docker-receive` based apps when deleting releases
=> Migrate slugs and docker-receive releases to Flynn images

controller/jobs.go, controller/types/types.go, pkg/backup/backup.go, schema/controller/common.json, schema/controller/new_job.json
This runs the database dumps on the cluster in the `background` partition so they run at reduced priority to user jobs.
Also adds capability to scheduler jobs with custom partition via the controller.
=> pkg/backup: Run database dumps in background partition

bootstrap/run_app_action.go, controller/jobs.go, controller/scheduler/scheduler.go, controller/types/types.go, controller/utils/utils.go, host/fixer/sirenia.go, host/libcontainer_backend.go, host/state.go, host/types/types.go, pkg/cluster/host.go, test/test_host.go
I think eventually we want volume GC at a higher level than flynn-host, but for now this prevents leaking data volumes which we know are ephemeral.
=> controller: Delete data volumes when one-off jobs stop 

cli/export.go
It has been removed in recent versions of Docker.
Fixes #3602.
=> cli: Stop using --force with 'docker tag'

controller/worker/deployment/job.go
Previously we were using a timeout for each individual job event, which means it was reset every time the scheduler tries to restart a failing job.
=> worker: Fix deployment timeout

host/libcontainer_backend.go
This may not be set if running an update from a version prior to commit 4079ded.
=> host: Ensure container.MuxConfig is set on restore

bootstrap/manifest_template.json, docker-receive/Dockerfile, docker-receive/Tupfile, docker-receive/migrator/main.go, gitreceive/receiver/flynn-receive.go, host/cli/bootstrap.go, host/containerinit/init.go, pkg/backup/backup.go, slugbuilder/Dockerfile, slugbuilder/Tupfile, slugbuilder/builder/build.sh, slugbuilder/builder/install-buildpack, slugbuilder/migrator/main.go, test/test_controller.go
Some small updates plus the addition of slug and docker-receive migrators which convert to Flynn images on cluster restore.
The migrators connect directly to the controller database so that it can update the release artifacts in place and in a transaction, rather than creating new releases via the controller API.
I've also moved the various artifact update SQL to run after the controller has started so that we know the artifacts have the new manifest columns.
=> bootstrap: Convert slugs and Docker images on cluster restore 

controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go
Host IDs should not contain dashes because that is the separator used to extract the host ID part of a job ID (see [`cluster.ExtractHostID`](https://github.com/flynn/flynn/blob/master/pkg/cluster/utils.go#L12-L18)).
I've also fixed the logging of attempts in `StartJob` (it was previously always one behind, and not logged after the first attempt failure).
=> scheduler: Fix host IDs in TestFailingAddJob

docker-receive/artifact/main.go, docker-receive/main.go, host/cli/bootstrap.go, host/cli/destroy-volumes.go, script/generate-backups, script/start-flynn-host
The Docker library creates temporary files in `/tmp` for verifying layer digests which don't always fit on the ext2 tmpfs.
I've also added a docker-receive deploy backup to CI (and updated `script/generate-backups`), and updated the bootstrap scripts so we don't delete system image volumes every time we run `script/bootstrap-flynn`.
=> docker-receive: Mount tmp volume at /tmp rather than /data

test/cluster/cluster.go
Services now listen on the external VM IP since 10075f4.
=> test: Set DISCOVERD when dumping logs

script/install-flynn.tmpl
This adds support to manually install Flynn on Ubuntu 16.04, but we will continue to use Ubuntu 14.04 via `flynn install` until we fully switch to 16.04 in dev + CI.
I have successfully installed both the stable (`v20161017.1`) and nightly (`v20161108.0`) versions on 14.04 and 16.04 using this updated script.
Ref #2789.
=> install-script: Support installing on Ubuntu 16.04

script/install-flynn.tmpl
This mitigates issues that are reported due to clock skew.
Closes #3581
=> script: Install ntp while installing Flynn

pkg/resource/resource.go
Fixes the recent failures of `TestClusterBackups` where resources are provisioned before the APIs are available.
=> controller: Use a retry client when provisioning resources

Makefile, host/cli/destroy-volumes.go, host/cli/download.go, host/host.go, host/volume/api/http.go, host/volume/manager/manager.go, host/volume/manager/persistence_test.go, host/volume/volume.go, host/volume/zfs/zfs.go
We don't seem to be running the volume tests in CI, so I have fixed that too.
=> host/volume: Don't error on restore if a volume no longer exists

docs/content/databases/mongodb.md
the current directory has to be specified. Otherwise a empty tar would be created.
=> docs: Update mongodb.md

installer/cluster.go
Copying images on EC2 can take a few minutes.
=> installer: Bump bootstrap timeout

test/helper.go, test/test_cli.go
This is to debug git push failures in CI like the following which have no output:
```
++ 20:12:08.770 /usr/bin/git push flynn master
test_git_deploy.go:67:
t.Assert(r.git("push", "flynn", "master"), Succeeds)
... result *main.CmdResult = &main.CmdResult{Cmd:[]string{"git", "push", "flynn", "master"}, Output:"", OutputBuf:(*bytes.Buffer)(0xc42011f260), Err:(*exec.ExitError)(0xc42038a4c0)}
```
=> test: Set GIT_TRACE to debug git push failures

controller/scheduler/discoverd.go, controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go
Exiting may leave the cluster without a scheduler, it is better to just wait for the events to happen.
=> scheduler: Don't exit at startup whilst waiting for events

controller/client/client.go, docker-receive/artifact/main.go, logaggregator/client/client.go, pkg/cluster/client.go, pkg/sirenia/client/client.go, router/client/client.go
This fixes a connection leak in the cluster-monitor fixer, which creates new clients for some phases. These new clients were not subsequently re-used and the established connections in the HTTP connection pool were leaking.
The solution is to reuse the same HTTP transport across all instances of all clients, which this change implements.
=> all: Reuse HTTP client transports

host/cli/bootstrap.go, slugbuilder/migrator/main.go
Some slugs have been seen which do not have the metadata, but if they belong to a release with `git=true`, then we can just assume they are stored in the blobstore.
=> slugbuilder: Don't require metadata to convert slugs

bootstrap/manifest_template.json
The /ping endpoint tries to determine the status of the sirenia cluster, which is not running for either mariadb or mongodb at bootstrap time, so the request times out.
This used to fail immediately, but now fails after 30s since switching HTTP transports in #3698 (which is a correct fix, if you want to know the status of the sirenia cluster, you should be retrying dial errors).
=> bootstrap: Just wait for mariadb / mongodb API

bootstrap/manifest_template.json, router/http.go, router/http_test.go, router/proxyproto/LICENSE, router/proxyproto/protocol.go, router/proxyproto/protocol_test.go, router/server.go
This adds support for version 1 of the PROXY protocol to indicate the source IP for incoming HTTP and HTTPS connections.
http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt
The feature is off by default, and can be enabled by setting the environment variable `PROXY_PROTOCOL=true` while running a non-backup `flynn-host bootstrap` or configuring the router directly after bootstrap with the command:
flynn -a router env set PROXY_PROTOCOL=true
This feature is useful to integrate external load balancers in TCP mode like the AWS Classic Load Balancer (previously called ELB) and HAProxy.
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html
https://cbonte.github.io/haproxy-dconv/1.6/configuration.html#5.2-send-proxy
References #68
/cc @temujin9 …
=> router: Add support for inbound PROXY protocol v1

router/proxyproto/protocol_test.go
It is unsafe to call `t.Fatalf` from goroutines, so change to `t.Errorf`, which is safe.
Closes #3708
=> router/proxyproto: Don't call t.Fatalf from goroutines

controller/release.go, host/fixer/fixer.go
I've also updated release deletion so it doesn't delete system images.
Tested manually with:
```
script/kill-flynn
script/start-flynn-host --no-destroy-state --no-destroy-vols 0
```
We should have tests for this, I have a plan...
Fixes #3686.
=> host/fixer: Reprovision temporary volumes

cli/run.go, test/test_cli.go
closes #3707 
```
$ flynn -a postgres run --limits temp_disk=3G bash
root@b025e6c0-d24a-431c-abff-b59c2c51bed6:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         3.0G  4.6M  3.0G   1% /
tmpfs           2.0G     0  2.0G   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda1        40G   29G  8.9G  77% /.containerinit
root@b025e6c0-d24a-431c-abff-b59c2c51bed6:/# exit
exit
$ flynn -a postgres run --limits temp_disk=2G bash
root@0d48eb90-b55a-4eb9-9558-9c8dd863546e:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         2.0G  3.1M  2.0G   1% /
tmpfs           2.0G     0  2.0G   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup …
```
=> cli: allow specifying limits for run jobs

host/libcontainer_backend.go
Container cleanup emits a cleanup event which attempts to persist to the state database, but the state database is open for reading when restoring state during startup, so running cleanup can deadlock.
`Container.Watch` (which is run [in a goroutine during restore](https://github.com/flynn/flynn/blob/v20161114.0p1/host/libcontainer_backend.go#L1381)) runs the cleanup in a deferred call [here](https://github.com/flynn/flynn/blob/v20161114.0p1/host/libcontainer_backend.go#L883-L890), so there is no need to run the cleanup directly in `UnmarshalState`, thus preventing the deadlock.
=> host: Prevent deadlock when restoring state

test/test_cli.go
Events can be dropped when jobs change state quickly (see #2424), but are eventually consistent, so just wait for the eventual job down states.
=> test: Just wait for down events in CLISuite.TestRun

script/release-flynn
I believe this restores the original behavior so that if `release-flynn` is run without `--branch` or `--nightly` that the master branch will be released on the `nightly` channel.
=> script: Automatically set --nightly if releasing master

cli/git.go
This is correct, and may fix reported hangs with some versions of git.
=> cli: Treat empty line as EOF in git credential helper

controller/scheduler/scheduler.go, controller/scheduler/scheduler_test.go, controller/testutils/fake_host_client.go, controller/utils/utils.go, host/http.go, host/state.go, pkg/cluster/host.go
Loading all jobs from each host in the cluster leads to ever increasing network i/o and load in the cluster as the number of stopped jobs increases.
Once the scheduler knows a job has stopped, there is no need to sync it again, so the scheduler has been updated to just sync the starting / running jobs from each host (which should be a small number of jobs) and determine which jobs have stopped by their absence from that list.
=> scheduler: Only sync active jobs from hosts

controller/deployment.go, controller/schema.go, controller/schema/queries.go, controller/types/types.go, controller/worker/deployment/all_at_once.go, controller/worker/deployment/one_by_one.go, controller/worker/deployment/sirenia.go, schema/controller/deployment.json, test/test_scheduler.go
This is also fixed in #3667, but I would like to get this fix into the next stable release, and I don't think #3667 is ready to be merged just yet.
Fixes #3699.
=> worker: Maintain formation tags through deployments

controller/migrate_test.go, controller/schema.go
It is safe to just change this migration because any users who have managed to run it will not be affected (otherwise the migration would have failed).
=> controller: Handle app releases without formations in migration 27

gitreceive/receiver/flynn-receive.go, slugbuilder/artifact/main.go, slugbuilder/builder/build.sh
This avoids potentially matching unrelated buildpack output as the configured process types.
=> slugbuilder: Determine process types in Go

cli/release.go
Mention how to use `flynn release update--clean` in usage and make it more usable by omitting the ID from the JSON file. This usability enhancement is especially useful when using `--clean` with JSON generated by `flynn release show --json`.
=> cli: Improve usability and docs of release update --clean

demo/Makefile, util/packer/ubuntu/install.sh
I have successfully built the box locally with this change and used it with `vagrant up`.
Fixes #3785.
=> util/packer: Fix VirtualBox detection

installer/app/src/views/aws-region-picker.js.jsx, util/packer/ubuntu.json
Allows for new Canada region to be selected as an option via installer.
Need to confirm this region doesn't require any additional changes to the installer etc to fully function.
=> Add Canada Central to AWSRegionPicker

dashboard/app/lib/javascripts/dashboard/actions/app-env.js, dashboard/app/lib/javascripts/dashboard/actions/providers.js
Refs #3718 
Closes #3790
This fixes editing env and provisioning databases for an app when the app has no releases.
=> dashboard: Fix creating app releases in dashboard

Vagrantfile, demo/Vagrantfile
=> Vagrantfile: Ensure network cable is connected

cli/release.go, controller/types/types.go, controller/utils/utils.go, host/libcontainer_backend.go, host/types/types.go, pkg/exec/exec.go
This allows processes that require access to the host PID namespace for monitoring purposes etc to be run as Flynn jobs rather than being managed outside of Flynn.
Ideal for agents like Scope/Sysdig/CollectD etc.
=> host,controller: Allow jobs to be launched in host PID namespace

cli/cluster.go, controller/types/types.go, host/logmux/sink.go
Allows usage with self-signed or otherwise untrusted target syslog sinks.
Not recommended for production due to potential for man-in-the-middle attacks but very useful in development and testing environments.
=> host,cli: Syslog sink insecure

host/cli/inspect.go, host/libcontainer_backend.go, host/state.go, host/types/types.go
This exposes the container PID via the host API.
Necessary for providing PID -> container mapping in tools such as Scope that need to join on the host namespace PID.
=> host: Expose container PID

script/start-flynn-host, test/cluster/cluster.go, test/cluster2/cluster.go, test/rootfs/build.sh, test/runner/runner.go, util/flynn-in-flynn/boot.go
This updates `test/cluster2` to boot clusters on a single host using tags and reverts CI back to using multiple VMs which should hopefully make it more reliable.
=> test/runner: Boot multi node default cluster

schema/controller/expanded_formation.json, test/cluster/cluster.go, test/runner/runner.go
I've also added a fix for `ControllerSuite.TestExampleOutput` now that we have formations with tags (i.e. the flynn-in-flynn clusters).
=> test: Mount backups dir on all VMs

cli/export.go
This prevents importing under a new app name from breaking deploys.
=> cli: Rewrite app name in service from process config

host/logmux/sink.go
This was causing flynn-host to panic on shutdown when it had closed the DB but then tried to persist the logaggregator sink once it was stopped.
=> host/logmux: Ensure the DB is open when persisting sinks

host/monitor.go
So that it is started with the volume from the previous primary when rebooting a single node cluster.
Fixes #3847.
=> host: Repair MongoDB cluster before the controller

host/cli/bootstrap.go, script/bootstrap-flynn, script/generate-backups, test/test_backup.go
Restoring backups from cluster versions >= `v20161026.0` (i.e. since [this commit](https://github.com/flynn/flynn/commit/00cb6e0)) will fail to start the MongoDB / MariaDB appliances because `Release.Processes` will get set to `null` by [these SQL commands](https://github.com/flynn/flynn/blob/v20170116.0/host/cli/bootstrap.go#L356-L372) (since the `env` key no longer exists on the db type).
I've wrapped those SQL commands with a conditional, and added a test for restoring a `v20161114.0p1` backup (which fails without this change).
We need to improve our testing of backups, at the very least test that backing up a cluster with the current code can then be restored, but we need to merge this as it is affecting users.
Fixes #3816
Fixes #3843
=> bootstrap: Fix restoring from recent MongoDB / MariaDB backups

script/release-flynn
Useful when the current release is broken.
=> script: Support forcing a duplicate release

script/run-integration-tests, test/arg/arg.go, test/helper.go, test/test_host.go
When tests fail in nested clusters, it is hard to debug what has gone wrong because the cluster is destroyed.
If the tests are being run in a terminal then a bash shell will now be started before destroying the cluster:
```
test_host.go:895:
t.Fatal("fail")
... Error: fail
++ 15:24:48.545 
*****
starting bash shell with both 'flynn-host' and 'flynn' configured
to debug test failure in cluster "flynn-d84f"
run 'exit' when you're done
*****
test-debug@flynn-d84f# flynn-host list
ID                                ADDR               RAFT STATUS
29f4162630464647b001c441f9f712a1  100.100.3.18:1113  peer (leader)
3ff374e277724019825b613fa83a91f8  100.100.3.20:1113  peer
e49a510aca2b4e92875ea7e931790e8e  100.100.3.19:1113  peer
test-debug@flynn-d84f# flynn -a discoverd ps
ID …
```
=> test: Start a bash shell to debug cluster test failures

controller/types/types.go, host/logmux/sink.go, test/test_host.go
Drops structured data as it's not of any use outside of the logaggregator API.
If users want to consume this they will probably also wish to implement the logaggregator HTTP cursor API in which case we can expose the ability to create logaggregator compatible sinks.
=> host: Drop structured data when sending to syslog sink

cli/cluster.go, controller/types/types.go, host/logmux/sink.go
Add option to support non-RFC6587 compliant sinks that expect syslog lines delimited by newlines.
Fixes #3858
=> host,cli: Add newline delimited option for syslog sink

cli/ps.go
Currently the header list is output in quiet mode, which results in the following:
```
flynn02-15630c66-d3a3-44ca-809c-ca2599ff1cc1
flynn01-3b8ef01b-4d25-4f1c-89ef-d2483f7a75a1
ID  TYPE  STATE  CREATED  RELEASE
```
Which results in the following:
```sh
Job flynn02-15630c66-d3a3-44ca-809c-ca2599ff1cc1 killed.
Job flynn01-3b8ef01b-4d25-4f1c-89ef-d2483f7a75a1 killed.
ERROR: could not kill job ID: controller: resource not found
ERROR: could not kill job TYPE: controller: resource not found
ERROR: could not kill job STATE: controller: resource not found
ERROR: could not kill job CREATED: controller: resource not found
ERROR: could not kill job RELEASE: controller: resource not found
Could not kill all jobs.
```
This simply skips all header assembly and output if quiet is enabled.
=> Don't output headers in quiet mode

router/data_store.go, router/schema/queries.go
This sometimes manifests itself when migrating a domain when we add new routes with the same certificate in parallel.
=> router: Prevent race creating TLS certificates

host/logmux/sink.go
=> host/logmux: Don't attempt to close nil conn on Close

host/cli/cli-add-command.go, host/host.go
closes #2873
```
$ flynn-host cli-add-command
Install the Flynn CLI (see https://flynn.io/docs/cli for instructions) and paste the line below into a terminal window:
flynn cluster add -p iG8I30Ewxw5P76EF10ogjYKBTg3Gjfc9ulbE/Vm7IVo= default 1.localflynn.com f488bf68ea6628d1d2ec8c18907d8254
The built-in dashboard can be accessed at http://dashboard.1.localflynn.com and your login token is 6d94a7313568aaf6c0cec0e52c0d2162
```
=> host: Add 'flynn-host cli-add-command' to generate 'flynn cluster add' command

host/cli/bootstrap.go
If `DEBUG=false`, we should not print debug output.
/cc @temujin9
=> host/cli: Check value of DEBUG during bootstrap

host/http.go, host/types/types.go, pkg/cluster/host.go, test/test_host_update.go
When updating a host running in a nested cluster, the whole host dies when the original flynn-host daemon exits (because it is PID 1 in the container) so all jobs on that host also die, leading to test failures like "unexpected EOF".
The delay before exiting can now be specified by the client to give the tests more time to make assertions.
=> test: Use a longer shutdown delay in host update tests

cli/docker.go
So that the service is used rather than job events when deploying the app.
=> cli: Set service for docker-receive releases

discoverd/client/client.go
Not having a timeout meant that, after a successful dial to a discoverd server, subsequent HTTP requests could hang indefinitely, which is particular problematic for heartbeats as then the service will get marked as down even though the job is still running, so apps will become unavailable.
Reduces the need for #3792 and #3766 as services should not flap like they used to when the network becomes unreliable.
Fixes #3953
Fixes #3748
Fixes #3680
Fixes #3313
=> discoverd: Use a low HTTP client timeout

test/test_host_update.go
To help investigate why the test keeps failing in CI.
=> test: Add debug logging to TestUpdateLogs

test/test_host_update.go
This avoids a race between the new flynn-host daemon connecting to the job and the test signalling it to stop.
=> test: Fix TestUpdateLogs

host/host.go
Just a small update to the help text to include the 'volume' option to flynn-host
=> host: Updated usage to show 'volume' command

logaggregator/api_test.go, logaggregator/iterator_test.go, pkg/syslog/rfc5424/message.go, pkg/syslog/rfc5424/message_test.go, pkg/syslog/rfc5424/parser_test.go
The `TIME-SECFRAC` production in RFC 5424 only allows six digits, this patch ensures that we comply with that.
=> pkg/syslog: Truncate fractional seconds to comply with RFC

controller/scheduler/scheduler.go, controller/scheduler/volume.go
This avoids a race where two goroutines can persist a volume and try to decode the response into the volume struct concurrently.
Observed in a CI build where the scheduler crashed with `fatal error: concurrent map writes`.
=> scheduler: Prevent race persisting volumes

controller/release.go, controller/types/types.go, controller/worker/release_cleanup/handler.go, docker-receive/artifact/main.go, docker-receive/utils/utils.go, pinkerton/ref.go, pkg/imagebuilder/builder.go, test/test_docker_receive.go
Deleting a layer from the blobstore did not previously invalidate the docker-receive cache, so pushing the same image would not regenerate the layer, now it does :smile:.
Addresses the issue from [this comment](https://github.com/flynn/flynn/issues/4011#issuecomment-289174300).
/cc @temujin9
=> docker-receive: Fix deleting image layers

cli/scale.go
In an effort to fix #3983, a bug that affected versions older than v20170309.0, 6a298e8d64fb2818e6704f85d542576c2e593175 was committed which introduced a new bug for the same Flynn versions where process types that are not specified in the `flynn scale` command are scaled to zero because the existing formation map is not copied over.
This patch fixes the issue by ensuring that unspecified process types are copied over properly and not modified by `flynn scale`.
Closes #4016 
```text
$ flynn scale worker=1
scaling web: 1=>0, worker: 0=>1
17:10:02.910 ==> worker 422bca30-25ad-4aee-8202-1300e90800bf pending
17:10:02.918 ==> web host0-afdef0f0-82c5-4398-a751-87f9f3f93fc6 stopping
17:10:02.938 ==> web host0-afdef0f0-82c5-4398-a751-87f9f3f93fc6 down
17:10:02.938 ==> worker …
```
=> cli: Fix pre-ScaleRequest formation scaling

pkg/syslog/rfc5424/message.go
Some syslog timestamp parsers can't handle the variable number of fractional second digits, so always include trailing zeros.
=> pkg/syslog: Use a consistent number of secfrac digits

host/libcontainer_backend.go
This patch sets `/proc/sys/vm/overcommit_memory` to 1, which enables virtual memory overcommit and disables heuristic based denial of memory allocations (using these heuristics is the default setting of 0).
Due to the large virtual memory allocations that Go uses, and the fact that flynn-host frequently forks, the default heuristics can cause errors like this:
fork/exec /sbin/zfs: cannot allocate memory
Since we rely on the OOM killer anyway, there's no need to arbitrarily cause memory allocations to fail and we can turn off the heuristics entirely.
=> host: Force memory overcommitment

appliance/redis/cmd/flynn-redis/main_test.go
CI runs an old version of Redis which seems to handle empty passwords differently than newer versions (e.g. the version used in vagrant).
We have an outstanding task to bring CI up to date which would reveal this, but we are waiting on #3817 before doing that (I have a local branch refactoring CI based off that work).
=> appliance/redis: Set a password in TestMain_Discoverd

host/libcontainer_backend.go
This avoids flynn-in-flynn needing write access to /proc.
=> host: Only set overcommit if not already set

docs/content/production.html.md
Setting the `AUTH_KEY` for all controller types at once doesn't work because the scheduler gets deployed first and will not be able to access the web process with the new key.
/cc @temujin9
=> docs: Fix command for updating controller AUTH_KEY

cli/release.go, util/cloner/flynn-clone.sh
`flynn-clone.sh` clones a Flynn app by copying the release configuration, optionally using an environment variable whitelist file.
Example cloning an app which has `FOO` and `TOKEN` set:
```
$ flynn -a my-app env
FOO=bar
TOKEN=s3cr3t
$ echo FOO > whitelist.env
$ util/cloner/flynn-clone.sh --env-whitelist whitelist.env my-app my-app-staging
===> 02:01:10 cloning source app "my-app" from "default" cluster to destination app "my-app-staging" in "default" cluster
===> 02:01:10 getting source app
===> 02:01:10 generating destination release configuration
===> 02:01:10 filtering environment variables using whitelist:
FOO
===> 02:01:10 creating destination app
Created my-app-staging
===> 02:01:10 creating destination release
Created release 51f7e44b-0146-4c91-873e-957f9bffcbac.
Created release …
```
=> util/cloner: Add flynn-clone.sh script

installer/cluster.go, installer/digital_ocean_cluster.go
- Running `apt-get update` before installing `iptables-persistent` fixes an issue where the package isn't found.
- The install script errors out due a false-positive for flynn already being installed. Passing in the `--clean` flag is a work around.
Closes #4046
=> installer: Fix DigitalOcean

installer/app/src/base-cluster.js, installer/app/src/views/advanced-options.js.jsx, installer/app/src/views/release-channel-selector.js.jsx, installer/aws_cluster.go, installer/azure_cluster.go, installer/bare_cluster.go, installer/digital_ocean_cluster.go, installer/http.go, installer/installer.go, installer/schema.go
Adds option under "Advanced options" for release channel and version. The "More info" link opens the [releases.flynn.io](https://releases.flynn.io) page for the selected channel/version. Only versions for which there is an EC2 image available are listed for AWS (all other launchers use the install script).
Closes #2287
=> installer: Allow selecting version to install

pkg/backup/tar_writer.go
Fix for #4049.
When `syscall.Getuid()` returns a negative value zero is instead used as userid in the tar file.
This prevents userids like `00000-1` which are invalid.
Sorry for that new pull request, I previously fucked up with the branches on my fork.
=> Fix UID in backups on Windows

script/lib/aws.sh
s3cmd uses python-magic by default to figure out the MIME type of a file. Some version combinations return `text/plain` for JSON files instead of `application/json`, which breaks the Vagrant box manifest download.
Setting `--no-mime-magic` falls back to using the file extension, which is what we want.
Closes #4051
=> script/lib: Don't use magic for S3 upload MIME types

util/cedarish/Dockerfile
This is the list of sources used by the Ubuntu Core image with the universe lines uncommented.
Check with:
```
$ URL="https://partner-images.canonical.com/core/trusty/20170330/ubuntu-trusty-core-cloudimg-amd64-root.tar.gz"
$ curl -fsSL "${URL}" | tar xzO etc/apt/sources.list | grep -oP 'deb .*$' | grep -vP '(backports|multiverse)'
deb http://archive.ubuntu.com/ubuntu/ trusty main restricted
deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted
deb http://archive.ubuntu.com/ubuntu/ trusty universe
deb http://archive.ubuntu.com/ubuntu/ trusty-updates universe
deb http://archive.ubuntu.com/ubuntu/ trusty-security main restricted
deb http://archive.ubuntu.com/ubuntu/ trusty-security universe
```
Fixes #4062.
=> util/cedarish: Update apt sources

cli/install.go
Without a `usage:` section in help, docopt blows up with:
"usage:" (case-insensitive) not found.
=> cli: Fix usage for deprecated `flynn install` command

docs/content/development.html.md
https://flynn.io/docs/development links to github issues which are
labelled easy, but the label is now complexity/easy so the link
results in no entries.
Signed-off-by: Simon Amor <simon@leaky.org>
=> docs: easy issues aren't easy, they're complexity/easy

dashboard/app/lib/stylesheets/dashboard/panel.scss
When the app-list is long enough to cause a scrollbar on the middle
panel, there's not quite enough width for the github and provision
database buttons and this causes them to appear one above the other
instead of side by side.
This commit has the side-effect of reducing the padding by 0.5rem in
right-hand panel too.
Signed-off-by: Simon Amor <simon@leaky.org>
=> dashboard: Reduce github/provision button padding

test/runner/runner.go
This change ensures that builds are only triggered by new pull requests and pushes to open pull requests. Other events like requesting a review, editing the description, and labeling should not trigger a build.
=> test/runner: Only run builds for relevant PR events

pkg/imagebuilder/builder.go, test/test_docker_receive.go
Replaces tab characters in Manifest with `\t` an prevents so the error mentioned in #3910
=> Fix pushing of docker images with tab characters in env

host/libcontainer_backend.go
This is a workaround for the unregister_netdevice kernel hang that can occur when starting containers.
See these issues for more details:
https://github.com/moby/moby/issues/5618
https://github.com/kubernetes/kubernetes/issues/20096
=> host: Set bridge to promiscuous to avoid kernel bug

test/helper.go, test/test_cli.go
The `flynn/test-apps` image is not built using Docker anymore.
=> test: Use busybox for Docker image tests

Vagrantfile, test/rootfs/setup.sh
Install the protobuf compiler as a build dependency.
Required to test #3425 in CI.
=> Vagrantfile,test/rootfs: Install protoc as build dependency

util/packer/ubuntu.json
The rest was removed previously, and these bits make the template invalid.
=> util/packer: Remove vestigial amazon-ebs references

router/http.go, test/test_router.go
I made an assumption that turned out to be incorrect, about the router.Route member which gets populated for an HTTPS route. This fixes the issue, and wraps it in an integration test.
=> Fix issue with ADDITIONAL_HTTPS_PORTS

discoverd/server/dns_test.go
The kernel provides no guarantees that a UDP packet will be delivered, and this test occasionally flakes with:
read udp 127.0.0.1:43870->127.0.0.1:43733: i/o timeout
=> discoverd/server: Retry UDP test query on timeout

docs/content/languages/python.md
Was looking through docs when it said python3.4 was last available runtime. Checked given buildpacks link and saw python3.6. This PR updates the docs and specifies a runtime range up to 3.6.1.
Signed-off-by: Jay Nagpaul <jaynagpaul@gmail.com>
=> Updated supported python runtimes as per the github link

cli/remote.go
Fixes #2404.
Signed-off-by: Philip Lehmann-Boehm <philip@philiplb.de>
=> Added a hint to use -a <app> in the flynn -a <app> remote add command.

builder/build.go
This continues to be an issue on recent kernels.
This reverts commit 5cbd41d15340bba115fe9b3330cf7eb41c83089b.
=> Revert "builder: Remove kernel bug workaround"

gitreceive/server.go, test/test_git_deploy.go
When gitreceive used a cached copy of the repo, it was not properly checking out submodules. Adding `--checkout` to the `git submodule update` command fixed this.
=> gitreceive: Fix restoring submodules from cache

test/cluster/cluster.go
The unit tests rarely hang and under some circumstances trigger a rebuild of Flynn, which can take more than five minutes.
=> test: Bump unit test timeout to 20 minutes

test/test_router.go
Ensure that the configuration change is applied to the router before moving forward, by watching for the up/down job events from the deployment.
This fixes a test failure that looks like:
```
++ 17:30:41.803 /go/src/github.com/flynn/flynn/build/bin/flynn-linux-amd64.4698f835b92d4d66342307a6dfede31b9a7d8bfc6b98001b79e04842a3587658 -a dashboard route add http -s dashboard-web -p 8080 dashboard.063ab384872a5776cad013a88d0e1b71.local
unknown_error: Something went wrong
```
=> test: Fix race in RouterSuite.TestAdditionalHttpPorts

Godeps/Godeps.json, vendor/github.com/flynn/go-p9p/server.go
This fixes the `error serving conn: error reading fcall: EOF` logspam during builds.
=> vendor: Update go-p9p

host/libcontainer_backend.go
Not unlocking this mutex causes all future API calls to hang.
=> host: Ensure mutex is unlocked in error case when adding job

discoverd/main.go
The fix address the following [issue](https://github.com/flynn/flynn/issues/4227) .
Fixes #4227.
=> Remove Google DNS server as default recursors

docs/content/languages/python.md
This is an attempt to avoid new users making the same mistake as I did, explained in #4228 . It is a minor clarification of the Python version numbers.
=> Clarification of Python version numbers

controller/schema.go, controller/worker/deployment/job.go, controller/worker/deployment/one_down_one_up.go, schema/controller/common.json, test/test_deployer.go
This can be used by apps which mount external storage (e.g. NFS mounts) and are happy to sacrifice availability in favour of data consistency.
=> controller: Add one-down-one-up deploy strategy

util/cloner/flynn-clone.sh
Ensure that `appname-web` is rewritten after` appname-extra-proc-web` to avoid improperly rewriting app names where the destination app name contains the source name as a prefix.
=> util/cloner: Fix app name rewrite order

cli/release.go, cli/run.go, controller/jobs.go, controller/types/types.go, schema/controller/new_job.json
This allows process mounts to be updated with `flynn release update` and also allows one-off jobs to use mounts from a process type with `flynn run --mounts-from web`.
=> cli: Better support for custom mounts

router/proxy/reverseproxy.go, router/server.go
When the `DEBUG` env var is set, the router will log details about each request/response that it routes to a backend.
Example log message:
> t=2017-11-27T21:44:14+0000 lvl=dbug msg="request complete" app=router request_id=7d48d1a6-9174-4eb4-8cdb-49b768cfbb0e client_addr=192.0.2.200:38846 host=controller.1.localflynn.com path=/apps/router/log method=GET status=200 location= backend=100.100.60.4:80
=> router: Add request logging for debugging

controller/audit_log.go, controller/controller.go, controller/domain.go, discoverd/server/handler_test.go, pkg/httphelper/httphelper.go
When `AUDIT_LOG=true`, the controller will log details about all HTTP requests including JSON request bodies.
A comma-separated list of auth key IDs can be provided in the `AUTH_KEY_IDS` env var, with one for each configured AUTH_KEY. The corresponding ID corresponding to the key used to authorize the request, will be logged if this variable is set.
Example log message:
```text
t=2017-11-27T22:07:56+0000 lvl=info msg="request completed" component=controller req_id=01a03e5e-7ab4-46e3-b388-bf6eaa17f310 status=200 duration=3.335794ms method=POST path=/releases client_ip=192.0.2.200 key_id=foo user_agent=Go-http-client/1.1 body="{\"app_id\":\"f8fb63d8-0900-4e15-88fc-ee89439625e3\",\"artifacts\":[\"bec2eb8b-7479-48db-8848-72ef945799bd\"],\"env\":{\"AUTH_KEY\":\"[redacted]\",\"PASSWORD_A\":\"[re …
```
=> controller: Implement basic request audit logging

cli/env.go, test/test_cli.go
Show env var from job if specified, instead from app.
Fixes #4108
=> cli: show env vars from job first

script/release-components
We don't use Docker for builds.
=> script: Remove docker pull from release-components

builder/manifest.json, router/http.go, router/proxy/reverseproxy.go, router/server.go, test/test_router.go
If `ERROR_503_PAGE_URL` is set for the router app, it will get the page contents from the URL at startup and serve it as HTML whenever a 503 error is returned.
=> router: Add option for custom 503 error page

dashboard/app/lib/javascripts/dashboard/views/app-route-new.js.jsx
Set `DrainBackends: true` for routes created through the dashboard.
See e28ed409af55fed355ed8238441436437a0f6a06 (#4386)
Closes #4407
=> dashboard: Fix creating app route

script/build-flynn
This is so the release pipeline uses the builder with the following fix: https://github.com/flynn/flynn/commit/9f952dc7d93fbdb940c75edc16d322727fd3861a
=> script: Build using nightly rather than stable

controller/examples/examples.go, controller/worker/domain_migration/domain_migration.go
Some more cases of inconsistent `drain_backends` as per e28ed409a.
=> controller: Ensure Route.DrainBackends is consistent

host/logmux/logmux.go, host/logmux/sink.go
These basic timeouts prevent a potential scenario where the stdout pipe from a container fills up due to a blocked sink, in turn blocking the containerized process in a write(2) to the pipe.
Both timeouts were tested manually via code modifications due to the complexity and fragility of an integration test for these paths.
=> host/logmux: Add timeouts to sink writes

bootstrap/bootstrap.go, bootstrap/run_app_action.go, host/cleanup.sh, host/cli/bootstrap.go, test/cluster/cluster.go, test/cluster2/cluster.go, test/test_host.go
Summary:
* fix the failing `HostSuite.TestUpdate`
* increase the timeout for starting jobs in test clusters
* use a different Flannel network for test clusters to avoid clashing with the host network
* destroy test clusters that fail to boot to avoid them leaking and slowing down other tests
* retry destroying zpools when stopping a test flynn-host
=> Various CI Updates

cli/cluster.go, test/test_cli.go
When adding a cluster with `<domain>` set to a controller URL like `https://controller.example.com`, the `ControllerURL` would be set correctly but `GitURL` would end up being `https://git.https://controller.example.com`.
This fixes `GitURL` and `DockerPushURL` in the case that `<domain>` starts with `https://controller.` by stripping the prefix.
@titanous we should also update the docs to use `$CLUSTER_DOMAIN` rather than `https://controller.$CLUSTER_DOMAIN` [here](https://flynn.io/docs/cli#adding-clusters) (I don't know how to do it myself).
Fixes #4495.
=> cli: Fix cluster URLs when domain is provided as a controller URL

util/assetbuilder/build.sh
This fixes the build of `dashboard-builder` (the builder environment is quite outdated and not compatible with Bundler 2.x).
=> util/assetbuilder: Pin to Bundler 1.x

flannel/pkg/ip/iptables.go, test/test_cli.go
The `append(s)` call has no effect, it just returns `s`.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
=> remove no-op append calls

cli/cluster.go, controller/types/types.go, host/logmux/logmux.go, host/logmux/sink.go
This enables support for some log sinks that require an API key to be prefixed. Also fixed the severity/facility to not be the default 0.
=> logmux: Add support for prefixed newline format

cli/export.go
If curl gets redirected to a server that supports HTTP/2 (for example with the GCS blobstore backend), it will return output that is not parsed correctly and the export will hang.
Closes #4548
=> cli: Ensure curl in export uses HTTP/1.1

slugbuilder/builder/build.sh
Heroku has added debugging output to the detect hooks that shows up on every push. Silence it by diverting stderr to /dev/null.
=> slugbuilder: Silence stderr output from detect hooks

Gopkg.lock, builder/img/go.sh, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/net/http2/writesched.go
This addresses several HTTP/2 DoS vulnerabilities, CVE-2019-9512 and CVE-2019-9514.
=> Update to Go 1.12.8

router/http.go, router/proxy/reverseproxy.go, router/proxy/transport.go
- Errors like clients disconnecting with `DEBUG=1` will log a line with `status=499` instead of `status=503`.
- The logs now consistently use fractional milliseconds for all durations.
- context is now used consistently and updated to use the APIs available as of Go 1.3.
=> router: Use HTTP status 499 in logs for client errors

cli/cluster.go, host/cli/bootstrap.go, script/start-flynn-host, test/cluster/cluster.go, test/rootfs/build.sh, test/rootfs/setup.sh
- Fix `fmt` usage (this was causing `go test` to fail)
- Add `build/bin` to `PATH` when running unit tests (`gofmt` couldn't be found)
- Use the host `resolv.conf` (CI doesn't like Google DNS in VMs, lookups just hang)
- Enable DHCP in dev (so I can run CI in dev)
=> More CI Fixes

builder/img/ubuntu-xenial.sh, builder/manifest.json
The bionic ZFS packages are not compatible with the older xenial packages used in CI (due to a bug in recent versions of ZFS using backing files), and so the host image needs to be based off xenial so
that its ZFS package can be used to create zpools when starting test clusters.
This has no effect on the released flynn-host as the binary will continue to be built with the Go image (that is based on bionic) and the host image is only used for testing.
(This is a blind fix, I'll know if it's effective once this PR is opened and CI runs...)
=> builder: Downgrade host image to ubuntu-xenial

host/cleanup.sh, host/host.go, host/img/packages.sh, host/start.sh, script/run-integration-tests, test/cluster2/cluster.go, test/helper.go
This allows us to run nested clusters on Ubuntu hosts that are running newer kernels that would otherwise fail due to a ZFS kernel bug.
KVM will be used when running `script/run-integration-tests` if `/dev/kvm` exists.
=> host: Support starting using KVM

cli/route.go, controller/data/queries.go, controller/data/route.go, controller/data/schema.go, router/http.go, router/http_test.go, router/proxy/reverseproxy.go, router/proxy/transport.go, router/tcp.go, router/types/types.go, schema/router/route.json
This allows keep alives between the router and backends to be disabled with the `--disable-keep-alives` flag, or re-enabled with the `--enable-keep-alives` flag:
```bash
$ flynn route add http -s app-web --disable-keep-alives $domain
$ flynn route update $id --disable-keep-alives
$ flynn route update $id --enable-keep-alives
```
=> router: Support disabling keep alives

router/http_test.go, router/setup_test.go, router/sync.go
The router used to load routes from the database in a specific order to ensure that it processed root-path routes before sub-path routes, but now the routes come from the controller there is no guarantee that they are still returned in that order, so this change enforces the order once the routes are loaded.
This broken behavior was witnessed when restoring a backup that included routes with sub-paths and seeing the following in the router logs:
```
t=2020-03-28T17:58:27+0100 lvl=eror msg="Failed insert of path based route, consistency violation."
```
As well as the router test included in this PR, I've also manually tested restoring a backup with this fix and checking that sub-path routes work correctly.
=> router: Ensure root-path routes are processed before sub-path routes
